use std::{net::SocketAddr, time::Duration};
use tokio::{io::{AsyncReadExt,AsyncWriteExt}, net::TcpListener, task::JoinHandle};
use crate::{operations::NodeStatus, LifecycleFuture, NodeContext, NodeService, ServiceFailure, ServiceSpec, ALL_NODE_MODES};
pub const ADMIN_SERVICE:&str="admin-http";
#[derive(Clone, Debug)] pub struct AdminHttpConfig{pub bind:SocketAddr,pub max_request_bytes:usize,pub request_timeout:Duration}
pub struct AdminHttpService{config:AdminHttpConfig,status:NodeStatus,listener:Option<TcpListener>,task:Option<JoinHandle<()>>}
impl AdminHttpService{pub fn new(config:AdminHttpConfig,status:NodeStatus)->Self{Self{config,status,listener:None,task:None}} pub fn from_prebound(config:AdminHttpConfig,status:NodeStatus,listener:TcpListener)->Self{Self{config,status,listener:Some(listener),task:None}}}
impl NodeService for AdminHttpService{
fn spec(&self)->ServiceSpec{ServiceSpec::new(ADMIN_SERVICE,&[],ALL_NODE_MODES)}
fn start<'a>(&'a mut self,_:&'a NodeContext,_:Duration)->LifecycleFuture<'a>{Box::pin(async move{let listener=match self.listener.take(){Some(v)=>v,None=>TcpListener::bind(self.config.bind).await.map_err(|e|ServiceFailure{service:ADMIN_SERVICE,message:e.to_string()})?};let status=self.status.clone();let max=self.config.max_request_bytes;let timeout=self.config.request_timeout;self.task=Some(tokio::spawn(async move{loop{let Ok((mut stream,_))=listener.accept().await else{break};let status=status.clone();tokio::spawn(async move{let mut request=vec![0;max.min(8192)];let read=tokio::time::timeout(timeout,stream.read(&mut request)).await.ok().and_then(Result::ok).unwrap_or(0);let line=std::str::from_utf8(&request[..read]).ok().and_then(|s|s.lines().next()).unwrap_or("");let (code,body)=if line.starts_with("GET /healthz "){if status.is_healthy(){(200,"{\"healthy\":true}")}else{(503,"{\"healthy\":false}")}}else if line.starts_with("GET /readyz "){if status.is_ready(){(200,"{\"ready\":true}")}else{(503,"{\"ready\":false}")}}else{(404,"{\"error\":\"not_found\"}")};let response=format!("HTTP/1.1 {code} {}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",if code==200{"OK"}else if code==503{"Service Unavailable"}else{"Not Found"},body.len());let _=stream.write_all(response.as_bytes()).await;});}}));Ok(())})}
fn stop<'a>(&'a mut self,_:&'a NodeContext,_:Duration)->LifecycleFuture<'a>{Box::pin(async move{if let Some(task)=self.task.take(){task.abort();let _=task.await;}Ok(())})}}
