storage {
  db.engine = "LEVELDB"
  db.sync = true
  db.directory = "/var/lib/tron/data"
}
node.listen.port = 18888
node.discovery.enable = true
node.http.fullNodePort = 8090
node.rpc.port = 50051
node.jsonrpc.httpFullNodePort = 8545
node.metrics.prometheus.port = 9527
seed.node.ip.list = []
