storage {
  db.engine = "LEVELDB"
  db.sync = true
  db.directory = "/var/lib/tron-solidity/data"
}
node.discovery.enable = false
node.http.solidityPort = 8091
node.rpc.solidityPort = 50051
node.metrics.prometheus.port = 9527
seed.node.ip.list = []
node.trustNode = "127.0.0.1:59999"
