use prost::Message;
use serde::Deserialize;
use std::{fs,path::PathBuf,time::{SystemTime,UNIX_EPOCH}};
use tron_primitives::{Address20,TronAddress21};
use tron_protocol::protocol::{account::{AccountResource,FreezeV2,Frozen,UnFreezeV2},Account,Vote,Witness};
use tron_state::{SessionManager,StateStore,StoreKind};
use tron_storage::{OpenRequirements,StorageIdentity,StorageManager};
use tron_tvm::{EnergyMeter,PrecompileRegistry,Repository,TvmRules};

#[derive(Deserialize)]struct Oracle{contracts:Vec<Row>,scenarios:Vec<serde_json::Value>}
#[derive(Deserialize)]struct Row{address:String,name:String,activation:String,energy:String}
fn manager()->(PathBuf,SessionManager){let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c015-tron-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c015".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let root=StateStore::new(StorageManager::new(req).open_store(&path).unwrap());(path,SessionManager::new(root))}
fn addr(n:u32)->TronAddress21{let mut b=[0;20];b[16..].copy_from_slice(&n.to_be_bytes());TronAddress21::new(0x41,Address20::from_array(b))}
fn word(n:i64)->Vec<u8>{let mut x=vec![if n<0{255}else{0};32];x[24..].copy_from_slice(&n.to_be_bytes());x}
fn aw(a:TronAddress21)->Vec<u8>{let mut x=vec![0;32];x[12..].copy_from_slice(&a.as_bytes()[1..]);x}
fn call(reg:&PrecompileRegistry,a:u32,input:&[u8],rules:&TvmRules,repo:&mut Repository<'_>)->tron_tvm::PrecompileOutput{let mut meter=EnergyMeter::new(1_000_000).unwrap();reg.dispatch(&addr(a),input,rules,repo,&mut meter).unwrap()}
fn value(bytes:&[u8],n:usize)->i64{i64::from_be_bytes(bytes[n*32+24..n*32+32].try_into().unwrap())}

#[test]
fn inventory_activation_energy_and_oracle_rows_are_complete(){let oracle:Oracle=serde_json::from_str(include_str!("../../../../docs/oracles/c015-tron.v1.json")).unwrap();assert_eq!(oracle.contracts.len(),19);assert_eq!(oracle.scenarios.len(),5);let(path,m)=manager();let mut s=m.build_session().unwrap();let child=s.child().unwrap();let mut repo=Repository::from_session(&child);let reg=PrecompileRegistry::new();for row in &oracle.contracts{assert!(!row.name.is_empty()&&!row.activation.is_empty()&&!row.energy.is_empty());let n=u32::from_str_radix(&row.address,16).unwrap();assert!(reg.contract(&addr(n),&TvmRules::default()).is_none());}let mut vote=TvmRules::default();vote.vote=true;for n in 0x1000005..=0x100000a{assert!(reg.contract(&addr(n),&vote).is_some())}let mut freeze=TvmRules::default();freeze.freeze_v2=true;for n in 0x100000b..=0x1000015{assert!(reg.contract(&addr(n),&freeze).is_some());assert_eq!(call(&reg,n,&[],&freeze,&mut repo).energy,50)}let mut signatures=TvmRules::default();signatures.solidity_059=true;assert!(reg.contract(&addr(9),&signatures).is_some());assert!(reg.contract(&addr(10),&signatures).is_some());drop(repo);drop(child);drop(s);fs::remove_dir_all(path).unwrap()}

#[test]
fn vote_and_resource_queries_match_pinned_java_semantics(){let(path,m)=manager();let mut s=m.build_session().unwrap();let child=s.child().unwrap();let mut repo=Repository::from_session(&child);let owner=addr(0x1111);let witness=addr(0x2222);let account=Account{address:owner.as_bytes().to_vec(),allowance:77,balance:10_000_000,frozen:vec![Frozen{frozen_balance:2_000_000,expire_time:1}],frozen_v2:vec![FreezeV2{r#type:0,amount:5_000_000},FreezeV2{r#type:1,amount:7_000_000},FreezeV2{r#type:2,amount:11_000_000}],unfrozen_v2:vec![UnFreezeV2{r#type:0,unfreeze_amount:3_000_000,unfreeze_expire_time:2_000}],votes:vec![Vote{vote_address:witness.as_bytes().to_vec(),vote_count:9}],account_resource:Some(AccountResource{frozen_balance_for_energy:Some(Frozen{frozen_balance:4_000_000,expire_time:1}),..Default::default()}),..Default::default()};repo.put_account(&account);repo.put_raw(StoreKind::Witness,witness.as_bytes().to_vec(),Witness{address:witness.as_bytes().to_vec(),vote_count:123,..Default::default()}.encode_to_vec());repo.set_dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP",1000).unwrap();repo.set_dynamic_i64("TOTAL_NET_LIMIT",43).unwrap();let reg=PrecompileRegistry::new();let mut vote=TvmRules::default();vote.vote=true;assert_eq!(value(&call(&reg,0x1000006,&aw(witness),&vote,&mut repo).output,0),1);let mut input=aw(owner);input.extend(aw(witness));assert_eq!(value(&call(&reg,0x1000007,&input,&vote,&mut repo).output,0),9);assert_eq!(value(&call(&reg,0x1000008,&aw(owner),&vote,&mut repo).output,0),9);assert_eq!(value(&call(&reg,0x1000009,&aw(witness),&vote,&mut repo).output,0),123);let mut freeze=TvmRules::default();freeze.freeze_v2=true;assert_eq!(value(&call(&reg,0x100000b,&word(1),&freeze,&mut repo).output,0),43);assert_eq!(value(&call(&reg,0x100000c,&aw(owner),&freeze,&mut repo).output,0),31);let mut q=aw(owner);q.extend(word(1));assert_eq!(value(&call(&reg,0x100000d,&q,&freeze,&mut repo).output,0),7_000_000);assert_eq!(value(&call(&reg,0x1000013,&q,&freeze,&mut repo).output,0),11_000_000);let mut expire=aw(owner);expire.extend(word(2));assert_eq!(value(&call(&reg,0x100000e,&expire,&freeze,&mut repo).output,0),3_000_000);drop(repo);drop(child);drop(s);fs::remove_dir_all(path).unwrap()}

#[test]
fn resource_usage_decay_conversion_restore_and_zero_weight_match_java(){let(path,m)=manager();let mut s=m.build_session().unwrap();let child=s.child().unwrap();let mut repo=Repository::from_session(&child);let owner=addr(0x3333);let account=Account{address:owner.as_bytes().to_vec(),net_usage:1_000,latest_consume_time:100,net_window_size:100,frozen_v2:vec![FreezeV2{r#type:0,amount:5_000_000}],account_resource:Some(AccountResource{energy_usage:400,latest_consume_time_for_energy:100,energy_window_size:100,..Default::default()}),..Default::default()};repo.put_account(&account);for(k,v)in[("LATEST_BLOCK_HEADER_TIMESTAMP",375_000),("TOTAL_NET_WEIGHT",2),("TOTAL_NET_LIMIT",1_000),("TOTAL_ENERGY_WEIGHT",5),("TOTAL_ENERGY_CURRENT_LIMIT",1_000)]{repo.set_dynamic_i64(k,v).unwrap()}let reg=PrecompileRegistry::new();let rules=TvmRules{freeze_v2:true,..TvmRules::default()};let mut net=aw(owner);net.extend(word(0));let out=call(&reg,0x1000012,&net,&rules,&mut repo);assert_eq!((value(&out.output,0),value(&out.output,1)),(1_500_000,225));let mut energy=aw(owner);energy.extend(word(1));let out=call(&reg,0x1000012,&energy,&rules,&mut repo);assert_eq!((value(&out.output,0),value(&out.output,1)),(1_500_000,225));assert_eq!(value(&call(&reg,0x100000f,&net,&rules,&mut repo).output,0),3_500_000);let mut check=aw(owner);check.extend(word(2_000_000));check.extend(word(0));let out=call(&reg,0x1000011,&check,&rules,&mut repo);assert_eq!((value(&out.output,0),value(&out.output,1),value(&out.output,2)),(1_400_000,600_000,225));repo.set_dynamic_i64("TOTAL_NET_WEIGHT",0).unwrap();let out=call(&reg,0x1000012,&net,&rules,&mut repo);assert_eq!((value(&out.output,0),value(&out.output,1)),(0,225));repo.set_dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP",600_000).unwrap();let out=call(&reg,0x1000012,&net,&rules,&mut repo);assert_eq!((value(&out.output,0),value(&out.output,1)),(0,0));drop(repo);drop(child);drop(s);fs::remove_dir_all(path).unwrap()}

#[test]
fn malformed_failure_and_osaka_revert_results_are_exact(){let(path,m)=manager();let mut s=m.build_session().unwrap();let child=s.child().unwrap();let mut repo=Repository::from_session(&child);let reg=PrecompileRegistry::new();let mut vote=TvmRules::default();vote.vote=true;let out=call(&reg,0x1000007,&[],&vote,&mut repo);assert!(out.success);assert_eq!(out.output,word(0));let mut freeze=TvmRules::default();freeze.freeze_v2=true;let out=call(&reg,0x1000011,&[0],&freeze,&mut repo);assert!(out.success);assert_eq!(out.output.len(),96);let mut sig=TvmRules::default();sig.solidity_059=true;sig.osaka=true;let out=call(&reg,9,&[],&sig,&mut repo);assert!(!out.success);assert!(out.output.is_empty());assert_eq!(out.energy,1_000_000);drop(repo);drop(child);drop(s);fs::remove_dir_all(path).unwrap()}
