use serde::Deserialize;
use std::{fs,path::PathBuf,time::{SystemTime,UNIX_EPOCH}};
use tron_primitives::{Address20,TronAddress21};
use tron_state::{SessionManager,StateStore};
use tron_storage::{OpenRequirements,StorageIdentity,StorageManager};
use tron_tvm::{EnergyMeter,PrecompileRegistry,Repository,TvmRules};

#[derive(Deserialize)]struct Oracle{p256_records:Vec<P256Row>}
#[derive(Deserialize)]#[allow(non_snake_case)]struct P256Row{Input:String,Expected:String,Gas:i64}
fn decode(s:&str)->Vec<u8>{(0..s.len()).step_by(2).map(|i|u8::from_str_radix(&s[i..i+2],16).unwrap()).collect()}
fn manager()->(PathBuf,SessionManager){let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c015-standard-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c015".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let root=StateStore::new(StorageManager::new(req).open_store(&path).unwrap());(path,SessionManager::new(root))}
fn address(value:u32)->TronAddress21{let mut b=[0;20];b[16..].copy_from_slice(&value.to_be_bytes());TronAddress21::new(0x41,Address20::from_array(b))}

#[test]
fn registry_addresses_activation_energy_and_basic_results_match_java(){let(path,m)=manager();let mut s=m.build_session().unwrap();let mut child=s.child().unwrap();let mut repo=Repository::from_session(&child);let reg=PrecompileRegistry::new();let base=TvmRules::default();for n in 1..=8{assert!(reg.contract(&address(n),&base).is_some())}assert!(reg.contract(&address(0x20003),&base).is_none());assert!(reg.contract(&address(0x20009),&base).is_none());assert!(reg.contract(&address(0x100),&base).is_none());let mut evm=base.clone();evm.compatible_evm=true;assert!(reg.contract(&address(0x20003),&evm).is_some());assert!(reg.contract(&address(0x20009),&evm).is_some());let mut osaka=base.clone();osaka.osaka=true;assert!(reg.contract(&address(0x100),&osaka).is_some());let mut meter=EnergyMeter::new(1000).unwrap();let out=reg.dispatch(&address(4),b"abc",&base,&mut repo,&mut meter).unwrap();assert!(out.success);assert_eq!(out.output,b"abc");assert_eq!(out.energy,18);let mut meter=EnergyMeter::new(72).unwrap();let out=reg.dispatch(&address(2),b"abc",&base,&mut repo,&mut meter).unwrap();assert!(out.success);assert_eq!(out.output,decode("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));assert_eq!(out.energy,72);drop(repo);drop(child);drop(s);drop(m);let _=fs::remove_dir_all(path);}

#[test]
fn p256_replays_all_782_pinned_java_records_and_boundaries(){let oracle:Oracle=serde_json::from_str(include_str!("../../../../docs/oracles/c015-standard.v1.json")).unwrap();assert_eq!(oracle.p256_records.len(),782);let(path,m)=manager();let mut s=m.build_session().unwrap();let mut child=s.child().unwrap();let mut repo=Repository::from_session(&child);let reg=PrecompileRegistry::new();let mut rules=TvmRules::default();rules.osaka=true;for row in oracle.p256_records{assert_eq!(row.Gas,6900);let input=decode(&row.Input);assert_eq!(input.len(),160);let mut meter=EnergyMeter::new(6900).unwrap();let out=reg.dispatch(&address(0x100),&input,&rules,&mut repo,&mut meter).unwrap();assert!(out.success);assert_eq!(out.output,decode(&row.Expected));assert_eq!(out.energy,6900);}for n in [0usize,159,161]{let mut meter=EnergyMeter::new(6900).unwrap();let out=reg.dispatch(&address(0x100),&vec![0;n],&rules,&mut repo,&mut meter).unwrap();assert!(out.success);assert!(out.output.is_empty());assert_eq!(out.energy,6900);}drop(repo);drop(child);drop(s);drop(m);let _=fs::remove_dir_all(path);}

#[test]
fn modexp_bn128_and_blake2f_failure_boundaries_are_exact(){let(path,m)=manager();let mut s=m.build_session().unwrap();let mut child=s.child().unwrap();let mut repo=Repository::from_session(&child);let reg=PrecompileRegistry::new();let mut rules=TvmRules::default();let mut modexp=vec![0;99];modexp[31]=1;modexp[63]=1;modexp[95]=1;modexp[96]=2;modexp[97]=5;modexp[98]=13;let mut meter=EnergyMeter::new(1000).unwrap();assert_eq!(reg.dispatch(&address(5),&modexp,&rules,&mut repo,&mut meter).unwrap().output,vec![6]);let mut meter=EnergyMeter::new(500).unwrap();assert_eq!(reg.dispatch(&address(6),&[],&rules,&mut repo,&mut meter).unwrap().output,vec![0;64]);let mut meter=EnergyMeter::new(100000).unwrap();let empty_pair=reg.dispatch(&address(8),&[],&rules,&mut repo,&mut meter).unwrap();assert!(empty_pair.success);assert_eq!(empty_pair.output[31],1);rules.compatible_evm=true;let mut meter=EnergyMeter::new(100).unwrap();let invalid=reg.dispatch(&address(0x20009),&[0;212],&rules,&mut repo,&mut meter).unwrap();assert!(!invalid.success);assert_eq!(meter.remaining(),0);drop(repo);drop(child);drop(s);drop(m);let _=fs::remove_dir_all(path);}

#[test]
fn modexp_three_intervals_and_length_bounds_are_exact(){let(path,m)=manager();let mut s=m.build_session().unwrap();let child=s.child().unwrap();let mut repo=Repository::from_session(&child);let reg=PrecompileRegistry::new();let mut degenerate=vec![0;96];degenerate[62]=4;degenerate[63]=1;
 for(rules,success,fault)in[(TvmRules::default(),true,None),(TvmRules{create2_depth_timeout:true,..TvmRules::default()},false,Some(tron_tvm::VmFault::OutOfTime)),(TvmRules{create2_depth_timeout:true,osaka:true,..TvmRules::default()},false,Some(tron_tvm::VmFault::PrecompiledContract))]{let mut meter=EnergyMeter::new(1_000_000).unwrap();let out=reg.dispatch(&address(5),&degenerate,&rules,&mut repo,&mut meter).unwrap();assert_eq!(out.success,success);assert!(out.output.is_empty());assert_eq!(out.fault,fault);}
 for slot in [31usize,63,95]{let mut input=vec![0;96];input[slot-1]=4;input[slot]=1;let mut meter=EnergyMeter::new(i64::MAX).unwrap();let out=reg.dispatch(&address(5),&input,&TvmRules{osaka:true,..TvmRules::default()},&mut repo,&mut meter).unwrap();assert!(!out.success,"slot {slot}");assert!(out.output.is_empty());}
 let mut over_i32=vec![0;96];over_i32[60..64].copy_from_slice(&0x8000_0000u32.to_be_bytes());let mut meter=EnergyMeter::new(i64::MAX).unwrap();let out=reg.dispatch(&address(5),&over_i32,&TvmRules::default(),&mut repo,&mut meter).unwrap();assert!(!out.success);assert!(out.output.is_empty());
 drop(repo);drop(child);drop(s);drop(m);let _=fs::remove_dir_all(path);}
