use std::{fs,path::PathBuf,time::{SystemTime,UNIX_EPOCH}};
use tron_primitives::{Address20,TronAddress21};
use tron_state::{SessionManager,StateStore,StoreKind};
use tron_storage::{OpenRequirements,StorageIdentity,StorageManager};
use tron_tvm::{ChildStorageMode,ContractResult,EnergyMeter,Memory,OperationRegistry,Program,Repository,Stack1024,VmFault,Word,MEMORY_LIMIT,STACK_LIMIT};

fn manager(name:&str)->(PathBuf,SessionManager){let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c014-foundation-{name}-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c014".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let root=StateStore::new(StorageManager::new(req).open_store(&path).unwrap());(path,SessionManager::new(root))}
fn address(byte:u8)->TronAddress21{TronAddress21::new(0x41,Address20::from_array([byte;20]))}

#[test]
fn word_matches_tvm_signed_shift_signextend_and_address_boundaries(){let minus_one=Word::MAX;assert_eq!(Word::from(7u64).signed_div(minus_one),Word::ZERO-Word::from(7u64));assert_eq!(minus_one.sar(Word::from(256u64)),Word::MAX);assert_eq!(Word::from(1u64).shl(Word::from(256u64)),Word::ZERO);assert_eq!(Word::from(0x80u64).sign_extend(Word::ZERO).to_be_bytes()[0],0xff);assert_eq!(Word::from(0x7fu64).sign_extend(Word::ZERO),Word::from(0x7fu64));assert_eq!(Word::from_be_bytes([0x22;32]).to_tron_address().as_bytes(),&[&[0x41][..],&[0x22;20][..]].concat()[..]);assert_eq!(Word::MAX.to_i32_safe(),i32::MAX);assert_eq!(Word::MAX.low_i32(),-1);}

#[test]
fn stack_memory_program_and_fault_mapping_hold_boundaries(){let mut stack=Stack1024::default();for _ in 0..STACK_LIMIT{stack.push(Word::ONE).unwrap();}assert_eq!(stack.push(Word::ONE),Err(VmFault::StackTooLarge));assert_eq!(Stack1024::default().pop(),Err(VmFault::StackTooSmall));let mut memory=Memory::default();memory.write(31,&[1,2]).unwrap();assert_eq!(memory.soft_len(),64);assert_eq!(memory.physical_len(),1024);memory.expand(usize::MAX,0).unwrap();memory.write(MEMORY_LIMIT-1,&[9]).unwrap();assert_eq!(memory.write(MEMORY_LIMIT,&[9]),Err(VmFault::OutOfMemory));let mut overlap=Memory::default();overlap.write(0,&[1,2,3,4]).unwrap();overlap.copy_within(1,0,3).unwrap();assert_eq!(overlap.read(0,4).unwrap(),vec![1,1,2,3]);let mut p=Program::new(vec![0x61,0xaa,0x5b,0x5b]);assert_eq!(p.next_opcode(),Some(0x61));assert_eq!(p.read_push(2).to_be_bytes()[30..],[0xaa,0x5b]);assert!(!p.is_jumpdest(2));assert!(p.is_jumpdest(3));assert_eq!(VmFault::TransferFailed.contract_result(),ContractResult::TransferFailed);assert!(!VmFault::TransferFailed.spends_remaining());assert!(VmFault::StackTooLarge.spends_remaining());}

#[test]
fn repository_children_commit_revoke_zero_delete_and_session_roundtrip(){let(path,manager)=manager("journal");let mut outer=manager.build_session().unwrap();let mut execution=outer.child().unwrap();let addr=address(7);execution.store(StoreKind::Code).put(addr.as_bytes(),b"old").unwrap();let mut repo=Repository::from_session(&execution);repo.put_code(addr,b"root".to_vec());let copied=repo.begin_child(ChildStorageMode::Copied);repo.put_code(addr,b"child".to_vec());repo.set_transient(addr,Word::ONE,Word::from(2u64));repo.mark_new_contract(addr);repo.revoke_child(copied).unwrap();assert_eq!(repo.code(&addr),Some(b"root".to_vec()));assert_eq!(repo.transient(&addr,Word::ONE),Word::ZERO);assert!(!repo.is_new_contract(&addr));let slot=Word::from(9u64);let copied=repo.begin_child(ChildStorageMode::Copied);repo.set_storage(&addr,slot,Word::from(3u64),0,None);repo.revoke_child(copied).unwrap();assert_eq!(repo.storage(&addr,slot,0,None),None);let shared=repo.begin_child(ChildStorageMode::Shared);repo.set_storage(&addr,slot,Word::from(4u64),0,None);repo.revoke_child(shared).unwrap();assert_eq!(repo.storage(&addr,slot,0,None),None);repo.set_storage(&addr,slot,Word::ZERO,0,None);assert_eq!(repo.storage(&addr,slot,0,None),None);let deltas=repo.flush_into_session().unwrap();assert_eq!(deltas.len(),1);assert_eq!(execution.store(StoreKind::Code).get(addr.as_bytes()),Some(b"root".to_vec()));execution.merge().unwrap();outer.commit().unwrap();let mut reopened=manager.build_session().unwrap();assert_eq!(reopened.store(StoreKind::Code).get(addr.as_bytes()),Some(b"root".to_vec()));reopened.revoke().unwrap();drop(manager);fs::remove_dir_all(path).unwrap();}

#[test]
fn energy_and_family_registry_interfaces_are_stable(){let mut meter=EnergyMeter::new(100).unwrap();meter.spend(99).unwrap();assert_eq!(meter.remaining(),1);assert_eq!(meter.spend(2),Err(VmFault::OutOfEnergy));assert_eq!(meter.used(),100);assert_eq!(EnergyMeter::memory_cost(32).unwrap(),3);assert_eq!(OperationRegistry::integration().unwrap().registered_count(),165);}
