use std::{fs,path::PathBuf,time::{SystemTime,UNIX_EPOCH}};
use tron_primitives::{Address20,Hash32,TransactionId,TronAddress21};
use tron_state::{SessionManager,StateStore};
use tron_storage::{OpenRequirements,StorageIdentity,StorageManager};
use tron_tvm::{EnergyMeter,FrameContext,Memory,OperationContext,OperationControl,OperationEffects,Program,Repository,Stack1024,TvmRules,Unlimited,VmFault,Word,MEMORY_LIMIT};
fn manager()->(PathBuf,SessionManager){let n=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let p=std::env::temp_dir().join(format!("c014-a-{n}"));let r=OpenRequirements{identity:StorageIdentity{network:"c014a".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};(p.clone(),SessionManager::new(StateStore::new(StorageManager::new(r).open_store(&p).unwrap())))}
fn addr(b:u8)->TronAddress21{TronAddress21::new(0x41,Address20::from_array([b;20]))}
fn frame()->FrameContext{FrameContext{code_address:addr(1),context_address:addr(2),origin:addr(3),caller:addr(4),input:vec![0xaa,0xbb],call_value:Word::from(7u8),token_value:Word::ZERO,token_id:Word::ZERO,root_txid:TransactionId::new(Hash32::from_array([0;32])),contract_version:1,depth:0,is_static:false}}
fn run(op:u8,rules:TvmRules,values:&[Word])->(Result<OperationControl,tron_tvm::VmFault>,Stack1024,i64){let(p,m)=manager();let s=m.build_session().unwrap();let mut repo=Repository::from_session(&s);let mut stack=Stack1024::default();for v in values.iter().rev(){stack.push(*v).unwrap();}let mut program=Program::new(vec![op]);let mut memory=Memory::default();let mut effects=OperationEffects::default();let mut energy=EnergyMeter::new(1_000_000).unwrap();let mut limiter=Unlimited;let f=frame();let spec=tron_tvm::opcodes_a::operation_specs().iter().find(|v|v.opcode==op).unwrap();let var=spec.variants.last().unwrap();let mut ctx=OperationContext{rules:&rules,frame:&f,program:&mut program,stack:&mut stack,memory:&mut memory,effects:&mut effects,energy:&mut energy,repository:&mut repo,limiter:&mut limiter};let cost=(var.energy)(&ctx).unwrap();let result=(var.execute)(&mut ctx);drop(repo);drop(s);drop(m);fs::remove_dir_all(p).unwrap();(result,stack,cost)}
fn copy_case(op:u8,values:&[Word])->(Result<i64,VmFault>,Result<OperationControl,VmFault>,Memory){let(p,m)=manager();let s=m.build_session().unwrap();let mut repo=Repository::from_session(&s);let mut stack=Stack1024::default();for v in values.iter().rev(){stack.push(*v).unwrap();}let mut program=Program::new(vec![op,0xaa,0xbb]);let mut memory=Memory::default();let mut effects=OperationEffects::default();let mut energy=EnergyMeter::new(i64::MAX).unwrap();let mut limiter=Unlimited;let f=frame();let spec=tron_tvm::opcodes_a::operation_specs().iter().find(|v|v.opcode==op).unwrap();let var=spec.variants.last().unwrap();let mut ctx=OperationContext{rules:&TvmRules::default(),frame:&f,program:&mut program,stack:&mut stack,memory:&mut memory,effects:&mut effects,energy:&mut energy,repository:&mut repo,limiter:&mut limiter};let cost=(var.energy)(&ctx);let result=(var.execute)(&mut ctx);drop(repo);drop(s);drop(m);fs::remove_dir_all(p).unwrap();(cost,result,memory)}
#[test]fn pinned_java_inventory_has_all_54_exact_rows(){let rows=tron_tvm::opcodes_a::operation_specs();assert_eq!(rows.len(),54);assert!(rows.windows(2).all(|v|v[0].opcode<v[1].opcode));let fixture=include_str!("../../../../docs/oracles/c014-opcodes-a.v1.json");assert!(fixture.contains("\"row_count\":54"));for row in rows{assert!(fixture.contains(&format!("\"opcode\":{}",row.opcode)));}}
#[test]fn arithmetic_signed_modulo_shift_and_stack_order_match_java(){let r=TvmRules{constantinople:true,osaka:true,..Default::default()};let(_,s,e)=run(0x03,r.clone(),&[Word::from(3u8),Word::from(9u8)]);assert_eq!(s.peek(0).unwrap(),Word::MAX-Word::from(5u8));assert_eq!(e,3);let(_,s,_)=run(0x07,r.clone(),&[Word::ZERO-Word::from(7u8),Word::from(3u8)]);assert_eq!(s.peek(0).unwrap(),Word::ZERO-Word::ONE);let(_,s,_)=run(0x05,r.clone(),&[Word::ZERO-Word::from(7u8),Word::from(3u8)]);assert_eq!(s.peek(0).unwrap(),Word::ZERO-Word::from(2u8));let(_,s,_)=run(0x1d,r,&[Word::from(256u64),Word::MAX]);assert_eq!(s.peek(0).unwrap(),Word::MAX);}
#[test]fn address_width_activation_energy_and_sha3_are_exact(){let mut r=TvmRules{constantinople:true,istanbul:true,london:true,blob:true,osaka:true,multi_sign:false,..Default::default()};let(_,s,_)=run(0x30,r.clone(),&[]);assert_eq!(s.peek(0).unwrap().to_be_bytes()[11],0x41);r.multi_sign=true;let(_,s,_)=run(0x30,r.clone(),&[]);assert_eq!(s.peek(0).unwrap().to_be_bytes()[11],0);let(_,s,_)=run(0x20,r.clone(),&[Word::ZERO,Word::ZERO]);assert_eq!(s.peek(0).unwrap(),Word::from_be_bytes(tron_crypto::keccak256(&[])));let rows=tron_tvm::opcodes_a::operation_specs();assert!(!(rows.iter().find(|v|v.opcode==0x1b).unwrap().activation)(&TvmRules::default()));assert!((rows.iter().find(|v|v.opcode==0x49).unwrap().activation)(&r));}
#[test]fn copy_handlers_reject_out_of_range_before_allocation_and_accept_limit(){for op in [0x37,0x39,0x3c]{let args=|destination:usize,size:usize|if op==0x3c{vec![Word::ZERO,Word::from(destination as u64),Word::ZERO,Word::from(size as u64)]}else{vec![Word::from(destination as u64),Word::ZERO,Word::from(size as u64)]};let(cost,result,memory)=copy_case(op,&args(MEMORY_LIMIT-1,1));assert!(cost.is_ok(),"opcode {op:#x} max");assert_eq!(result,Ok(OperationControl::Continue));assert_eq!(memory.soft_len(),MEMORY_LIMIT);let(cost,result,memory)=copy_case(op,&args(0,MEMORY_LIMIT));assert!(cost.is_ok(),"opcode {op:#x} exact");assert_eq!(result,Ok(OperationControl::Continue));assert_eq!(memory.soft_len(),MEMORY_LIMIT);for(destination,size)in[(MEMORY_LIMIT,1),(i32::MAX as usize,i32::MAX as usize)]{let(cost,result,memory)=copy_case(op,&args(destination,size));assert_eq!(cost,Err(VmFault::OutOfMemory),"opcode {op:#x} destination={destination} size={size}");assert_eq!(result,Err(VmFault::OutOfMemory));assert_eq!(memory.physical_len(),0,"opcode {op:#x} allocated before rejecting");}}}
#[test]fn padded_memory_copy_zero_fills_without_temporary_buffer(){let mut memory=Memory::default();memory.write_padded(1,5,&[0xaa,0xbb],1).unwrap();assert_eq!(memory.read(0,6).unwrap(),vec![0,0xbb,0,0,0,0]);let before=memory.physical_len();assert_eq!(memory.write_padded(MEMORY_LIMIT,1,&[1],0),Err(VmFault::OutOfMemory));assert_eq!(memory.physical_len(),before);}
