use std::{fs,path::PathBuf,time::{SystemTime,UNIX_EPOCH}};
use tron_primitives::{Address20,Hash32,TransactionId,TronAddress21};
use tron_state::{SessionManager,StateStore};
use tron_storage::{OpenRequirements,StorageIdentity,StorageManager};
use tron_tvm::{EnergyMeter,FrameContext,Memory,OperationContext,OperationControl,OperationEffects,OperationRegistry,Program,Repository,Stack1024,TvmRules,Unlimited,VmFault,Word};

fn manager(name:&str)->(PathBuf,SessionManager){let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c014-b-{name}-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c014".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let root=StateStore::new(StorageManager::new(req).open_store(&path).unwrap());(path,SessionManager::new(root))}
fn address(byte:u8)->TronAddress21{TronAddress21::new(0x41,Address20::from_array([byte;20]))}
fn frame(is_static:bool)->FrameContext{FrameContext{code_address:address(1),context_address:address(2),origin:address(3),caller:address(4),input:Vec::new(),call_value:Word::ZERO,token_value:Word::ZERO,token_id:Word::ZERO,root_txid:TransactionId::new(Hash32::from_array([0x55;32])),contract_version:0,depth:0,is_static}}
fn execute(code:Vec<u8>,rules:&TvmRules,frame:&FrameContext,stack:&mut Stack1024,memory:&mut Memory,effects:&mut OperationEffects,energy:&mut EnergyMeter,repository:&mut Repository<'_>)->Result<(i64,OperationControl),VmFault>{let registry=OperationRegistry::integration().unwrap().resolve(rules);let mut program=Program::new(code);let opcode=program.next_opcode().unwrap();let resolved=registry[usize::from(opcode)].ok_or(VmFault::IllegalOperation)?;stack.check_shape(resolved.spec.required_before,resolved.spec.resulting_window)?;let mut limiter=Unlimited;let mut context=OperationContext{rules,frame,program:&mut program,stack,memory,effects,energy,repository,limiter:&mut limiter};let cost=(resolved.variant.energy)(&context)?;context.energy.spend(cost)?;let control=(resolved.variant.execute)(&mut context)?;Ok((cost,control))}

#[test]
fn registry_matches_all_88_pinned_java_rows_and_activation_windows(){let specs=tron_tvm::opcodes_b::operation_specs();assert_eq!(specs.len(),88);assert!(specs.windows(2).all(|w|w[0].opcode<w[1].opcode));let fixture=include_str!("../../../../docs/oracles/c014-opcodes-b.v1.json");assert_eq!(fixture.matches("\"opcode\":").count(),88);let base=OperationRegistry::integration().unwrap().resolve(&TvmRules::default());assert!(base[0x5c].is_none()&&base[0x5f].is_none());let rules=TvmRules{shanghai:true,cancun:true,..TvmRules::default()};let active=OperationRegistry::integration().unwrap().resolve(&rules);assert!(active[0x5c].is_some()&&active[0x5d].is_some()&&active[0x5e].is_some()&&active[0x5f].is_some());for n in 1u8..=16{let dup=&specs.iter().find(|v|v.opcode==0x7f+n).unwrap();assert_eq!((dup.required_before,dup.resulting_window),(u16::from(n),u16::from(n)+1));let swap=&specs.iter().find(|v|v.opcode==0x8f+n).unwrap();assert_eq!((swap.required_before,swap.resulting_window),(u16::from(n)+1,u16::from(n)+1));}}

#[test]
fn push_dup_swap_pop_and_push_truncation_replay(){let(path,manager)=manager("stack");let session=manager.build_session().unwrap();let mut repo=Repository::from_session(&session);let rules=TvmRules{shanghai:true,..TvmRules::default()};let f=frame(false);let mut stack=Stack1024::default();let mut memory=Memory::default();let mut effects=OperationEffects::default();let mut energy=EnergyMeter::new(100).unwrap();let(_,c)=execute(vec![0x61,0xaa],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();assert_eq!(c,OperationControl::Continue);assert_eq!(stack.pop().unwrap(),Word::from(0xaa00u64));for v in 1u8..=16{stack.push(Word::from(v)).unwrap();}execute(vec![0x8f],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();assert_eq!(stack.peek(0).unwrap(),Word::ONE);execute(vec![0x90],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();assert_eq!(stack.peek(0).unwrap(),Word::from(16u64));execute(vec![0x50],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();drop(repo);drop(session);drop(manager);fs::remove_dir_all(path).unwrap();}

#[test]
fn memory_copy_energy_storage_zero_delete_and_static_guards_replay(){let(path,manager)=manager("state");let session=manager.build_session().unwrap();let mut repo=Repository::from_session(&session);let rules=TvmRules{cancun:true,higher_cpu_memory:true,..TvmRules::default()};let f=frame(false);let mut stack=Stack1024::default();let mut memory=Memory::default();memory.write(0,&(0u8..65).collect::<Vec<_>>()).unwrap();let mut effects=OperationEffects::default();let mut energy=EnergyMeter::new(100_000).unwrap();stack.push(Word::from(33u64)).unwrap();stack.push(Word::ZERO).unwrap();stack.push(Word::from(32u64)).unwrap();let(cost,_)=execute(vec![0x5e],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();assert_eq!(cost,9);assert_eq!(memory.read(32,33).unwrap(),(0u8..33).collect::<Vec<_>>());stack.push(Word::from(9u64)).unwrap();stack.push(Word::from(7u64)).unwrap();let(cost,_)=execute(vec![0x55],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();assert_eq!(cost,20_000);assert_eq!(repo.storage(&f.context_address,Word::from(7u64),0,None),Some(Word::from(9u64)));stack.push(Word::ZERO).unwrap();stack.push(Word::from(7u64)).unwrap();let(cost,_)=execute(vec![0x55],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();assert_eq!(cost,5_000);assert_eq!(repo.storage(&f.context_address,Word::from(7u64),0,None),None);let sf=frame(true);stack.push(Word::ONE).unwrap();stack.push(Word::ONE).unwrap();assert_eq!(execute(vec![0x5d],&rules,&sf,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo),Err(VmFault::StaticViolation));drop(repo);drop(session);drop(manager);fs::remove_dir_all(path).unwrap();}

#[test]
fn jump_validation_log_limits_and_return_revert_replay(){let(path,manager)=manager("control");let session=manager.build_session().unwrap();let mut repo=Repository::from_session(&session);let rules=TvmRules::default();let f=frame(false);let mut stack=Stack1024::default();let mut memory=Memory::default();memory.write(0,&[1,2,3,4]).unwrap();let mut effects=OperationEffects::default();let mut energy=EnergyMeter::new(100_000).unwrap();stack.push(Word::from(1u64)).unwrap();assert_eq!(execute(vec![0x56,0x5b],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo),Ok((8,OperationControl::Continue)));stack.push(Word::from(1u64)).unwrap();assert_eq!(execute(vec![0x56,0x60,0x5b],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo),Err(VmFault::BadJumpDestination));stack.push(Word::from(0xabu64)).unwrap();stack.push(Word::from(4u64)).unwrap();stack.push(Word::ZERO).unwrap();let(cost,_)=execute(vec![0xa1],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();assert_eq!(cost,782);assert_eq!(effects.logs[0].topics,vec![Word::from(0xabu64).to_be_bytes()]);assert_eq!(effects.logs[0].data,vec![1,2,3,4]);for opcode in [0xf3,0xfd]{stack.push(Word::from(3u64)).unwrap();stack.push(Word::ONE).unwrap();let(_,control)=execute(vec![opcode],&rules,&f,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo).unwrap();let expected=if opcode==0xf3{OperationControl::Halt(vec![2,3,4])}else{OperationControl::Revert(vec![2,3,4])};assert_eq!(control,expected);}let sf=frame(true);stack.push(Word::ZERO).unwrap();stack.push(Word::ZERO).unwrap();assert_eq!(execute(vec![0xa0],&rules,&sf,&mut stack,&mut memory,&mut effects,&mut energy,&mut repo),Err(VmFault::StaticViolation));drop(repo);drop(session);drop(manager);fs::remove_dir_all(path).unwrap();}
