use prost::Message;
use std::time::{SystemTime,UNIX_EPOCH};
use tron_protocol::protocol::{account::{AccountResource,FreezeV2,Frozen},Account,DelegatedResource,ResourceCode};
use tron_state::{SessionManager,StateStore,StoreKind};
use tron_storage::{OpenRequirements,StorageIdentity,StorageManager};
use tron_crypto::{create2_address,internal_create_address};
use tron_primitives::{Address20,Hash32,TransactionId,TronAddress21};
use tron_tvm::{EnergyMeter,FrameContext,Memory,OperationContext,OperationControl,OperationEffects,Program,Repository,Stack1024,TvmRules,Unlimited,VmFault,Word,MEMORY_LIMIT,opcodes_c::{CallKind,child_frame,create2_address_no_ff,create_address,operation_specs,validate_deployed_code}};

fn address(b:u8)->TronAddress21{TronAddress21::new(0x41,Address20::from_array([b;20]))}
fn frame(depth:u16,is_static:bool)->FrameContext{FrameContext{code_address:address(1),context_address:address(2),origin:address(3),caller:address(4),input:vec![],call_value:Word::from(7u64),token_value:Word::from(8u64),token_id:Word::from(9u64),root_txid:TransactionId::new(Hash32::from_array([0x11;32])),contract_version:1,depth,is_static}}

#[test]
fn pinned_java_rows_have_exact_opcode_shape_activation_and_order(){
 let rows=operation_specs();
 let expected=[(0xd0,8,1),(0xd1,2,1),(0xd2,0,1),(0xd3,0,1),(0xd4,1,1),(0xd5,3,1),(0xd6,2,1),(0xd7,2,1),(0xd8,4,1),(0xd9,0,1),(0xda,2,1),(0xdb,2,1),(0xdc,0,1),(0xdd,0,1),(0xde,3,1),(0xdf,3,1),(0xf0,3,1),(0xf1,7,1),(0xf2,7,1),(0xf4,6,1),(0xf5,4,1),(0xfa,6,1),(0xff,1,0)];
 assert_eq!(rows.len(),23);for(row,(opcode,required,resulting))in rows.iter().zip(expected){assert_eq!((row.opcode,row.required_before,row.resulting_window),(opcode,required,resulting));}
 let none=TvmRules::default();for row in rows{let active=(row.activation)(&none);assert_eq!(active,matches!(row.opcode,0xf0|0xf1|0xf2|0xf4|0xfa|0xff));}
 let all=TvmRules{transfer_trc10:true,constantinople:true,solidity_059:true,freeze:true,vote:true,freeze_v2:true,..TvmRules::default()};assert!(rows.iter().all(|r|(r.activation)(&all)));
}

#[test]
fn depth_context_caller_value_token_and_static_rules_match_java(){
 let parent=frame(63,false);let dst=address(9);
 let call=child_frame(&parent,dst,Word::from(5u64),Word::from(6u64),Word::from(7u64),CallKind::Call).unwrap();assert_eq!((call.code_address,call.context_address,call.caller,call.call_value,call.depth),(dst,dst,parent.context_address,Word::from(5u64),64));
 let code=child_frame(&parent,dst,Word::from(5u64),Word::ZERO,Word::ZERO,CallKind::CallCode).unwrap();assert_eq!((code.code_address,code.context_address,code.caller),(dst,parent.context_address,parent.context_address));
 let delegated=child_frame(&parent,dst,Word::ZERO,Word::ZERO,Word::ZERO,CallKind::DelegateCall).unwrap();assert_eq!((delegated.context_address,delegated.caller,delegated.call_value,delegated.token_value,delegated.token_id),(parent.context_address,parent.caller,parent.call_value,parent.token_value,parent.token_id));
 let static_call=child_frame(&parent,dst,Word::MAX,Word::MAX,Word::MAX,CallKind::StaticCall).unwrap();assert!(static_call.is_static);assert_eq!((static_call.call_value,static_call.token_value,static_call.token_id),(Word::ZERO,Word::ZERO,Word::ZERO));
 assert!(child_frame(&frame(64,false),dst,Word::ZERO,Word::ZERO,Word::ZERO,CallKind::Call).is_none());
}

#[test]
fn create_addresses_use_root_nonce_and_create2_has_no_ff_and_code_rules(){
 let f=frame(0,false);assert_eq!(create_address(&f,-3),internal_create_address(&f.root_txid,-3));let salt=Word::from(42u64);assert_eq!(create2_address_no_ff(&f,salt,b"init",false),create2_address(&f.caller,&Hash32::from_array(salt.to_be_bytes()),b"init"));assert_eq!(create2_address_no_ff(&f,salt,b"init",true),create2_address(&f.context_address,&Hash32::from_array(salt.to_be_bytes()),b"init"));assert_eq!(validate_deployed_code(b"abc",false),Ok(600));assert_eq!(validate_deployed_code(&[0xef,0],false),Ok(400));assert_eq!(validate_deployed_code(&[0xef,0],true),Err(tron_tvm::VmFault::InvalidCode));
}

#[test]
fn create_return_data_clearing_matches_pre_and_post_osaka_returndata_ops(){
 let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c014-create-returndata-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c014".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let manager=SessionManager::new(StateStore::new(StorageManager::new(req).open_store(&path).unwrap()));let session=manager.build_session().unwrap();let mut repo=Repository::from_session(&session);
 let create=operation_specs().iter().find(|row|row.opcode==0xf0).unwrap();let create2=operation_specs().iter().find(|row|row.opcode==0xf5).unwrap();let returndata=tron_tvm::opcodes_a::operation_specs();let size=returndata.iter().find(|row|row.opcode==0x3d).unwrap();let copy=returndata.iter().find(|row|row.opcode==0x3e).unwrap();
 for(kind,osaka,expected)in[("create",false,Vec::<u8>::new()),("create2-pre-osaka",false,vec![0xaa,0xbb]),("create2-osaka",true,Vec::<u8>::new())]{
  let rules=TvmRules{constantinople:true,osaka,..Default::default()};let f=frame(64,false);let mut program=Program::new(vec![0x00]);let mut stack=Stack1024::default();let mut memory=Memory::default();let mut effects=OperationEffects{return_data:vec![0xaa,0xbb],..Default::default()};let mut energy=EnergyMeter::new(100_000).unwrap();let mut limiter=Unlimited;
  if kind=="create"{for value in [Word::ZERO,Word::ZERO,Word::ZERO]{stack.push(value).unwrap();}}else{for value in [Word::from(9u64),Word::ZERO,Word::ZERO,Word::ZERO]{stack.push(value).unwrap();}}
  let mut ctx=OperationContext{rules:&rules,frame:&f,program:&mut program,stack:&mut stack,memory:&mut memory,effects:&mut effects,energy:&mut energy,repository:&mut repo,limiter:&mut limiter};let control=if kind=="create"{(create.variants[0].execute)(&mut ctx)}else{(create2.variants[0].execute)(&mut ctx)}.unwrap();assert!(matches!(control,OperationControl::Create(_)));assert_eq!(ctx.effects.return_data,expected,"{kind}");
  (size.variants[0].execute)(&mut ctx).unwrap();assert_eq!(ctx.stack.pop().unwrap(),Word::from(expected.len() as u64),"{kind}");for value in [Word::from(expected.len() as u64),Word::ZERO,Word::ZERO]{ctx.stack.push(value).unwrap();}(copy.variants[0].execute)(&mut ctx).unwrap();assert_eq!(ctx.memory.read(0,expected.len()).unwrap(),expected,"{kind}");
 }
 drop(repo);drop(session);drop(manager);std::fs::remove_dir_all(path).unwrap();
}

#[test]
fn call_and_create_families_reject_huge_memory_ranges_before_action(){
 let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c014-memory-bounds-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c014-memory".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let manager=SessionManager::new(StateStore::new(StorageManager::new(req).open_store(&path).unwrap()));let session=manager.build_session().unwrap();let mut repo=Repository::from_session(&session);let rules=TvmRules{transfer_trc10:true,constantinople:true,..Default::default()};let f=frame(0,false);
 let huge=[Word::MAX,Word::from((MEMORY_LIMIT+1) as u64),Word::from((i64::MAX as u64)+1)];
 for opcode in [0xf1,0xf2,0xf4,0xfa,0xd0]{for bad in huge{let mut args=if opcode==0xd0{vec![Word::ZERO,Word::ZERO,Word::ZERO,Word::ZERO,bad,Word::ONE,Word::ZERO,Word::ZERO]}else if matches!(opcode,0xf4|0xfa){vec![Word::ZERO,Word::ZERO,bad,Word::ONE,Word::ZERO,Word::ZERO]}else{vec![Word::ZERO,Word::ZERO,Word::ZERO,bad,Word::ONE,Word::ZERO,Word::ZERO]};let mut stack=Stack1024::default();for value in args.drain(..).rev(){stack.push(value).unwrap();}let mut program=Program::new(vec![opcode]);let mut memory=Memory::default();let mut effects=OperationEffects::default();let mut energy=EnergyMeter::new(i64::MAX).unwrap();let mut limiter=Unlimited;let row=operation_specs().iter().find(|row|row.opcode==opcode).unwrap();let ctx=OperationContext{rules:&rules,frame:&f,program:&mut program,stack:&mut stack,memory:&mut memory,effects:&mut effects,energy:&mut energy,repository:&mut repo,limiter:&mut limiter};assert_eq!((row.variants[0].energy)(&ctx),Err(VmFault::OutOfMemory),"opcode {opcode:#x}, {bad:?}");assert_eq!(ctx.memory.physical_len(),0);}}
 for opcode in [0xf0,0xf5]{for bad in huge{let args=if opcode==0xf0{vec![Word::ZERO,bad,Word::ONE]}else{vec![Word::ZERO,bad,Word::ONE,Word::ZERO]};let mut stack=Stack1024::default();for value in args.into_iter().rev(){stack.push(value).unwrap();}let mut program=Program::new(vec![opcode]);let mut memory=Memory::default();let mut effects=OperationEffects::default();let mut energy=EnergyMeter::new(i64::MAX).unwrap();let mut limiter=Unlimited;let row=operation_specs().iter().find(|row|row.opcode==opcode).unwrap();let ctx=OperationContext{rules:&rules,frame:&f,program:&mut program,stack:&mut stack,memory:&mut memory,effects:&mut effects,energy:&mut energy,repository:&mut repo,limiter:&mut limiter};assert_eq!((row.variants[0].energy)(&ctx),Err(VmFault::OutOfMemory),"opcode {opcode:#x}, {bad:?}");assert_eq!(ctx.memory.physical_len(),0);}}
 drop(repo);drop(session);drop(manager);std::fs::remove_dir_all(path).unwrap();
}

#[test]
fn system_state_adapter_replays_java_freeze_v2_withdraw_cancel_and_rollback_deltas(){
 let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c014-system-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c014".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let manager=SessionManager::new(StateStore::new(StorageManager::new(req).open_store(&path).unwrap()));let session=manager.build_session().unwrap();
 let owner=address(2);session.store(StoreKind::Account).put(owner.as_bytes(),&Account{address:owner.as_bytes().to_vec(),balance:5_000_000,allowance:700_000,..Default::default()}.encode_to_vec()).unwrap();for(k,v)in[("LATEST_BLOCK_HEADER_TIMESTAMP",1_700_000_000_000i64),("UNFREEZE_DELAY_DAYS",14),("ALLOW_CANCEL_ALL_UNFREEZE_V2",1),("TOTAL_NET_WEIGHT",0)]{session.store(StoreKind::DynamicProperties).put(tron_state::dynamic::key(k).unwrap(),&v.to_be_bytes()).unwrap()}
 let mut repo=Repository::from_session(&session);assert!(repo.freeze_v2(&owner,Word::from(2_000_000u64),Word::ZERO).unwrap());let frozen=repo.account(&owner).unwrap().unwrap();assert_eq!((frozen.balance,frozen.frozen_v2),(3_000_000,vec![FreezeV2{r#type:ResourceCode::Bandwidth as i32,amount:2_000_000}]));assert_eq!(repo.dynamic_i64("TOTAL_NET_WEIGHT").unwrap(),Some(2));
 let checkpoint=repo.begin_child(tron_tvm::ChildStorageMode::Copied);assert!(!repo.freeze_v2(&owner,Word::from(9_000_000u64),Word::ZERO).unwrap());repo.revoke_child(checkpoint).unwrap();assert_eq!(repo.account(&owner).unwrap().unwrap().balance,3_000_000);
 assert!(repo.unfreeze_v2(&owner,Word::from(1_000_000u64),Word::ZERO).unwrap());let pending=repo.account(&owner).unwrap().unwrap();assert_eq!(pending.unfrozen_v2.len(),1);assert_eq!(pending.unfrozen_v2[0].unfreeze_amount,1_000_000);assert!(repo.cancel_all_unfreeze_v2(&owner).unwrap());let cancelled=repo.account(&owner).unwrap().unwrap();assert!(cancelled.unfrozen_v2.is_empty());assert_eq!(cancelled.frozen_v2[0].amount,2_000_000);assert_eq!(repo.withdraw_reward(&owner).unwrap(),700_000);assert_eq!(repo.account(&owner).unwrap().unwrap().balance,3_700_000);assert!(!repo.deltas().is_empty());
 drop(repo);drop(session);drop(manager);std::fs::remove_dir_all(path).unwrap();
}

#[test]
fn pinned_java_legacy_freeze_unfreeze_vectors_preserve_v1_state_and_v2_queues(){
 let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c014-legacy-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c014-legacy".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let manager=SessionManager::new(StateStore::new(StorageManager::new(req).open_store(&path).unwrap()));let session=manager.build_session().unwrap();
 let owner=address(0x21);let receiver=address(0x22);session.store(StoreKind::Account).put(owner.as_bytes(),&Account{address:owner.as_bytes().to_vec(),balance:10_000_000,..Default::default()}.encode_to_vec()).unwrap();for(k,v)in[("LATEST_BLOCK_HEADER_TIMESTAMP",1_700_000_000_000i64),("MIN_FROZEN_TIME",3),("TOTAL_NET_WEIGHT",0),("TOTAL_ENERGY_WEIGHT",0)]{session.store(StoreKind::DynamicProperties).put(tron_state::dynamic::key(k).unwrap(),&if k=="MIN_FROZEN_TIME"{(v as i32).to_be_bytes().to_vec()}else{v.to_be_bytes().to_vec()}).unwrap()}
 let mut repo=Repository::from_session(&session);assert!(repo.freeze_legacy(&owner,&owner,Word::from(2_000_000u64),Word::ZERO).unwrap());let self_frozen=repo.account(&owner).unwrap().unwrap();assert_eq!((self_frozen.balance,self_frozen.frozen,self_frozen.frozen_v2,self_frozen.unfrozen_v2),(8_000_000,vec![Frozen{frozen_balance:2_000_000,expire_time:1_700_259_200_000}],vec![],vec![]));assert_eq!(repo.dynamic_i64("TOTAL_NET_WEIGHT").unwrap(),Some(2));
 assert!(repo.freeze_legacy(&owner,&receiver,Word::from(3_000_000u64),Word::ONE).unwrap());let delegated_owner=repo.account(&owner).unwrap().unwrap();let delegated_receiver=repo.account(&receiver).unwrap().unwrap();assert_eq!(delegated_owner.balance,5_000_000);assert_eq!(delegated_owner.account_resource.as_ref().unwrap().delegated_frozen_balance_for_energy,3_000_000);assert_eq!(delegated_receiver.account_resource.as_ref().unwrap().acquired_delegated_frozen_balance_for_energy,3_000_000);assert!(delegated_owner.frozen_v2.is_empty()&&delegated_owner.unfrozen_v2.is_empty());let key=tron_state::delegation::legacy_resource_key(owner.as_bytes(),receiver.as_bytes());let delegated=DelegatedResource::decode(repo.get_raw(StoreKind::DelegatedResource,&key).unwrap().as_slice()).unwrap();assert_eq!((delegated.frozen_balance_for_energy,delegated.expire_time_for_energy),(3_000_000,1_700_259_200_000));assert_eq!(repo.dynamic_i64("TOTAL_ENERGY_WEIGHT").unwrap(),Some(3));
 assert_eq!(repo.unfreeze_legacy(&owner,&owner,Word::ZERO).unwrap(),None);assert_eq!(repo.account(&owner).unwrap().unwrap().balance,5_000_000);repo.set_dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP",1_700_259_200_000).unwrap();assert_eq!(repo.unfreeze_legacy(&owner,&owner,Word::ZERO).unwrap(),Some(2_000_000));assert_eq!(repo.unfreeze_legacy(&owner,&receiver,Word::ONE).unwrap(),Some(3_000_000));let thawed_owner=repo.account(&owner).unwrap().unwrap();let thawed_receiver=repo.account(&receiver).unwrap().unwrap();assert_eq!((thawed_owner.balance,thawed_owner.frozen,thawed_owner.frozen_v2,thawed_owner.unfrozen_v2),(10_000_000,vec![],vec![],vec![]));assert_eq!(thawed_owner.account_resource.as_ref().unwrap().delegated_frozen_balance_for_energy,0);assert_eq!(thawed_receiver.account_resource.as_ref().unwrap().acquired_delegated_frozen_balance_for_energy,0);assert_eq!((repo.dynamic_i64("TOTAL_NET_WEIGHT").unwrap(),repo.dynamic_i64("TOTAL_ENERGY_WEIGHT").unwrap()),(Some(0),Some(0)));
 let checkpoint=repo.begin_child(tron_tvm::ChildStorageMode::Copied);assert!(!repo.freeze_legacy(&owner,&owner,Word::from(20_000_000u64),Word::ZERO).unwrap());repo.revoke_child(checkpoint).unwrap();assert_eq!(repo.account(&owner).unwrap().unwrap().balance,10_000_000);drop(repo);drop(session);drop(manager);std::fs::remove_dir_all(path).unwrap();
}

#[test]
fn legacy_energy_self_path_uses_account_resource_not_freeze_v2(){
 let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c014-legacy-energy-{nonce}"));let req=OpenRequirements{identity:StorageIdentity{network:"c014-legacy-energy".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let manager=SessionManager::new(StateStore::new(StorageManager::new(req).open_store(&path).unwrap()));let session=manager.build_session().unwrap();let owner=address(0x31);session.store(StoreKind::Account).put(owner.as_bytes(),&Account{address:owner.as_bytes().to_vec(),balance:2_000_000,account_resource:Some(AccountResource::default()),..Default::default()}.encode_to_vec()).unwrap();for(k,v)in[("LATEST_BLOCK_HEADER_TIMESTAMP",10i64),("MIN_FROZEN_TIME",0),("TOTAL_ENERGY_WEIGHT",0)]{session.store(StoreKind::DynamicProperties).put(tron_state::dynamic::key(k).unwrap(),&if k=="MIN_FROZEN_TIME"{(v as i32).to_be_bytes().to_vec()}else{v.to_be_bytes().to_vec()}).unwrap()}let mut repo=Repository::from_session(&session);assert!(repo.freeze_legacy(&owner,&owner,Word::from(1_000_000u64),Word::ONE).unwrap());let frozen=repo.account(&owner).unwrap().unwrap();assert_eq!(frozen.account_resource.unwrap().frozen_balance_for_energy,Some(Frozen{frozen_balance:1_000_000,expire_time:10}));assert!(frozen.frozen_v2.is_empty()&&frozen.unfrozen_v2.is_empty());assert_eq!(repo.unfreeze_legacy(&owner,&owner,Word::ONE).unwrap(),Some(1_000_000));drop(repo);drop(session);drop(manager);std::fs::remove_dir_all(path).unwrap();
}
