use std::{fs,path::PathBuf,time::{SystemTime,UNIX_EPOCH}};
use prost::Message;
use tron_primitives::{Address20,Hash32,TransactionId,TronAddress21};
use tron_protocol::protocol::{account::{AccountResource,FreezeV2,Frozen,UnFreezeV2},Account,ResourceCode};
use tron_state::{Session,SessionManager,StateStore,StoreKind};
use tron_storage::{OpenRequirements,StorageIdentity,StorageManager};
use tron_tvm::{ContractResult,EnergyMeter,FrameContext,Interpreter,Memory,NoTrace,OperationRegistry,Program,Repository,Stack1024,TvmRules,Unlimited,Word};

fn address(byte:u8)->TronAddress21{TronAddress21::new(0x41,Address20::from_array([byte;20]))}
fn manager(name:&str)->(PathBuf,SessionManager){let nonce=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();let path=std::env::temp_dir().join(format!("c014-selfdestruct-{name}-{nonce}"));let requirements=OpenRequirements{identity:StorageIdentity{network:"c014".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};let root=StateStore::new(StorageManager::new(requirements).open_store(&path).unwrap());(path,SessionManager::new(root))}
fn frame()->FrameContext{FrameContext{code_address:address(1),context_address:address(1),origin:address(2),caller:address(3),input:Vec::new(),call_value:Word::ZERO,token_value:Word::ZERO,token_id:Word::ZERO,root_txid:TransactionId::new(Hash32::from_array([7;32])),contract_version:0,depth:0,is_static:false}}
fn put(session:&Session,account:Account){session.store(StoreKind::Account).put(&account.address,&account.encode_to_vec()).unwrap()}
fn execute(repository:&mut Repository<'_>,rules:&TvmRules,beneficiary:TronAddress21)->tron_tvm::ExecutionOutcome{let mut code=vec![0x73];code.extend_from_slice(&beneficiary.as_bytes()[1..]);code.push(0xff);let registry=OperationRegistry::integration().unwrap();let interpreter=Interpreter::new(&registry,rules);let mut program=Program::new(code);let mut stack=Stack1024::default();let mut memory=Memory::default();let mut meter=EnergyMeter::new(100_000).unwrap();let mut limiter=Unlimited;let mut trace=NoTrace;interpreter.run(&frame(),&mut program,&mut stack,&mut memory,repository,&mut meter,&mut limiter,&mut trace)}

#[test]
fn eligibility_failure_reverts_without_deltas_or_internal_transaction(){
 let(path,manager)=manager("eligibility");let session=manager.build_session().unwrap();let owner=frame().context_address;let beneficiary=address(8);put(&session,Account{address:owner.as_bytes().to_vec(),balance:77,delegated_frozen_balance_for_bandwidth:1,..Default::default()});let mut repository=Repository::from_session(&session);
 let rejected=execute(&mut repository,&TvmRules{freeze:true,..Default::default()},beneficiary);assert_eq!(rejected.contract_result,ContractResult::Revert);assert!(rejected.internal_transactions.is_empty());assert!(rejected.deltas.is_empty());assert_eq!(repository.balance(&owner).unwrap(),77);
 repository.put_account(&Account{address:owner.as_bytes().to_vec(),balance:77,frozen:vec![Frozen{frozen_balance:2_000_000,expire_time:101}],..Default::default()});repository.set_dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP",100).unwrap();let active=execute(&mut repository,&TvmRules{freeze:true,selfdestruct_restriction:true,..Default::default()},beneficiary);assert_eq!(active.contract_result,ContractResult::Revert);assert!(active.internal_transactions.is_empty());assert_eq!(repository.balance(&owner).unwrap(),77);
 repository.put_account(&Account{address:owner.as_bytes().to_vec(),balance:77,delegated_frozen_v2_balance_for_bandwidth:1,..Default::default()});let delegated=execute(&mut repository,&TvmRules{freeze_v2:true,..Default::default()},beneficiary);assert_eq!(delegated.contract_result,ContractResult::Revert);assert!(delegated.internal_transactions.is_empty());
 repository.put_account(&Account{address:owner.as_bytes().to_vec(),balance:77,unfrozen_v2:vec![UnFreezeV2{r#type:ResourceCode::Bandwidth as i32,unfreeze_amount:9,unfreeze_expire_time:101}],..Default::default()});let pending=execute(&mut repository,&TvmRules{freeze_v2:true,..Default::default()},beneficiary);assert_eq!(pending.contract_result,ContractResult::Revert);assert!(pending.internal_transactions.is_empty());
 drop(repository);drop(session);drop(manager);fs::remove_dir_all(path).unwrap();
}

#[test]
fn legacy_self_beneficiary_moves_trx_tokens_and_frozen_resources_to_configured_blackhole(){
 let(path,manager)=manager("blackhole");let session=manager.build_session().unwrap();let owner=frame().context_address;let blackhole=address(12);let mut account=Account{address:owner.as_bytes().to_vec(),balance:77,frozen:vec![Frozen{frozen_balance:2_000_000,expire_time:1}],account_resource:Some(AccountResource{frozen_balance_for_energy:Some(Frozen{frozen_balance:3_000_000,expire_time:1}),..Default::default()}),..Default::default()};account.asset_v2.insert("1000001".into(),5);put(&session,account);put(&session,Account{address:blackhole.as_bytes().to_vec(),balance:11,..Default::default()});let mut repository=Repository::from_session(&session);repository.set_blackhole_address(blackhole);repository.set_dynamic_i64("TOTAL_NET_WEIGHT",2).unwrap();repository.set_dynamic_i64("TOTAL_ENERGY_WEIGHT",3).unwrap();
 let outcome=execute(&mut repository,&TvmRules{transfer_trc10:true,freeze:true,..Default::default()},owner);assert_eq!(outcome.contract_result,ContractResult::Success);assert_eq!(outcome.deleted_accounts,vec![owner]);assert_eq!(repository.balance(&blackhole).unwrap(),5_000_088);assert_eq!(repository.token_balance(&blackhole,"1000001").unwrap(),5);assert_eq!(repository.dynamic_i64("TOTAL_NET_WEIGHT").unwrap(),Some(0));assert_eq!(repository.dynamic_i64("TOTAL_ENERGY_WEIGHT").unwrap(),Some(0));assert_eq!(outcome.internal_transactions.len(),1);assert!(!outcome.internal_transactions[0].rejected);
 drop(repository);drop(session);drop(manager);fs::remove_dir_all(path).unwrap();
}

#[test]
fn restricted_existing_self_is_noop_while_new_contract_deletes_with_expired_v2_lineage(){
 let(path,manager)=manager("restricted");let session=manager.build_session().unwrap();let owner=frame().context_address;let blackhole=address(12);let mut account=Account{address:owner.as_bytes().to_vec(),balance:77,..Default::default()};account.asset_v2.insert("1000001".into(),5);put(&session,account.clone());put(&session,Account{address:blackhole.as_bytes().to_vec(),balance:11,..Default::default()});let mut repository=Repository::from_session(&session);repository.set_blackhole_address(blackhole);
 let no_op=execute(&mut repository,&TvmRules{transfer_trc10:true,selfdestruct_restriction:true,..Default::default()},owner);assert_eq!(no_op.contract_result,ContractResult::Success);assert!(no_op.deleted_accounts.is_empty());assert_eq!(repository.balance(&owner).unwrap(),77);assert_eq!(repository.token_balance(&owner,"1000001").unwrap(),5);assert_eq!(no_op.internal_transactions.len(),1);assert!(!no_op.internal_transactions[0].rejected);
 repository.put_account(&Account{unfrozen_v2:vec![UnFreezeV2{r#type:ResourceCode::Energy as i32,unfreeze_amount:9,unfreeze_expire_time:100}],frozen_v2:vec![FreezeV2{r#type:ResourceCode::Energy as i32,amount:13}],..account});repository.set_dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP",100).unwrap();repository.mark_new_contract(owner);let deleted=execute(&mut repository,&TvmRules{transfer_trc10:true,freeze_v2:true,selfdestruct_restriction:true,..Default::default()},owner);assert_eq!(deleted.deleted_accounts,vec![owner]);assert_eq!(repository.balance(&blackhole).unwrap(),97);assert_eq!(repository.account(&blackhole).unwrap().unwrap().frozen_v2,vec![FreezeV2{r#type:ResourceCode::Energy as i32,amount:13}]);assert_eq!(deleted.internal_transactions.len(),2);assert_eq!(deleted.internal_transactions[0].value,Word::from(86u64));assert_eq!(deleted.internal_transactions[1].parent_hash,frame().root_txid.hash());assert_eq!(deleted.internal_transactions[1].note,b"withdrawExpireUnfreezeWhileSuiciding");assert_eq!(deleted.internal_transactions[1].value,Word::from(9u64));assert!(!deleted.internal_transactions[1].rejected);
 drop(repository);drop(session);drop(manager);fs::remove_dir_all(path).unwrap();
}
