//! libp2p 2.2.9 DNS tree parser and sequence-monotonic client.
use base64::{engine::general_purpose::URL_SAFE_NO_PAD,Engine};
use k256::ecdsa::{RecoveryId,Signature,VerifyingKey};
use prost::Message;
use sha3::{Digest,Keccak256};
use std::{collections::{HashSet,VecDeque},net::{IpAddr,SocketAddr},str::FromStr};
use crate::discovery::{DnsRoot,EndPoints,Endpoint};
const ROOT:&str="tree-root-v1:";const BRANCH:&str="tree-branch:";const LINK:&str="tree://";const NODES:&str="nodes:";
#[derive(Debug,thiserror::Error,PartialEq,Eq)]pub enum DnsError{#[error("invalid DNS entry: {0}")]Invalid(&'static str),#[error("bad signature")]Signature,#[error("stale sequence {new} <= {current}")]Stale{current:i32,new:i32},#[error("missing TXT record {0}")]Missing(String),#[error("tree exceeded traversal limit")]Limit}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct RootEntry{pub e_root:String,pub l_root:String,pub sequence:i32,pub signature:[u8;65],pub tree_text:String}
#[derive(Debug,Clone,PartialEq,Eq)]pub enum Entry{Root(RootEntry),Branch(Vec<String>),Link{public_key:String,domain:String},Nodes(Vec<DnsNode>)}
#[derive(Debug,Clone,PartialEq,Eq,Hash)]pub struct DnsNode{pub node_id:Vec<u8>,pub ipv4:Option<IpAddr>,pub ipv6:Option<IpAddr>,pub port:u16}
pub fn parse_entry(txt:&str)->Result<Entry,DnsError>{let txt=txt.trim_matches('"');if let Some(v)=txt.strip_prefix(ROOT){let bytes=URL_SAFE_NO_PAD.decode(v).map_err(|_|DnsError::Invalid("root base64"))?;let root=DnsRoot::decode(bytes.as_slice()).map_err(|_|DnsError::Invalid("root protobuf"))?;let tree=root.tree_root.ok_or(DnsError::Invalid("tree root"))?;let signature_text=String::from_utf8(root.signature).map_err(|_|DnsError::Invalid("signature encoding"))?;let sig=URL_SAFE_NO_PAD.decode(signature_text).map_err(|_|DnsError::Invalid("signature base64"))?;let signature:[u8;65]=sig.try_into().map_err(|_|DnsError::Invalid("signature length"))?;let e_root=String::from_utf8(tree.e_root).map_err(|_|DnsError::Invalid("e root"))?;let l_root=String::from_utf8(tree.l_root).map_err(|_|DnsError::Invalid("l root"))?;if !valid_hash(&e_root)||!valid_hash(&l_root){return Err(DnsError::Invalid("child hash"))}let tree_text=format!("e_root: \"{}\"\nl_root: \"{}\"\nseq: {}\n",e_root,l_root,tree.seq);return Ok(Entry::Root(RootEntry{e_root,l_root,sequence:tree.seq,signature,tree_text}))}if let Some(v)=txt.strip_prefix(BRANCH){return Ok(Entry::Branch(if v.is_empty(){vec![]}else{v.split(',').map(str::to_owned).collect()}))}if let Some(v)=txt.strip_prefix(LINK){let(public_key,domain)=v.split_once('@').ok_or(DnsError::Invalid("link"))?;if decode_base32(public_key).is_none(){return Err(DnsError::Invalid("public key"))}return Ok(Entry::Link{public_key:public_key.into(),domain:domain.into()})}if let Some(v)=txt.strip_prefix(NODES){let bytes=URL_SAFE_NO_PAD.decode(v.replace('"',"")).map_err(|_|DnsError::Invalid("nodes base64"))?;let endpoints=EndPoints::decode(bytes.as_slice()).map_err(|_|DnsError::Invalid("nodes protobuf"))?;return Ok(Entry::Nodes(endpoints.nodes.into_iter().map(node_from_endpoint).collect::<Result<_,_>>()?))}Err(DnsError::Invalid("unknown prefix"))}
fn node_from_endpoint(e:Endpoint)->Result<DnsNode,DnsError>{if !(1..=65535).contains(&e.port){return Err(DnsError::Invalid("port"))}let ipv4=if e.address.is_empty(){None}else{Some(IpAddr::from_str(std::str::from_utf8(&e.address).map_err(|_|DnsError::Invalid("IPv4 UTF-8"))?).map_err(|_|DnsError::Invalid("IPv4"))?)};let ipv6=if e.address_ipv6.is_empty(){None}else{Some(IpAddr::from_str(std::str::from_utf8(&e.address_ipv6).map_err(|_|DnsError::Invalid("IPv6 UTF-8"))?).map_err(|_|DnsError::Invalid("IPv6"))?)};Ok(DnsNode{node_id:e.node_id,ipv4,ipv6,port:e.port as u16})}
pub fn label(txt:&str)->String{encode_base32(&Keccak256::digest(txt.as_bytes())[..16])}
pub fn valid_hash(v:&str)->bool{v.len()==26&&!v.contains(['\r','\n'])&&decode_base32(v).is_some()}
pub fn verify_root(root:&RootEntry,key:&VerifyingKey)->Result<(),DnsError>{let sig=Signature::from_slice(&root.signature[..64]).map_err(|_|DnsError::Signature)?;let recovery=RecoveryId::from_byte(if root.signature[64]>=27{root.signature[64]-27}else{root.signature[64]}).ok_or(DnsError::Signature)?;let digest=Keccak256::digest(root.tree_text.as_bytes());let recovered=VerifyingKey::recover_from_prehash(&digest,&sig,recovery).map_err(|_|DnsError::Signature)?;if &recovered==key{Ok(())}else{Err(DnsError::Signature)}}
pub trait TxtLookup{fn lookup(&self,name:&str)->Result<Vec<String>,DnsError>;}#[derive(Debug,Clone)]pub struct SyncResult{pub sequence:i32,pub nodes:Vec<DnsNode>,pub links:Vec<(String,String)>}pub struct DnsClient<L>{lookup:L,max_records:usize}impl<L:TxtLookup>DnsClient<L>{pub fn new(lookup:L,max_records:usize)->Self{Self{lookup,max_records:max_records.max(1)}}pub fn sync(&self,domain:&str,key:&VerifyingKey,current:Option<i32>)->Result<SyncResult,DnsError>{let text=self.lookup.lookup(domain)?.into_iter().find(|v|v.trim_matches('"').starts_with(ROOT)).ok_or_else(||DnsError::Missing(domain.into()))?;let Entry::Root(root)=parse_entry(&text)?else{unreachable!()};verify_root(&root,key)?;if current.is_some_and(|v|root.sequence<=v){return Err(DnsError::Stale{current:current.unwrap(),new:root.sequence})}let mut queue=VecDeque::from([root.e_root,root.l_root]);let mut seen=HashSet::new();let mut nodes=HashSet::new();let mut links=HashSet::new();while let Some(hash)=queue.pop_front(){if !seen.insert(hash.clone()){continue}if seen.len()>self.max_records{return Err(DnsError::Limit)}let name=format!("{hash}.{domain}");let text=self.lookup.lookup(&name)?.into_iter().next().ok_or_else(||DnsError::Missing(name.clone()))?;if label(text.trim_matches('"'))!=hash{return Err(DnsError::Invalid("content hash"))}match parse_entry(&text)?{Entry::Branch(v)=>queue.extend(v),Entry::Nodes(v)=>nodes.extend(v),Entry::Link{public_key,domain}=>{links.insert((public_key,domain));},Entry::Root(_)=>return Err(DnsError::Invalid("nested root"))}}let mut nodes:Vec<_>=nodes.into_iter().collect();nodes.sort_by_key(|n|(n.ipv4,n.ipv6,n.port));let mut links:Vec<_>=links.into_iter().collect();links.sort();Ok(SyncResult{sequence:root.sequence,nodes,links})}}
pub trait DnsPublisher{type Error;fn publish_txt(&mut self,name:&str,value:&str)->Result<(),Self::Error>;}pub struct PublishPlan{pub domain:String,pub records:Vec<(String,String)>}impl PublishPlan{pub fn apply<P:DnsPublisher>(&self,p:&mut P)->Result<(),P::Error>{for(n,v)in &self.records{p.publish_txt(n,v)?}Ok(())}}
pub fn captured_ip(node:&DnsNode,captured:Option<IpAddr>)->Option<SocketAddr>{captured.or(node.ipv4).or(node.ipv6).map(|ip|SocketAddr::new(ip,node.port))}
fn encode_base32(data:&[u8])->String{const A:&[u8;32]=b"ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let(mut acc,mut bits)=(0u32,0);let mut out=String::new();for &b in data{acc=(acc<<8)|b as u32;bits+=8;while bits>=5{bits-=5;out.push(A[((acc>>bits)&31)as usize]as char)}}if bits>0{out.push(A[((acc<<(5-bits))&31)as usize]as char)}out}
fn decode_base32(s:&str)->Option<Vec<u8>>{let(mut acc,mut bits)=(0u32,0);let mut out=Vec::new();for b in s.bytes(){let v=match b.to_ascii_uppercase(){b'A'..=b'Z'=>b.to_ascii_uppercase()-b'A',b'2'..=b'7'=>b.to_ascii_uppercase()-b'2'+26,_=>return None};acc=(acc<<5)|v as u32;bits+=5;if bits>=8{bits-=8;out.push((acc>>bits)as u8)}}Some(out)}
