use std::{collections::HashSet,io::{BufRead,BufReader},net::{TcpListener as StdTcpListener,UdpSocket as StdUdpSocket},process::{Child,Command,Stdio},time::Duration};
use tokio::net::{TcpListener,TcpStream,UdpSocket};
use tokio_util::sync::CancellationToken;
use tron_network::{connection::{Direction,PoolConfig},discovery::{decode_datagram,DiscoverMessage,Endpoint as DiscoverEndpoint,Ping,Pong},handshake::{AdmissionConfig,Endpoint,HelloMessage},session::{session_event_channel,SessionConfig,SessionEvent,SessionRegistry,TransportSession},tcp::FramedIo};

fn payload()->Vec<u8>{let hex=std::env::var("C020_TCP_MESSAGE_HEX").expect("C020 Java evidence vector");assert_eq!(hex.len()%2,0);(0..hex.len()).step_by(2).map(|i|u8::from_str_radix(&hex[i..i+2],16).unwrap()).collect()}
fn java(mode:&str,port:u16)->Child{let exe=std::env::var("C020_JAVA").expect("C020_JAVA is set by c020_gate.py");let cp=std::env::var("C020_ORACLE_CP").expect("C020_ORACLE_CP is set by c020_gate.py");Command::new(exe).args(["-cp",&cp,"C020Oracle",mode,&port.to_string()]).stdout(Stdio::piped()).stderr(Stdio::inherit()).spawn().unwrap()}
fn wait_line(child:&mut Child,want:&str){let mut reader=BufReader::new(child.stdout.take().unwrap());let mut line=String::new();loop{assert!(reader.read_line(&mut line).unwrap()>0,"Java oracle exited before {want}");if line.contains(want){break}line.clear();}}
fn tcp_port()->u16{StdTcpListener::bind("127.0.0.1:0").unwrap().local_addr().unwrap().port()}
fn udp_port()->u16{StdUdpSocket::bind("127.0.0.1:0").unwrap().local_addr().unwrap().port()}
fn ep(port:u16)->DiscoverEndpoint{let hex="79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8";let node_id=(0..hex.len()).step_by(2).map(|i|u8::from_str_radix(&hex[i..i+2],16).unwrap()).collect();DiscoverEndpoint{address:b"127.0.0.1".to_vec(),port:i32::from(port),node_id,address_ipv6:vec![]}}
fn session_config(port:u16,direction:Direction)->SessionConfig{SessionConfig{local_hello:HelloMessage{from:Some(Endpoint{address:b"127.0.0.1".to_vec(),port:i32::from(port),node_id:vec![8;64],address_ipv6:vec![]}),network_id:728126428,code:0,timestamp:9,version:1},direction,admission:AdmissionConfig{network_id:728126428,version:1,max_connections:8,max_same_ip:8,trusted:HashSet::new(),ban_duration:Duration::from_secs(1)},pool:PoolConfig{min_connections:1,max_connections:8,min_active:1,max_same_ip:8,initial_backoff:Duration::from_millis(10),max_backoff:Duration::from_secs(1)},keepalive_interval:Duration::from_millis(50),pong_timeout:Duration::from_secs(1),write_timeout:Duration::from_secs(3),compression:true}}
async fn run_live(stream:TcpStream,port:u16,direction:Direction){let (tx,mut rx)=session_event_channel(64,1<<20,Duration::from_secs(1));let session=TransportSession::new(FramedIo::new(stream,Duration::from_secs(3)),stream_peer(direction),session_config(port,direction),SessionRegistry::default()).with_events(tx);let traffic=session.run(CancellationToken::new()).await.unwrap();assert!(traffic.sent_wire>traffic.sent_payload&&traffic.received_wire>traffic.received_payload);let expected=payload();let mut got=false;while let Ok(queued)=rx.try_recv(){if let SessionEvent::Message(body)=queued.into_event(){assert_eq!(body,expected);got=true}}assert!(got,"live Java peer did not deliver negotiated compressed message")}
fn stream_peer(direction:Direction)->std::net::SocketAddr{match direction{Direction::Active=>std::net::SocketAddr::from(([127,0,0,1],18888)),Direction::Passive=>std::net::SocketAddr::from(([127,0,0,1],18889))}}

#[tokio::test(flavor="current_thread")]
async fn java_netty_client_to_rust_transport_session(){let listener=TcpListener::bind("127.0.0.1:0").await.unwrap();let port=listener.local_addr().unwrap().port();let mut child=java("tcp-client",port);let(stream,_)=listener.accept().await.unwrap();run_live(stream,port,Direction::Passive).await;assert!(child.wait().unwrap().success());}

#[tokio::test(flavor="current_thread")]
async fn rust_transport_session_to_java_netty_server(){let port=tcp_port();let mut child=java("tcp-server",port);wait_line(&mut child,"READY");let stream=TcpStream::connect(("127.0.0.1",port)).await.unwrap();run_live(stream,port,Direction::Active).await;assert!(child.wait().unwrap().success());}

#[tokio::test(flavor="current_thread")]
async fn java_udp_to_rust_resolves_raw_envelope(){let socket=UdpSocket::bind("127.0.0.1:0").await.unwrap();let port=socket.local_addr().unwrap().port();let mut child=java("udp-client",port);let mut buf=[0u8;2048];let(n,from)=socket.recv_from(&mut buf).await.unwrap();assert!(matches!(decode_datagram(&buf[..n]).unwrap(),DiscoverMessage::Ping(_)));let pong=DiscoverMessage::Pong(Pong{from:Some(ep(port)),echo:7,timestamp:9}).encode_datagram().unwrap();socket.send_to(&pong,from).await.unwrap();assert!(child.wait().unwrap().success());}

#[tokio::test(flavor="current_thread")]
async fn rust_udp_to_java_resolves_raw_envelope(){let port=udp_port();let mut child=java("udp-server",port);wait_line(&mut child,"READY");let socket=UdpSocket::bind("127.0.0.1:0").await.unwrap();let ping=DiscoverMessage::Ping(Ping{from:Some(ep(socket.local_addr().unwrap().port())),to:Some(ep(port)),version:4,timestamp:9}).encode_datagram().unwrap();socket.send_to(&ping,("127.0.0.1",port)).await.unwrap();let mut buf=[0u8;2048];let(n,_)=socket.recv_from(&mut buf).await.unwrap();assert!(matches!(decode_datagram(&buf[..n]).unwrap(),DiscoverMessage::Pong(_)));assert!(child.wait().unwrap().success());}
