use prost::Message;
use tron_network::{connection::Direction,handlers::{transaction_id_from_wire,validate_block_time,HandlerDisconnect,HandlerError,TransactionHandler,TransactionSink},peer::{InventoryItem,PeerConnection}};
use tron_protocol::protocol::{transaction::Contract,Transaction,transaction,Transactions};
use std::net::{IpAddr,Ipv4Addr,SocketAddr};

fn peer()->PeerConnection{PeerConnection::new(SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST),18888),Direction::Active,0)}
fn tx(signature:usize)->Transaction{Transaction{raw_data:Some(transaction::Raw{contract:vec![Contract::default()],..Default::default()}),signature:vec![vec![7;signature]],..Default::default()}}
fn txid(transaction:&Transaction)->[u8;32]{transaction_id_from_wire(&transaction.encode_to_vec()).unwrap()}
struct Sink{processed:usize,broadcast:usize} impl TransactionSink for Sink{fn known_transaction(&self,_:&[u8;32])->bool{false}fn process_transaction(&mut self,_:Vec<u8>,_:i64)->Result<(),String>{self.processed+=1;Ok(())}fn broadcast_transaction(&mut self,_:&[u8],_:&PeerConnection){self.broadcast+=1}}
#[test]fn transactions_require_exact_request_and_signature_65_through_68(){for length in 65..=68{let transaction=tx(length);let id=txid(&transaction);let mut p=peer();p.adv_requests.insert(InventoryItem{hash:id,kind:0},1);let payload=Transactions{transactions:vec![transaction]}.encode_to_vec();let mut handler=TransactionHandler::new(2);assert_eq!(handler.receive(&mut p,&payload,2).unwrap(),1);let mut sink=Sink{processed:0,broadcast:0};assert_eq!(handler.drain(&p,&mut sink,1),1);assert_eq!((sink.processed,sink.broadcast),(1,1));}}
#[test]fn malformed_signature_is_bad_transaction_and_uncorrelated_is_bad_message(){let transaction=tx(64);let id=txid(&transaction);let payload=Transactions{transactions:vec![transaction.clone()]}.encode_to_vec();let mut p=peer();let mut handler=TransactionHandler::new(2);assert!(matches!(handler.receive(&mut p,&payload,2),Err(HandlerError::UnrequestedTransaction(_))));p.adv_requests.insert(InventoryItem{hash:id,kind:0},1);let error=handler.receive(&mut p,&payload,2).unwrap_err();assert_eq!(error.disconnect(),HandlerDisconnect::BadTransaction);assert!(matches!(error,HandlerError::BadSignatureLength{length:64,..}));}
#[test]fn signatures_and_results_do_not_change_transaction_id(){let first=tx(65);let mut second=first.clone();second.signature=vec![vec![9;68]];second.ret.push(Default::default());assert_ne!(first.encode_to_vec(),second.encode_to_vec());assert_eq!(txid(&first),txid(&second));let id=txid(&first);let mut p=peer();p.adv_requests.insert(InventoryItem{hash:id,kind:0},1);let payload=Transactions{transactions:vec![second]}.encode_to_vec();let mut handler=TransactionHandler::new(1);assert_eq!(handler.receive(&mut p,&payload,2).unwrap(),1);}
#[test]fn duplicate_transaction_is_rejected_by_raw_data_identity(){let first=tx(65);let mut second=first.clone();second.signature=vec![vec![8;68]];let id=txid(&first);let mut p=peer();p.adv_requests.insert(InventoryItem{hash:id,kind:0},1);let payload=Transactions{transactions:vec![first,second]}.encode_to_vec();let mut handler=TransactionHandler::new(2);assert!(matches!(handler.receive(&mut p,&payload,2),Err(HandlerError::DuplicateTransaction(found)) if found==id));assert_eq!(handler.queued(),0);}
#[test]fn java_advert_id_hashes_exact_preserved_raw_data_bytes(){let raw=[0x12,0x00,0xa8,0x06,0x01];let mut transaction=vec![0x0a,raw.len() as u8];transaction.extend_from_slice(&raw);transaction.extend_from_slice(&[0x12,0x01,0x07]);assert_eq!(transaction_id_from_wire(&transaction).unwrap(),[0x94,0xf0,0x8c,0xd5,0x7d,0xa9,0x97,0xc2,0x1a,0xa1,0xac,0x85,0x50,0xfb,0x99,0x22,0x39,0xc0,0xf4,0x55,0xf2,0x2e,0xeb,0xf9,0x72,0x16,0xb4,0x8e,0xa7,0x19,0x35,0xb4]);}
#[test]fn block_time_rejects_exact_three_seconds_but_accepts_one_second(){assert!(validate_block_time(4_000,1_000).is_err());assert!(validate_block_time(2_000,1_000).is_ok());}
