use std::{collections::HashSet, net::{IpAddr,Ipv4Addr,Ipv6Addr,SocketAddr}, sync::{Arc,Mutex,MutexGuard}};
use tron_network::{app_message::AppMessageType, connection::Direction, peer::{InventoryItem,PeerConnection,PeerManager}, service::*, stats::{need_to_log,InventoryKind,MessageCount,MessageStatistics,NodeStatistics,P2pTraffic,PeerStatistics,TrafficStat,TronStatsManager,NODE_STATISTICS_CACHE_LIMIT,TRAFFIC_INITIAL_DELAY_SECS,TRAFFIC_INTERVAL_SECS}, watchdog::*};
use tron_protocol::protocol::ReasonCode;
use tokio_util::sync::CancellationToken;
fn addr(n:u8)->SocketAddr{SocketAddr::from(([10,0,0,n],18888))}
fn peer(n:u8,d:Direction,now:i64)->PeerConnection{PeerConnection::new(addr(n),d,now)}

#[test]fn pinned_intervals_and_peer_status_timeouts(){assert_eq!(PEER_STATUS_INITIAL_DELAY.as_secs(),5);assert_eq!(PEER_STATUS_INTERVAL.as_secs(),2);assert_eq!((COMMON_TIMEOUT_MS,ADV_TIMEOUT_MS,SYNC_TIMEOUT_MS),(30_000,20_000,5_000));let now=100_000;let mut m=PeerManager::default();let mut common=peer(1,Direction::Active,now);common.block_both_have_update_ms=now-COMMON_TIMEOUT_MS-1;m.add(common);let mut adv=peer(2,Direction::Active,now);adv.need_sync_from_peer=false;adv.adv_requests.insert(InventoryItem{hash:[2;32],kind:1},now-ADV_TIMEOUT_MS-1);m.add(adv);let mut sync=peer(3,Direction::Active,now);sync.need_sync_from_peer=false;sync.sync_requested.insert(tron_network::peer::BlockKey{hash:vec![3],number:3},now-SYNC_TIMEOUT_MS-1);m.add(sync);let out=PeerStatusCheck.check(&mut m,now);assert_eq!(out.len(),3);assert!(m.peers().iter().all(|p|p.disconnect_reason==Some(ReasonCode::TimeOut)));}

#[test]fn effective_check_is_bounded_cached_and_times_out_handshake(){let now=1_000_000;let mut m=PeerManager::default();m.add(peer(1,Direction::Active,now));let nodes=[CandidateNode{address:addr(2),updated_ms:2},CandidateNode{address:addr(3),updated_ms:3}];let mut e=EffectiveCheck::new(true);assert_eq!(e.check(&mut m,&nodes,&HashSet::new(),now),EffectiveAction::Connect(addr(3)));e.connection_failed(addr(3));assert_eq!(e.check(&mut m,&nodes,&HashSet::new(),now+1),EffectiveAction::Connect(addr(2)));e.connection_failed(addr(2));assert_eq!(e.check(&mut m,&nodes,&HashSet::new(),now+2),EffectiveAction::None);assert_eq!(e.check(&mut m,&nodes,&HashSet::new(),now+EFFECTIVE_CACHE_MS+1),EffectiveAction::Connect(addr(3)));let mut chosen=peer(3,Direction::Active,now);chosen.connected_at_ms=now;m.add(chosen);assert!(matches!(e.check(&mut m,&nodes,&HashSet::new(),now+MAX_HANDSHAKE_MS),EffectiveAction::Disconnect(Disconnect{reason:ReasonCode::BelowThanMe,..})));assert!(has_ipv4_stack([IpAddr::V4(Ipv4Addr::LOCALHOST)]));assert!(!has_ipv4_stack([IpAddr::V6(Ipv6Addr::LOCALHOST)]));}

#[test]fn resilience_preserves_trust_and_applies_random_lan_isolation_limits(){let cfg=ResilienceConfig{max_connections:4,min_connections:3,min_active_connections:2,inactive_threshold_ms:1_000};let mut r=Resilience::new(cfg,7);let mut m=PeerManager::default();for n in 1..=4{let mut p=peer(n,Direction::Active,10_000);p.need_sync_from_peer=false;p.need_sync_from_us=false;p.last_interactive_ms=100*n as i64;p.block_received_ms=100*n as i64;if n==4{p.trusted=true}m.add(p);}let d=r.disconnect_random(&mut m,10_000).unwrap();assert_eq!(d.reason,ReasonCode::RandomElimination);assert_ne!(d.address,addr(4));let d=r.disconnect_lan(&mut m,10_000).unwrap();assert_eq!(d.reason,ReasonCode::BadProtocol);assert_ne!(d.address,addr(4));let mut iso=PeerManager::default();for n in 1..=5{let mut p=peer(n,if n<=2{Direction::Active}else{Direction::Passive},10_000);p.need_sync_from_peer=false;p.need_sync_from_us=false;p.last_interactive_ms=n as i64;if n==5{p.trusted=true}iso.add(p);}let out=r.disconnect_isolated(&mut iso,0,61_000);assert_eq!(out.len(),2);assert!(out.iter().all(|d|d.address!=addr(5)));assert_eq!(iso.connected().count(),3);}
#[test]fn fetch_block_selects_fast_idle_alternate_and_times_out(){let now=1000;let mut hash=[0u8;32];hash[..8].copy_from_slice(&11i64.to_be_bytes());let item=InventoryItem{hash,kind:2};let mut m=PeerManager::default();let mut old=peer(1,Direction::Active,now);old.fetch_latency_p75_ms=800.0;m.add(old);let mut fast=peer(2,Direction::Active,now);fast.fetch_latency_p75_ms=100.0;fast.remember_received(item.clone(),now);m.add(fast);let mut f=FetchBlockService::new(500);f.fetch_block(&[hash],addr(1),10,now);assert_eq!(f.process(&mut m,now+100),FetchAction::Request{peer:addr(2),item});let mut f=FetchBlockService::new(500);f.fetch_block(&[hash],addr(1),10,now);assert_eq!(f.process(&mut m,now+500),FetchAction::Cleared);}

#[test]fn message_count_ring_reset_statistics_and_logging_match_java(){let mut c=MessageCount::new(10);c.add(2,10);c.add(3,11);assert_eq!(c.count(2,11),5);assert_eq!(c.count(61,11),0);c.reset_total();assert_eq!(c.total(),0);assert_eq!(c.count(2,11),5);c.add(7,72);assert_eq!(c.count(60,72),7);let mut s=MessageStatistics::new(0);s.record(true,AppMessageType::Inventory,Some((InventoryKind::Transaction,4)),None,1);assert_eq!(s.total(true,TrafficStat::Message),1);assert_eq!(s.total(true,TrafficStat::TrxInventory),1);assert_eq!(s.total(true,TrafficStat::TrxInventoryElement),4);s.record(false,AppMessageType::Transactions,None,Some(3),1);assert_eq!(s.total(false,TrafficStat::Transaction),3);assert!(!need_to_log(AppMessageType::Ping,None));assert!(!need_to_log(AppMessageType::Inventory,Some(InventoryKind::Transaction)));assert!(need_to_log(AppMessageType::Inventory,Some(InventoryKind::Block)));}

#[test]fn node_peer_and_manager_statistics_match_disconnect_and_work(){assert_eq!((TRAFFIC_INITIAL_DELAY_SECS,TRAFFIC_INTERVAL_SECS),(1,1));let mut node=NodeStatistics::default();assert_eq!(node.disconnect_reason(),ReasonCode::Unknown);node.disconnected_remote(ReasonCode::Requested);assert_eq!(node.disconnect_reason(),ReasonCode::Requested);node.disconnected_local(ReasonCode::BadProtocol);assert_eq!(node.disconnect_reason(),ReasonCode::BadProtocol);assert_eq!(node.disconnect_times(),2);let peer_stats=PeerStatistics::new(0);assert_eq!(peer_stats.message_statistics.total(true,TrafficStat::Message),0);let mut manager=TronStatsManager::default();let ip=IpAddr::V4(Ipv4Addr::new(127,0,0,2));assert_eq!(manager.node_statistics(ip).disconnect_reason(),ReasonCode::Unknown);let first=P2pTraffic{tcp_in:5,tcp_out:7,udp_in:11,udp_out:13};assert_eq!(manager.work(first),tron_network::stats::TrafficDelta{tcp_in:5,tcp_out:7,udp_in:11,udp_out:13});let second=P2pTraffic{tcp_in:8,tcp_out:9,udp_in:17,udp_out:20};assert_eq!(manager.work(second),tron_network::stats::TrafficDelta{tcp_in:3,tcp_out:2,udp_in:6,udp_out:7});assert_eq!(manager.previous(),second);for n in 0..=NODE_STATISTICS_CACHE_LIMIT{manager.node_statistics(IpAddr::V4(Ipv4Addr::from((n as u32).wrapping_add(1))));}assert_eq!(manager.node_count(),NODE_STATISTICS_CACHE_LIMIT);}

type Log=Arc<Mutex<Vec<(bool,Component)>>>;
fn locked(log:&Log)->MutexGuard<'_,Vec<(bool,Component)>>{log.lock().unwrap_or_else(|e|e.into_inner())}
struct Recorder{component:Component,log:Log,fail:bool}
impl Lifecycle for Recorder{fn start(&mut self,_:CancellationToken)->Result<(),String>{locked(&self.log).push((true,self.component));if self.fail{Err("boom".into())}else{Ok(())}}fn close(&mut self)->Result<(),String>{locked(&self.log).push((false,self.component));Ok(())}}
fn components(log:&Log,fail:Option<Component>)->Vec<ComponentService>{START_ORDER.into_iter().map(|c|ComponentService{component:c,lifecycle:Box::new(Recorder{component:c,log:log.clone(),fail:fail==Some(c)})}).collect()}
#[test]fn service_composes_config_and_starts_closes_in_java_order(){let log=Arc::new(Mutex::new(Vec::new()));let cfg=P2pConfig{active_nodes:vec![addr(1)],fast_forward_nodes:vec![addr(2)],max_connections:4,min_connections:9,min_active_connections:8,ip:None,ipv6:Some(Ipv6Addr::LOCALHOST),ipv6_enabled:false,..Default::default()};let params=NetworkParameters{persisted_nodes:vec![addr(3)],external_ip:Some(IpAddr::V4(Ipv4Addr::new(1,2,3,4)))};let mut service=TronNetService::new(cfg,&params,components(&log,None));assert_eq!(service.config().min_connections,4);assert_eq!(service.config().min_active_connections,4);assert!(service.config().trust_nodes.contains(&addr(1).ip()));assert!(service.config().trust_nodes.contains(&addr(2).ip()));assert_eq!(service.config().ip,params.external_ip);assert!(service.config().ipv6.is_none());service.start().unwrap();service.close().unwrap();let got=locked(&log);assert_eq!(got.iter().filter(|x|x.0).map(|x|x.1).collect::<Vec<_>>(),START_ORDER);assert_eq!(got.iter().filter(|x|!x.0).map(|x|x.1).collect::<Vec<_>>(),CLOSE_ORDER);}
#[test]fn service_cancels_and_drains_started_components_on_failure(){let log=Arc::new(Mutex::new(Vec::new()));let mut service=TronNetService::new(P2pConfig::default(),&NetworkParameters::default(),components(&log,Some(Component::FetchBlock)));assert!(service.start().is_err());assert!(!service.is_running());let got=locked(&log);assert_eq!(got.iter().filter(|x|!x.0).map(|x|x.1).collect::<Vec<_>>(),vec![Component::Adv,Component::Sync,Component::Resilience,Component::PeerStatus,Component::Transactions,Component::Transport]);}
