#[path = "support/c013_replay.rs"]
mod c013_replay;

use std::{fs,path::PathBuf,time::{SystemTime,UNIX_EPOCH}};
use prost::Message;
use tron_execution::{Actuator,ActuatorResult,ExecutionConfig,ProposalCreateActuator,ProposalApproveActuator,ProposalDeleteActuator,ExchangeCreateActuator,ExchangeInjectActuator,ExchangeWithdrawActuator,ExchangeTransactionActuator,validate_proposal_parameter};
use tron_protocol::{google::protobuf::Any,protocol::{Account,Exchange,Proposal,ProposalApproveContract,ProposalCreateContract,ProposalDeleteContract,ExchangeCreateContract,ExchangeInjectContract,ExchangeWithdrawContract,ExchangeTransactionContract,Witness}};
use tron_state::{dynamic,Session,SessionManager,StateStore,StoreKind}; use tron_storage::{OpenRequirements,StorageIdentity,StorageManager};
const ORACLE:&str=include_str!("../../../../docs/oracles/c013-proposal-exchange-real.v1.json"); const OWNER:[u8;21]=[0x41;21]; const TOKEN:&[u8]=b"1000001";
fn path(n:&str)->PathBuf{std::env::temp_dir().join(format!("c013-pe-{n}-{}-{}",std::process::id(),SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()))}
fn manager(n:&str)->(PathBuf,SessionManager){let p=path(n);let r=OpenRequirements{identity:StorageIdentity{network:"c013".into(),genesis:"00".into()},schema_version:1,backend:"rustlog".into(),backend_format:"rustlog-v1".into(),supported_features:vec!["rustlog-v1".into()]};(p.clone(),SessionManager::new(StateStore::new(StorageManager::new(r).open_store(&p).unwrap())))}
fn long(s:&Session,n:&str,v:i64){s.store(StoreKind::DynamicProperties).put(dynamic::key(n).unwrap(),&v.to_be_bytes()).unwrap()} fn any<M:Message>(n:&str,m:&M)->Any{Any{type_url:format!("type.googleapis.com/{n}"),value:m.encode_to_vec()}}
fn setup(s:&Session){for(n,v)in[("LATEST_PROPOSAL_NUM",0),("LATEST_EXCHANGE_NUM",0),("LATEST_BLOCK_HEADER_TIMESTAMP",1_700_000_000_000),("NEXT_MAINTENANCE_TIME",1_700_001_000_000),("MAINTENANCE_TIME_INTERVAL",21_600_000),("PROPOSAL_EXPIRE_TIME",259_200_000),("ALLOW_SAME_TOKEN_NAME",1),("EXCHANGE_CREATE_FEE",100),("EXCHANGE_BALANCE_LIMIT",1_000_000_000_000_000),("ALLOW_HARDEN_EXCHANGE_CALCULATION",0),("ALLOW_TVM_SHANGHAI",1),("ALLOW_BLACKHOLE_OPTIMIZATION",1),("BURN_TRX_AMOUNT",0)]{long(s,n,v)}let mut a=Account{address:OWNER.to_vec(),balance:10_000_000,..Default::default()};a.asset_v2.insert("1000001".into(),10_000_000);s.store(StoreKind::Account).put(&OWNER,&a.encode_to_vec()).unwrap();let w=Witness{address:OWNER.to_vec(),..Default::default()};s.store(StoreKind::Witness).put(&OWNER,&w.encode_to_vec()).unwrap()}
fn account(s:&Session)->Account{Account::decode(s.store(StoreKind::Account).get(&OWNER).unwrap().as_slice()).unwrap()} fn exchange(s:&Session)->Exchange{Exchange::decode(s.store(StoreKind::ExchangeV2).get(&1_i64.to_be_bytes()).unwrap().as_slice()).unwrap()}
#[test]fn java_direct_oracle_is_bound(){let v:serde_json::Value=serde_json::from_str(ORACLE).unwrap();assert_eq!(v["schema"],"c013-proposal-exchange-real.v1");assert_eq!(v["rows"].as_array().unwrap().len(),5);assert!(ORACLE.contains("trade-hardened"));}
#[test]fn proposal_full_id_surface_rejects_gaps_and_enforces_dependencies(){let(p,m)=manager("util");let mut s=m.build_session().unwrap();setup(&s);let c=tron_execution::ValidationContext::new(&s,ExecutionConfig::default(),None);assert!(validate_proposal_parameter(&c,98,1).is_ok());assert!(validate_proposal_parameter(&c,27,1).is_err());assert!(validate_proposal_parameter(&c,36,1).is_err());assert!(validate_proposal_parameter(&c,95,1).is_ok());drop(c);s.revoke().unwrap();drop(m);fs::remove_dir_all(p).unwrap();}
#[test]fn proposal_create_approve_delete_round_trip(){let(p,m)=manager("proposal");let mut s=m.build_session().unwrap();setup(&s);let mut parameters=std::collections::BTreeMap::new();parameters.insert(61,5_000);let create=ProposalCreateContract{owner_address:OWNER.to_vec(),parameters};ProposalCreateActuator::new(any("protocol.ProposalCreateContract",&create)).unwrap().execute(&s,Some(&mut ActuatorResult::default()),ExecutionConfig::default()).unwrap();let mut proposal=Proposal::decode(s.store(StoreKind::Proposal).get(&1_i64.to_be_bytes()).unwrap().as_slice()).unwrap();assert!(proposal.expiration_time>proposal.create_time);let approve=ProposalApproveContract{owner_address:OWNER.to_vec(),proposal_id:1,is_add_approval:true};ProposalApproveActuator::new(any("protocol.ProposalApproveContract",&approve)).unwrap().execute(&s,Some(&mut ActuatorResult::default()),ExecutionConfig::default()).unwrap();proposal=Proposal::decode(s.store(StoreKind::Proposal).get(&1_i64.to_be_bytes()).unwrap().as_slice()).unwrap();assert_eq!(proposal.approvals,vec![OWNER.to_vec()]);let delete=ProposalDeleteContract{owner_address:OWNER.to_vec(),proposal_id:1};ProposalDeleteActuator::new(any("protocol.ProposalDeleteContract",&delete)).unwrap().execute(&s,Some(&mut ActuatorResult::default()),ExecutionConfig::default()).unwrap();proposal=Proposal::decode(s.store(StoreKind::Proposal).get(&1_i64.to_be_bytes()).unwrap().as_slice()).unwrap();assert_eq!(proposal.state,3);s.revoke().unwrap();drop(m);fs::remove_dir_all(p).unwrap();}
#[test]fn exchange_create_inject_withdraw_trade_legacy_and_hardened(){for hardened in [0,1]{let(p,m)=manager(if hardened==0{"legacy"}else{"hard"});let mut s=m.build_session().unwrap();setup(&s);long(&s,"ALLOW_HARDEN_EXCHANGE_CALCULATION",hardened);let create=ExchangeCreateContract{owner_address:OWNER.to_vec(),first_token_id:b"_".to_vec(),first_token_balance:1_000_000,second_token_id:TOKEN.to_vec(),second_token_balance:2_000_000};let mut result=ActuatorResult::default();ExchangeCreateActuator::new(any("protocol.ExchangeCreateContract",&create)).unwrap().execute(&s,Some(&mut result),ExecutionConfig::default()).unwrap();assert_eq!(result.exchange_id,1);let inject=ExchangeInjectContract{owner_address:OWNER.to_vec(),exchange_id:1,token_id:b"_".to_vec(),quant:50_000};ExchangeInjectActuator::new(any("protocol.ExchangeInjectContract",&inject)).unwrap().execute(&s,Some(&mut result),ExecutionConfig::default()).unwrap();assert_eq!(result.exchange_inject_another_amount,100_000);let withdraw=ExchangeWithdrawContract{owner_address:OWNER.to_vec(),exchange_id:1,token_id:b"_".to_vec(),quant:10_000};ExchangeWithdrawActuator::new(any("protocol.ExchangeWithdrawContract",&withdraw)).unwrap().execute(&s,Some(&mut result),ExecutionConfig::default()).unwrap();assert!(result.exchange_withdraw_another_amount>0);let trade=ExchangeTransactionContract{owner_address:OWNER.to_vec(),exchange_id:1,token_id:b"_".to_vec(),quant:20_000,expected:1};ExchangeTransactionActuator::new(any("protocol.ExchangeTransactionContract",&trade)).unwrap().execute(&s,Some(&mut result),ExecutionConfig::default()).unwrap();assert!(result.exchange_received_amount>0);assert!(exchange(&s).first_token_balance>0);assert!(account(&s).asset_v2["1000001"]>0);s.revoke().unwrap();drop(m);fs::remove_dir_all(p).unwrap();}}

#[test]
fn instrumented_java_proposal_exchange_invocations_replay_exactly() {
    let replay = c013_replay::replay("proposal_exchange");
    assert_eq!(replay.captured_invocations, 926);
    assert_eq!(replay.total_unique, 868);
    assert_eq!(replay.executed_unique, 232);
    assert_eq!(replay.explicit_exclusions, 0);
}

#[test]
fn zero_invocation_java_helpers_have_explicit_rust_dispositions() {
    assert_eq!(c013_replay::prove_zero_invocation_methods("proposal_exchange"), 3);
}
