use tron_config::toolkit::{toolkit_capabilities, validate_toolkit_backend, PlatformFacts};
use tron_storage::{OpenRequirements, StorageIdentity, StorageManager};

use crate::cli::*;
use crate::db::{self, DbServices};
use crate::error::{CommandOutput, ErrorCategory, ToolkitError};

pub struct ProductionDbServices { pub platform: PlatformFacts }
impl ProductionDbServices { pub fn new(platform: PlatformFacts) -> Self { Self { platform } } }
fn requirements(platform:&PlatformFacts,selector:&StorageSelector)->Result<OpenRequirements,ToolkitError>{
    let capabilities=toolkit_capabilities(platform.clone());
    let identity=validate_toolkit_backend(&capabilities,selector.backend).map_err(|e|{use tron_config::toolkit::ToolkitCapabilityError::*;match e{FuturePlatform{..}=>categorized(ErrorCategory::UnsupportedPlatform,e.to_string()),UnsupportedPlatform{..}=>categorized(ErrorCategory::UnsupportedPlatform,e.to_string()),JavaReferenceOnly{..}|UnknownBackend(_)=>categorized(ErrorCategory::UnsupportedBackend,e.to_string())}})?;
    Ok(OpenRequirements{identity:StorageIdentity{network:selector.network.clone(),genesis:selector.genesis.clone()},schema_version:selector.schema_version,backend:identity.backend.into(),backend_format:identity.backend_format.into(),supported_features:selector.features.clone()})
}
fn db_error(error:db::inspect::DbFailure)->ToolkitError{if matches!(error.logical_exit,402..=405){ToolkitError::Parity{code:error.logical_exit,stdout:Vec::new(),stderr:error.render().into_bytes()}}else{ToolkitError::Categorized{category:category(error.category),detail:error.detail}}}
fn storage_error(error:tron_storage::StorageError)->ToolkitError{match error{tron_storage::StorageError::RewriteRejected{category:cat,detail}=>ToolkitError::Categorized{category:category(cat),detail},tron_storage::StorageError::Format(e)=>db_error(db::inspect::DbFailure::from_format(e)),tron_storage::StorageError::DiskFull{..}=>categorized(ErrorCategory::DiskFull,error.to_string()),tron_storage::StorageError::Permission{..}=>categorized(ErrorCategory::Permission,error.to_string()),tron_storage::StorageError::Locked{..}=>categorized(ErrorCategory::Locked,error.to_string()),tron_storage::StorageError::ConcurrentOpen{..}=>categorized(ErrorCategory::ConcurrentOpen,error.to_string()),other=>categorized(ErrorCategory::Integrity,other.to_string())}}
fn categorized(category:ErrorCategory,detail:String)->ToolkitError{ToolkitError::Categorized{category,detail}}
fn category(name:&str)->ErrorCategory{match name{"java_format"=>ErrorCategory::JavaFormat,"not_found"=>ErrorCategory::NotFound,"not_directory"=>ErrorCategory::NotDirectory,"destination_exists"=>ErrorCategory::DestinationExists,"source_not_directory"=>ErrorCategory::SourceNotDirectory,"unsupported_migration"=>ErrorCategory::UnsupportedMigration,"integrity"=>ErrorCategory::Integrity,"not_applicable"=>ErrorCategory::NotApplicable,"invalid_lite_dataset"=>ErrorCategory::InvalidLiteDataset,"incompatible_lite_dataset"=>ErrorCategory::IncompatibleLiteDataset,"recovery_required"=>ErrorCategory::RecoveryRequired,"permission"=>ErrorCategory::Permission,"locked"=>ErrorCategory::Locked,"disk_full"=>ErrorCategory::DiskFull,"concurrent_open"=>ErrorCategory::ConcurrentOpen,_=>ErrorCategory::Integrity}}
fn ok()->Result<CommandOutput,ToolkitError>{Ok(CommandOutput::success())}

impl DbServices for ProductionDbServices {
 fn convert(&mut self,a:&ConvertArgs)->Result<CommandOutput,ToolkitError>{db::transfer::convert(&a.source,&a.destination).map_err(db_error)?;ok()}
 fn archive(&mut self,a:&ArchiveArgs)->Result<CommandOutput,ToolkitError>{let outcome=db::archive::archive(&a.database_directory,&requirements(&self.platform,&a.selector)?,a.manifest_size_mib,usize::try_from(a.batch_size).unwrap_or(usize::MAX)).map_err(db_error)?;Ok(CommandOutput::stdout(db::archive::render_output(&a.database_directory,&outcome)))}
 fn copy(&mut self,a:&CopyArgs)->Result<CommandOutput,ToolkitError>{let outcome=db::transfer::copy(&a.source,&a.destination,&requirements(&self.platform,&a.selector)?).map_err(db_error)?;Ok(CommandOutput::stdout(match outcome{db::transfer::TransferOutcome::NoOp=>format!("{} does not contain any database.\n",a.source.display()).into_bytes(),db::transfer::TransferOutcome::Published(_)=>b"copy db done, fails: [], take 0 s.\n".to_vec()}))}
 fn checkpoint(&mut self,a:&CheckpointArgs)->Result<CommandOutput,ToolkitError>{db::transfer::checkpoint(&a.source,&a.destination,&requirements(&self.platform,&a.selector)?).map_err(db_error)?;Ok(CommandOutput::stdout(format!("checkpoint created: {}\n",a.destination.display()).into_bytes()))}
 fn lite(&mut self,a:&LiteArgs)->Result<CommandOutput,ToolkitError>{let req=requirements(&self.platform,&a.selector)?;let manager=StorageManager::new(req);let output=match a.operation{LiteOperation::Split=>{db::lite::rewrite_split(&manager,&db::lite::SplitRequest{source:a.fullnode_data_path.clone(),dataset_path:a.dataset_path.clone(),kind:match a.kind{LiteKind::Snapshot=>db::lite::LiteKind::Snapshot,LiteKind::History=>db::lite::LiteKind::History},identity:db::lite::DatasetIdentity{network:a.selector.network.clone(),genesis:a.selector.genesis.clone(),schema_version:a.selector.schema_version},recent_blocks:65536,exclude_historical_balance:a.exclude_historical_balance,max_batch_operations:1024}).map_err(storage_error)?;match a.kind{LiteKind::Snapshot=>"Create snapshot done.\n",LiteKind::History=>"Create history done.\n"}}LiteOperation::Merge=>{db::lite::rewrite_merge(&manager,&db::lite::MergeRequest{snapshot:a.fullnode_data_path.clone(),history:a.dataset_path.clone(),max_batch_operations:1024}).map_err(storage_error)?;"Merge history data to database done.\n"}};Ok(CommandOutput::stdout(output.as_bytes()))}
 fn move_store(&mut self,a:&MoveArgs)->Result<CommandOutput,ToolkitError>{match a{MoveArgs::Rust{source,destination,selector}=>{db::transfer::move_whole(source,destination,&requirements(&self.platform,selector)?).map_err(db_error)?;}MoveArgs::JavaCompatibility{database_directory,config}=>{db::transfer::reject_java_compatibility_move(database_directory,config).map_err(db_error)?;}}Ok(CommandOutput::stdout(b"move db done.\n"))}
 fn root(&mut self,a:&RootArgs)->Result<CommandOutput,ToolkitError>{let roots=db::root::calculate_roots(&a.path,&a.stores,&requirements(&self.platform,&a.selector)?).map_err(db_error)?;if roots.is_empty(){return Err(ToolkitError::Parity{code:404,stdout:Vec::new(),stderr:format!(" {} does not exist.\n",a.path.display()).into_bytes()})}Ok(CommandOutput::stdout(if a.json{db::root::render_json(&roots).map_err(db_error)?}else{db::root::render_text(&roots)}))}
 fn inspect(&mut self,a:&InspectArgs)->Result<CommandOutput,ToolkitError>{let value=db::inspect::inspect(&a.path).map_err(|e|db_error(db::inspect::DbFailure::from_format(e)))?;if a.json{let kind=match value.kind{db::inspect::InspectionKind::Missing=>serde_json::json!({"classification":"missing"}),db::inspect::InspectionKind::Empty=>serde_json::json!({"classification":"empty"}),db::inspect::InspectionKind::InitializingEmpty=>serde_json::json!({"classification":"initializing_empty"}),db::inspect::InspectionKind::Java{marker}=>serde_json::json!({"classification":"java","marker":marker,"guidance":db::inspect::JAVA_REJECTION_GUIDANCE}),db::inspect::InspectionKind::Rust(m)=>serde_json::json!({"classification":"rust","manifest_version":m.manifest_version,"schema_version":m.schema_version,"network":m.network,"genesis":m.genesis,"backend":m.backend,"backend_format":m.backend_format,"features":m.features,"generation":m.generation,"state":format!("{:?}",m.state).to_ascii_lowercase(),"parent_generation":m.parent_generation,"state_root":m.state_root})};let mut bytes=serde_json::to_vec(&serde_json::json!({"path":a.path.to_string_lossy(),"kind":kind})).map_err(|e|categorized(ErrorCategory::Integrity,e.to_string()))?;bytes.push(b'\n');Ok(CommandOutput::stdout(bytes))}else{Ok(CommandOutput::stdout(format!("{}: {:?}\n",a.path.display(),value.kind).into_bytes()))}}
 fn backup(&mut self,a:&BackupArgs)->Result<CommandOutput,ToolkitError>{db::transfer::backup(&a.source,&a.backup_directory,&a.name,&requirements(&self.platform,&a.selector)?).map_err(db_error)?;Ok(CommandOutput::stdout(format!("backup created: {}\n",a.backup_directory.join(&a.name).display()).into_bytes()))}
 fn migrate(&mut self,a:&MigrateArgs)->Result<CommandOutput,ToolkitError>{db::migration::migrate(&a.path,&requirements(&self.platform,&a.selector)?,a.target_schema).map_err(db_error)?;Ok(CommandOutput::stdout(format!("migration started: schema {}\n",a.target_schema).into_bytes()))}
 fn resume(&mut self,a:&ResumeArgs)->Result<CommandOutput,ToolkitError>{db::migration::resume(&a.path,&requirements(&self.platform,&a.selector)?).map_err(db_error)?;Ok(CommandOutput::stdout(b"migration resumed.\n"))}
 fn rollback(&mut self,a:&RollbackArgs)->Result<CommandOutput,ToolkitError>{db::migration::rollback(&a.path,&requirements(&self.platform,&a.selector)?).map_err(db_error)?;Ok(CommandOutput::stdout(b"migration rolled back.\n"))}
 fn capabilities(&mut self,a:&CapabilitiesArgs)->Result<CommandOutput,ToolkitError>{let c=toolkit_capabilities(self.platform.clone());let state=|s|format!("{s:?}").to_ascii_lowercase();if a.json{let backends=c.backends.iter().map(|b|serde_json::json!({"backend":b.backend.cli_name(),"state":state(b.state),"readable":b.readable,"writable":b.writable,"reason":b.reason})).collect::<Vec<_>>();let value=serde_json::json!({"platform":c.platform_id,"os":c.facts.os,"architecture":c.facts.architecture,"target":c.facts.target,"state":state(c.state),"reason":c.reason,"backends":backends,"migration_edges":Vec::<String>::new()});let mut bytes=serde_json::to_vec(&value).map_err(|e|categorized(ErrorCategory::Integrity,e.to_string()))?;bytes.push(b'\n');Ok(CommandOutput::stdout(bytes))}else{let mut text=format!("platform: {}\nstate: {}\n",c.platform_id,state(c.state));if let Some(reason)=c.reason{text.push_str(&format!("reason: {reason}\n"))}for b in c.backends{text.push_str(&format!("backend: {} state={} readable={} writable={}{}\n",b.backend.cli_name(),state(b.state),b.readable,b.writable,b.reason.map(|r|format!(" reason={r}")).unwrap_or_default()))}text.push_str("migration-edges: none\n");Ok(CommandOutput::stdout(text.into_bytes()))}}
}
