use std::sync::Arc;

use prost::Message;
use serde_json::{json, Value};
use tron_primitives::Hash32;
use tron_protocol::{google::protobuf::Any, protocol::{transaction::contract::ContractType, Block, CreateSmartContract, SmartContract, Transaction, TransactionInfo, TransferAssetContract, TransferContract, TriggerSmartContract}};
use tron_state::{dynamic, StoreKind};

use crate::jsonrpc_filters::{decode_filter_id, encode_filter_id, FilterChanges, FilterError, FilterManager, FilterView, LogFilter, RpcLog};
use crate::jsonrpc_methods::JsonRpcBackend;
use crate::jsonrpc_types::{address_hex, bytes_hex, decode_hex, parse_address, parse_block_tag, parse_hash, parse_quantity, quantity, BlockTag, BuildArguments, CallArguments, JsonRpcError};
use crate::{ApiContext, ApiCursor, ApiError, RpcDomainProvider, WalletMutation, WalletQuery};

#[derive(Clone)]
pub struct ContextJsonRpcBackend { context:ApiContext, provider:RpcDomainProvider, cursor:ApiCursor, filters:Arc<FilterManager> }

impl ContextJsonRpcBackend {
    #[must_use]
    pub fn new(context:ApiContext,cursor:ApiCursor,filters:Arc<FilterManager>)->Self{Self{provider:RpcDomainProvider::new(context.clone()),context,cursor,filters}}
    fn query(&self)->WalletQuery{WalletQuery::new(self.context.clone(),self.cursor)}
    fn api<T>(&self,value:Result<T,ApiError>)->Result<T,JsonRpcError>{value.map_err(api_error)}
    fn filter_view(&self)->Result<FilterView,JsonRpcError>{match self.cursor{ApiCursor::Head=>Ok(FilterView::Full),ApiCursor::Solidity=>Ok(FilterView::Solidity),ApiCursor::Pbft=>Err(JsonRpcError::method_not_found())}}
    fn dynamic_number(&self,name:&str)->Result<i64,JsonRpcError>{
        let key=dynamic::key(name).ok_or_else(||JsonRpcError::internal(format!("unknown dynamic property {name}")))?;
        let bytes=self.context.view(self.cursor).store(StoreKind::DynamicProperties).get(key).ok_or_else(||JsonRpcError::internal(format!("missing dynamic property {name}")))?;
        let actual=bytes.len();
        let encoded: [u8;8]=bytes.try_into().map_err(|_|JsonRpcError::internal(format!("invalid dynamic property {name} length {actual}")))?;
        Ok(i64::from_be_bytes(encoded))
    }
    fn head_number(&self)->Result<i64,JsonRpcError>{self.dynamic_number("LATEST_BLOCK_HEADER_NUMBER")}
    fn block_number(&self,value:&Value)->Result<i64,JsonRpcError>{let text=value.as_str().ok_or_else(||JsonRpcError::invalid_params("invalid block number"))?;match parse_block_tag(text)?{BlockTag::Latest=>self.head_number(),BlockTag::Finalized=>self.dynamic_number("LATEST_SOLIDIFIED_BLOCK_NUM"),BlockTag::Earliest=>Ok(0),BlockTag::Number(n)=>i64::try_from(n).map_err(|_|JsonRpcError::invalid_params("invalid block number"))}}
    fn block_by_hash(&self,value:&Value)->Result<Option<Block>,JsonRpcError>{let hash=parse_hash(value.as_str().ok_or_else(||JsonRpcError::invalid_params("invalid hash"))?)?;match self.query().block_by_id(&hash){Ok(v)=>Ok(Some(v)),Err(ApiError::NotFound(_))=>Ok(None),Err(e)=>Err(api_error(e))}}
    fn block_by_number(&self,value:&Value)->Result<Option<Block>,JsonRpcError>{let number=self.block_number(value)?;match self.query().block_by_num(number){Ok(v)=>Ok(Some(v)),Err(ApiError::NotFound(_))=>Ok(None),Err(e)=>Err(api_error(e))}}
    fn selected_block(&self,value:&Value)->Result<Option<Block>,JsonRpcError>{if value.as_str().is_some_and(|v|v.len()==66){self.block_by_hash(value)}else{self.block_by_number(value)}}
    fn require_latest(&self,a:&[Value],index:usize)->Result<(),JsonRpcError>{let tag=string(a,index)?;if tag.eq_ignore_ascii_case("latest"){return Ok(())}match parse_block_tag(tag)?{BlockTag::Number(_)=>Err(JsonRpcError::invalid_params("QUANTITY values are not supported")),_=>Err(JsonRpcError::invalid_params("TAG values other than latest are not supported"))}}
    fn build_transaction(&self,value:&Value)->Result<Value,JsonRpcError>{
        if self.cursor!=ApiCursor::Head{return Err(JsonRpcError::method_not_found())}
        let args:BuildArguments=serde_json::from_value(value.clone()).map_err(|_|JsonRpcError::invalid_request())?;
        let owner=parse_address(&args.from).map_err(|_|JsonRpcError::invalid_request())?.to_vec();
        let data=args.resolved_data()?;
        let kind=match args.contract_type.as_deref(){
            Some("CreateSmartContract")=>ContractType::CreateSmartContract,
            Some("TriggerSmartContract")=>ContractType::TriggerSmartContract,
            Some("TransferContract")|Some("Transfer")=>ContractType::TransferContract,
            Some("TransferAssetContract")|Some("TransferAsset")=>ContractType::TransferAssetContract,
            Some(_)=>return Ok(Value::Null),
            None=>if args.to.is_none(){if data.is_none(){return Err(JsonRpcError::invalid_request())}ContractType::CreateSmartContract}else{let to=parse_address(args.to.as_deref().unwrap())?;if self.provider.contract(&to,self.cursor).is_ok(){ContractType::TriggerSmartContract}else if args.token_id.unwrap_or(0)>0&&args.token_value.unwrap_or(0)>0&&args.value.is_none(){ContractType::TransferAssetContract}else if args.value.is_some(){ContractType::TransferContract}else{return Err(JsonRpcError::invalid_request())}},
        };
        let mutation=WalletMutation::new(self.context.clone());
        let mut extension=match kind{
            ContractType::CreateSmartContract=>{if args.abi.as_ref().is_some_and(|v|!v.is_null()&&v.as_array().is_none_or(Vec::is_empty)){return Err(JsonRpcError::invalid_params("invalid abi"))}let input=CreateSmartContract{owner_address:owner.clone(),new_contract:Some(SmartContract{origin_address:owner,bytecode:data.unwrap_or_default(),call_value:parse_opt_quantity(args.value.as_deref())?,consume_user_resource_percent:args.consume_user_resource_percent.unwrap_or(0),origin_energy_limit:args.origin_energy_limit.unwrap_or(0),name:args.name.clone().unwrap_or_default(),..Default::default()}),call_token_value:args.token_value.unwrap_or(0),token_id:args.token_id.unwrap_or(0)};self.api(self.provider.deploy_contract(input))?},
            ContractType::TriggerSmartContract=>{let input=TriggerSmartContract{owner_address:owner,contract_address:parse_address(args.to.as_deref().ok_or_else(JsonRpcError::invalid_request)?)?.to_vec(),call_value:parse_opt_quantity(args.value.as_deref())?,data:data.unwrap_or_default(),call_token_value:args.token_value.unwrap_or(0),token_id:args.token_id.unwrap_or(0)};self.api(self.provider.trigger_contract(input))?},
            ContractType::TransferContract=>self.api(mutation.create_transaction(&TransferContract{owner_address:owner,to_address:parse_address(args.to.as_deref().ok_or_else(JsonRpcError::invalid_request)?)?.to_vec(),amount:parse_opt_quantity(args.value.as_deref())?}))?,
            ContractType::TransferAssetContract=>self.api(mutation.transfer_asset(&TransferAssetContract{asset_name:args.token_id.unwrap_or(0).to_string().into_bytes(),owner_address:owner,to_address:parse_address(args.to.as_deref().ok_or_else(JsonRpcError::invalid_request)?)?.to_vec(),amount:args.token_value.unwrap_or(0)}))?,
            _=>return Ok(Value::Null),
        };
        let tx=extension.transaction.as_mut().ok_or_else(||JsonRpcError::internal("domain mutation produced no transaction"))?;
        let raw=tx.raw_data.as_mut().ok_or_else(||JsonRpcError::internal("domain mutation produced no raw transaction"))?;
        if matches!(kind,ContractType::CreateSmartContract|ContractType::TriggerSmartContract){raw.fee_limit=args.fee_limit.as_deref().map(parse_quantity).transpose()?.map_or_else(||parse_quantity(&args.gas).unwrap_or(0).saturating_mul(self.energy_fee().max(0) as u64),|v|v) as i64}
        if let Some(id)=args.permission_id{if let Some(contract)=raw.contract.first_mut(){contract.permission_id=id}}
        if let Some(extra)=args.extra_data.as_deref(){raw.data=decode_hex(extra)?}
        Ok(json!({"transaction":built_transaction_json(tx)}))
    }
    fn energy_fee(&self)->i64{self.context.view(self.cursor).store(StoreKind::DynamicProperties).get(b"ENERGY_FEE").and_then(|v|v.as_slice().try_into().ok()).map(i64::from_be_bytes).unwrap_or(100)}
    fn block_receipts(&self,value:&Value)->Result<Value,JsonRpcError>{let Some(block)=self.selected_block(value)? else{return Ok(Value::Null)};let raw=block.block_header.as_ref().and_then(|h|h.raw_data.as_ref());let number=raw.map_or(0,|r|r.number);if number==0{return Ok(Value::Null)}let infos=match self.query().transaction_infos_by_block(number){Ok(v)=>v.transaction_info,Err(ApiError::NotFound(_))=>return Ok(Value::Null),Err(e)=>return Err(api_error(e))};if infos.len()!=block.transactions.len(){return Err(JsonRpcError::internal(format!("TransactionList size mismatch: block has {} transactions, but transactionInfoList has {}",block.transactions.len(),infos.len())))}let hash=block_hash(&block,self.context.crypto_engine());let timestamp=raw.map_or(0,|r|r.timestamp);let mut gas=0u64;let mut logs=0u64;let mut out=Vec::with_capacity(infos.len());for (index,(tx,info)) in block.transactions.iter().zip(&infos).enumerate(){out.push(receipt_json(info,tx,&hash,index,gas,logs,timestamp,self.energy_fee())?);gas=gas.saturating_add(info.receipt.as_ref().map_or(0,|r|r.energy_usage_total.max(0) as u64));logs=logs.saturating_add(info.log.len() as u64)}Ok(Value::Array(out))}
    fn filter_error(error:FilterError)->JsonRpcError{match error{FilterError::NotFound=>JsonRpcError::invalid_params("filter not found"),FilterError::Invalid(v)=>JsonRpcError::invalid_params(v),FilterError::Limit(v)=>JsonRpcError::exceed_limit(v),FilterError::Unavailable=>JsonRpcError::method_not_found()}}
    fn new_log_filter(&self, value: &Value) -> Result<LogFilter, JsonRpcError> {
        let object = value.as_object().ok_or_else(|| JsonRpcError::invalid_params("invalid filter"))?;
        let is_finalized = |name: &str| object.get(name).and_then(Value::as_str).is_some_and(|bound| bound.eq_ignore_ascii_case("finalized"));
        if is_finalized("fromBlock") || is_finalized("toBlock") {
            return Err(JsonRpcError::invalid_params("invalid block range params"));
        }
        self.normalize_log_filter(value)
    }
    pub fn normalize_log_filter(&self, v: &Value) -> Result<LogFilter, JsonRpcError> { let o=v.as_object().ok_or_else(||JsonRpcError::invalid_params("invalid filter"))?;
    let addresses=match o.get("address"){None=>vec![],Some(Value::String(s))=>vec![parse_address(s)?.to_vec()],Some(Value::Array(v))=>v.iter().map(|x|x.as_str().ok_or_else(||JsonRpcError::invalid_params("invalid address")).and_then(|s|parse_address(s).map(|a|a.to_vec()))).collect::<Result<_,_>>()?,_=>return Err(JsonRpcError::invalid_params("invalid address"))};
    let topics=o.get("topics").and_then(Value::as_array).map(|ts|ts.iter().map(|t|match t{Value::Null=>Ok(None),Value::String(s)=>Ok(Some(vec![Hash32::from(parse_hash(s)?)])),Value::Array(a)=>Ok(Some(a.iter().map(|v|v.as_str().ok_or_else(||JsonRpcError::invalid_params("invalid topic")).and_then(|s|parse_hash(s).map(Hash32::from))).collect::<Result<_,_>>()?)),_=>Err(JsonRpcError::invalid_params("invalid topic"))}).collect::<Result<Vec<_>,_>>()).transpose()?.unwrap_or_default();
    let block_hash=o.get("blockHash").map(|v|v.as_str().ok_or_else(||JsonRpcError::invalid_params("invalid hash")).and_then(|s|parse_hash(s).map(Hash32::from))).transpose()?;
    if block_hash.is_some()&&(o.contains_key("fromBlock")||o.contains_key("toBlock")){return Err(JsonRpcError::invalid_params("cannot specify both blockHash and fromBlock/toBlock"))}
    if block_hash.is_some(){return Ok(LogFilter{addresses,topics,block_hash,..Default::default()})}
    let head=u64::try_from(self.head_number()?).map_err(|_|JsonRpcError::internal("negative head checkpoint"))?;
    let bound=|value:&Value|->Result<(u64,bool),JsonRpcError>{let text=value.as_str().ok_or_else(||JsonRpcError::invalid_params("invalid block number"))?;match text.to_ascii_lowercase().as_str(){"latest"|"head"=>Ok((head,true)),"pending"|"safe"=>Err(JsonRpcError::invalid_params(format!("{text} is not supported"))),_=>match parse_block_tag(text)?{BlockTag::Earliest=>Ok((0,false)),BlockTag::Finalized=>Ok((u64::try_from(self.dynamic_number("LATEST_SOLIDIFIED_BLOCK_NUM")?).map_err(|_|JsonRpcError::internal("negative solidity checkpoint"))?,false)),BlockTag::Number(n)=>Ok((n,false)),BlockTag::Latest=>unreachable!()}}};
    let from=o.get("fromBlock").map(&bound).transpose()?;let to=o.get("toBlock").map(&bound).transpose()?;
    let(from_block,to_block)=match(from,to){(None,None)=>(head,u64::MAX),(Some((from,_)),None)=>(from,u64::MAX),(None,Some((_,true)))=>(head,u64::MAX),(None,Some((to,false)))=>(to.min(head),to),(Some((from,_)),Some((_,true)))=>(from,u64::MAX),(Some((from,_)),Some((to,false)))=>{if from>to{return Err(JsonRpcError::invalid_params("please verify: fromBlock <= toBlock"))}(from,to)}};
    Ok(LogFilter{addresses,topics,from_block:Some(from_block),to_block:Some(to_block),block_hash:None}) }
    fn immediate_filter(&self,v:&Value)->Result<LogFilter,JsonRpcError>{let mut filter=self.normalize_log_filter(v)?;if filter.block_hash.is_none(){let head=u64::try_from(self.head_number()?).map_err(|_|JsonRpcError::internal("negative head checkpoint"))?;filter.to_block=Some(filter.to_block.unwrap_or(u64::MAX).min(head));}Ok(filter)}
}

impl JsonRpcBackend for ContextJsonRpcBackend {
 fn execute(&self,method:&str,params:&Value)->Result<Value,JsonRpcError>{let a=params.as_array().ok_or_else(||JsonRpcError::invalid_params("Invalid params"))?;match method{
  "eth_blockNumber"=>Ok(json!(quantity(self.head_number()?.max(0) as u64))),
  "eth_getBlockByHash"=>match self.block_by_hash(req(a,0)?)?{Some(b)=>block_json(&b,a.get(1).and_then(Value::as_bool).unwrap_or(false),self.context.crypto_engine()),None=>Ok(Value::Null)},
  "eth_getBlockByNumber"=>match self.block_by_number(req(a,0)?)?{Some(b)=>block_json(&b,a.get(1).and_then(Value::as_bool).unwrap_or(false),self.context.crypto_engine()),None=>Ok(Value::Null)},
  "eth_getBlockTransactionCountByHash"=>block_count(self.block_by_hash(req(a,0)?)?),"eth_getBlockTransactionCountByNumber"=>block_count(self.block_by_number(req(a,0)?)?),
  "eth_getBalance"=>{self.require_latest(a,1)?;let address=parse_address(string(a,0)?)?;match self.query().account(&address){Ok(v)=>Ok(json!(quantity(v.balance.max(0) as u64))),Err(ApiError::NotFound(_))=>Ok(json!("0x0")),Err(e)=>Err(api_error(e))}},
  "eth_getCode"=>{self.require_latest(a,1)?;let address=parse_address(string(a,0)?)?;Ok(json!(bytes_hex(&self.context.view(self.cursor).store(StoreKind::Code).get(&address).unwrap_or_default())))},
  "eth_getStorageAt"=>{self.require_latest(a,2)?;let address=parse_address(string(a,0)?)?;let slot=parse_hash(string(a,1)?)?;let mut key=address.to_vec();key.extend_from_slice(&slot);Ok(json!(bytes_hex(&self.context.view(self.cursor).store(StoreKind::StorageRow).get(&key).unwrap_or_else(||vec![0;32]))))},
  "eth_getTransactionByHash"=>{let hash=parse_hash(string(a,0)?)?;match self.query().transaction(&hash){Ok(tx)=>transaction_json(&tx,Some(hash),self.context.crypto_engine()),Err(ApiError::NotFound(_))=>Ok(Value::Null),Err(e)=>Err(api_error(e))}},
  "eth_getTransactionReceipt"=>{let hash=parse_hash(string(a,0)?)?;let info=match self.query().transaction_info(&hash){Ok(v)=>v,Err(ApiError::NotFound(_))=>return Ok(Value::Null),Err(e)=>return Err(api_error(e))};let selector=json!(quantity(info.block_number.max(0) as u64));if self.block_by_number(&selector)?.is_none(){return Ok(Value::Null)}let all=self.block_receipts(&selector)?;Ok(all.as_array().and_then(|v|v.iter().find(|r|r["transactionHash"]==bytes_hex(&hash))).cloned().unwrap_or(Value::Null))},
  "eth_getBlockReceipts"=>self.block_receipts(req(a,0)?),
  "eth_getTransactionByBlockHashAndIndex"=>transaction_at(self.block_by_hash(req(a,0)?)?,string(a,1)?,self.context.crypto_engine()),"eth_getTransactionByBlockNumberAndIndex"=>transaction_at(self.block_by_number(req(a,0)?)?,string(a,1)?,self.context.crypto_engine()),
  "eth_call"=>{let call:CallArguments=serde_json::from_value(req(a,0)?.clone()).map_err(|_|JsonRpcError::invalid_params("invalid call object"))?;self.require_latest(a,1)?;let input=trigger(&call)?;let out=self.api(self.provider.trigger_constant(input,self.cursor))?;Ok(json!(bytes_hex(out.constant_result.first().map_or(&[],Vec::as_slice))))},
  "eth_estimateGas"=>{let call:CallArguments=serde_json::from_value(req(a,0)?.clone()).map_err(|_|JsonRpcError::invalid_params("invalid call object"))?;let out=self.provider.estimate_energy(trigger(&call)?,self.cursor);Ok(json!(quantity(out.energy_required.max(0) as u64)))},
  "buildTransaction"=>self.build_transaction(req(a,0)?),
  "eth_newBlockFilter"=>Ok(json!(encode_filter_id(self.filters.new_block_filter(self.filter_view()?).map_err(Self::filter_error)?))),"eth_newPendingTransactionFilter"=>Ok(json!(encode_filter_id(self.filters.new_pending_filter(self.filter_view()?).map_err(Self::filter_error)?))),"eth_newFilter"=>Ok(json!(encode_filter_id(self.filters.new_log_filter_deferred(self.filter_view()?,self.new_log_filter(req(a,0)?)?).map_err(Self::filter_error)?))),"eth_uninstallFilter"=>Ok(json!(self.filters.uninstall(self.filter_view()?,decode_filter_id(string(a,0)?).map_err(Self::filter_error)?).unwrap_or(false))),"eth_getFilterChanges"=>encode_changes(self.filters.changes(self.filter_view()?,decode_filter_id(string(a,0)?).map_err(Self::filter_error)?).map_err(Self::filter_error)?),"eth_getFilterLogs"=>encode_logs(self.filters.filter_logs_at(self.filter_view()?,decode_filter_id(string(a,0)?).map_err(Self::filter_error)?,u64::try_from(self.head_number()?).map_err(|_|JsonRpcError::internal("negative head checkpoint"))?).map_err(Self::filter_error)?),"eth_getLogs"=>encode_logs(self.filters.get_logs(self.filter_view()?,&self.immediate_filter(req(a,0)?)?).map_err(Self::filter_error)?),_=>Err(JsonRpcError::method_not_found())}}
}

fn req(a:&[Value],i:usize)->Result<&Value,JsonRpcError>{a.get(i).ok_or_else(||JsonRpcError::invalid_params("Invalid params"))}
fn string(a:&[Value],i:usize)->Result<&str,JsonRpcError>{req(a,i)?.as_str().ok_or_else(||JsonRpcError::invalid_params("Invalid params"))}
fn api_error(e:ApiError)->JsonRpcError{match e{ApiError::InvalidArgument(v)=>JsonRpcError::invalid_params(v),ApiError::NotFound(_)=>JsonRpcError::invalid_params(e.to_string()),ApiError::FailedPrecondition(v)|ApiError::Unavailable(v)|ApiError::Internal(v)=>JsonRpcError::internal(v)}}
fn parse_opt_quantity(v:Option<&str>)->Result<i64,JsonRpcError>{let n=v.map(parse_quantity).transpose()?.unwrap_or(0);i64::try_from(n).map_err(|_|JsonRpcError::invalid_params("invalid quantity"))}
fn trigger(c:&CallArguments)->Result<TriggerSmartContract,JsonRpcError>{Ok(TriggerSmartContract{owner_address:c.from.as_deref().map(parse_address).transpose()?.map_or_else(Vec::new,|v|v.to_vec()),contract_address:c.to.as_deref().map(parse_address).transpose()?.map_or_else(Vec::new,|v|v.to_vec()),call_value:parse_opt_quantity(c.value.as_deref())?,data:c.data.as_deref().map(decode_hex).transpose()?.unwrap_or_default(),call_token_value:parse_opt_quantity(c.token_value.as_deref())?,token_id:parse_opt_quantity(c.token_id.as_deref())?})}
fn block_count(block:Option<Block>)->Result<Value,JsonRpcError>{Ok(block.map_or(Value::Null,|b|json!(quantity(b.transactions.len() as u64))))}
fn transaction_at(block:Option<Block>,index:&str,engine:tron_crypto::CryptoEngine)->Result<Value,JsonRpcError>{let index=parse_quantity(index)? as usize;match block.and_then(|b|b.transactions.get(index).cloned()){Some(tx)=>transaction_json(&tx,None,engine),None=>Ok(Value::Null)}}
fn transaction_json(tx:&Transaction,id:Option<[u8;32]>,engine:tron_crypto::CryptoEngine)->Result<Value,JsonRpcError>{let hash=id.map(|v|bytes_hex(&v)).unwrap_or_else(||bytes_hex(&tron_crypto::selected_digest(engine,&tx.raw_data.as_ref().map(Message::encode_to_vec).unwrap_or_default())));Ok(json!({"hash":hash,"input":tx.raw_data.as_ref().map(|r|bytes_hex(&r.encode_to_vec())).unwrap_or_else(||"0x".into()),"blockHash":Value::Null,"blockNumber":Value::Null,"transactionIndex":Value::Null}))}
fn block_hash(block:&Block,engine:tron_crypto::CryptoEngine)->String{let raw=block.block_header.as_ref().and_then(|h|h.raw_data.as_ref());let number=raw.map_or(0,|r|r.number);let header=raw.map(Message::encode_to_vec).unwrap_or_default();bytes_hex(tron_primitives::BlockId::new(number,tron_crypto::selected_digest(engine,&header).into()).as_bytes())}
fn block_json(block:&Block,full:bool,engine:tron_crypto::CryptoEngine)->Result<Value,JsonRpcError>{let raw=block.block_header.as_ref().and_then(|h|h.raw_data.as_ref());let transactions=if full{block.transactions.iter().map(|t|transaction_json(t,None,engine)).collect::<Result<Vec<_>,_>>()?}else{block.transactions.iter().map(|t|json!(bytes_hex(&tron_crypto::selected_digest(engine,&t.raw_data.as_ref().map(Message::encode_to_vec).unwrap_or_default())))).collect()};Ok(json!({"number":quantity(raw.map_or(0,|r|r.number.max(0) as u64)),"hash":block_hash(block,engine),"parentHash":raw.map(|r|bytes_hex(&r.parent_hash)).unwrap_or_else(||bytes_hex(&[0;32])),"timestamp":quantity(raw.map_or(0,|r|r.timestamp.max(0) as u64)),"transactions":transactions,"uncles":[]}))}
fn built_transaction_json(tx:&Transaction)->Value{let raw=tx.raw_data.as_ref();let contracts=raw.map_or_else(Vec::new,|r|r.contract.iter().map(|c|json!({"type":ContractType::try_from(c.r#type).map_or_else(|_|c.r#type.to_string(),|v|format!("{v:?}")),"parameter":{"type_url":c.parameter.as_ref().map_or("",|p|p.type_url.as_str()),"value":c.parameter.as_ref().map_or_else(String::new,|p|bytes_hex(&p.value))},"Permission_id":c.permission_id})).collect());json!({"raw_data":{"ref_block_bytes":raw.map_or_else(String::new,|r|bytes_hex(&r.ref_block_bytes)),"ref_block_hash":raw.map_or_else(String::new,|r|bytes_hex(&r.ref_block_hash)),"expiration":raw.map_or(0,|r|r.expiration),"timestamp":raw.map_or(0,|r|r.timestamp),"fee_limit":raw.map_or(0,|r|r.fee_limit),"data":raw.map_or_else(String::new,|r|bytes_hex(&r.data)),"contract":contracts},"signature":tx.signature.iter().map(|v|bytes_hex(v)).collect::<Vec<_>>()})}
fn receipt_json(info:&TransactionInfo,tx:&Transaction,block_hash:&str,index:usize,prior_gas:u64,prior_logs:u64,timestamp:i64,energy_fee:i64)->Result<Value,JsonRpcError>{let resource=info.receipt.as_ref();let gas=resource.map_or(0,|r|r.energy_usage_total.max(0) as u64);let result=resource.map_or(0,|r|r.result);let contract=tx.raw_data.as_ref().and_then(|r|r.contract.first());let (from,to,is_create)=contract.map(contract_addresses).transpose()?.unwrap_or((Value::Null,Value::Null,false));let logs=info.log.iter().enumerate().map(|(i,l)|json!({"logIndex":quantity(prior_logs+i as u64),"blockHash":block_hash,"blockNumber":quantity(info.block_number.max(0) as u64),"transactionIndex":quantity(index as u64),"transactionHash":bytes_hex(&info.id),"address":log_address_hex(&l.address),"data":bytes_hex(&l.data),"topics":l.topics.iter().map(|v|bytes_hex(v)).collect::<Vec<_>>(),"removed":false,"blockTimestamp":quantity(timestamp.max(0) as u64/1000)})).collect::<Vec<_>>();Ok(json!({"blockHash":block_hash,"blockNumber":quantity(info.block_number.max(0) as u64),"transactionIndex":quantity(index as u64),"transactionHash":bytes_hex(&info.id),"from":from,"to":to,"cumulativeGasUsed":quantity(prior_gas.saturating_add(gas)),"effectiveGasPrice":quantity(energy_fee.max(0) as u64),"gasUsed":quantity(gas),"contractAddress":if is_create&&!info.contract_address.is_empty(){json!(address_hex(&info.contract_address)?)}else{Value::Null},"logs":logs,"logsBloom":bytes_hex(&[0;256]),"status":if result<=1{"0x1"}else{"0x0"},"type":"0x0","revertReason":if result==2&&!info.res_message.is_empty(){json!(bytes_hex(&info.res_message))}else{Value::Null}}))}
fn log_address_hex(address:&[u8])->String{if address.len()==20{let mut tron=[0u8;21];tron[0]=0x41;tron[1..].copy_from_slice(address);address_hex(&tron).unwrap_or_else(|_|bytes_hex(address))}else{address_hex(address).unwrap_or_else(|_|bytes_hex(address))}}
fn contract_addresses(c:&tron_protocol::protocol::transaction::Contract)->Result<(Value,Value,bool),JsonRpcError>{let Some(Any{value,..})=&c.parameter else{return Ok((Value::Null,Value::Null,false))};match ContractType::try_from(c.r#type).ok(){Some(ContractType::TransferContract)=>{let v=TransferContract::decode(value.as_slice()).map_err(|e|JsonRpcError::internal(e.to_string()))?;Ok((json!(address_hex(&v.owner_address)?),json!(address_hex(&v.to_address)?),false))},Some(ContractType::TransferAssetContract)=>{let v=TransferAssetContract::decode(value.as_slice()).map_err(|e|JsonRpcError::internal(e.to_string()))?;Ok((json!(address_hex(&v.owner_address)?),json!(address_hex(&v.to_address)?),false))},Some(ContractType::TriggerSmartContract)=>{let v=TriggerSmartContract::decode(value.as_slice()).map_err(|e|JsonRpcError::internal(e.to_string()))?;Ok((json!(address_hex(&v.owner_address)?),json!(address_hex(&v.contract_address)?),false))},Some(ContractType::CreateSmartContract)=>{let v=CreateSmartContract::decode(value.as_slice()).map_err(|e|JsonRpcError::internal(e.to_string()))?;Ok((json!(address_hex(&v.owner_address)?),Value::Null,true))},_=>Ok((Value::Null,Value::Null,false))}}

fn encode_log(l:RpcLog)->Value{json!({"address":address_hex(&l.address).unwrap_or_else(|_|bytes_hex(&l.address)),"topics":l.topics.iter().map(|v|bytes_hex(v.as_bytes())).collect::<Vec<_>>(),"data":bytes_hex(&l.data),"blockHash":bytes_hex(l.block_hash.as_bytes()),"blockNumber":quantity(l.block_number),"transactionHash":bytes_hex(l.transaction_hash.as_bytes()),"transactionIndex":quantity(l.transaction_index),"logIndex":quantity(l.log_index),"removed":l.removed})}
fn encode_logs(v:Vec<RpcLog>)->Result<Value,JsonRpcError>{Ok(Value::Array(v.into_iter().map(encode_log).collect()))}
fn encode_changes(v:FilterChanges)->Result<Value,JsonRpcError>{match v{FilterChanges::Hashes(h)=>Ok(Value::Array(h.into_iter().map(|v|json!(bytes_hex(v.as_bytes()))).collect())),FilterChanges::Logs(l)=>encode_logs(l)}}
