package org.tron.tools.c012;
import java.lang.instrument.ClassFileTransformer;import java.security.*;import java.util.*;import net.bytebuddy.jar.asm.*;import static net.bytebuddy.jar.asm.Opcodes.*;
public final class C012Transformer implements ClassFileTransformer{
 private static final String CAP="org/tron/tools/c012/C012Capture";private final String tc,tm;public C012Transformer(String c,String m){tc=c.replace('.','/');tm=m;}
 public byte[] transform(final ClassLoader loader,String name,Class<?>r,ProtectionDomain p,byte[]in){if(name==null||!target(name))return null;try{final List<String>chg=new ArrayList<String>();ClassReader cr=new ClassReader(in);ClassWriter cw=new ClassWriter(cr,ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS){protected String getCommonSuperClass(String a,String b){try{Class<?>x=Class.forName(a.replace('/','.'),false,loader),y=Class.forName(b.replace('/','.'),false,loader);if(x.isAssignableFrom(y))return a;if(y.isAssignableFrom(x))return b;if(x.isInterface()||y.isInterface())return"java/lang/Object";do{x=x.getSuperclass();}while(x!=null&&!x.isAssignableFrom(y));return x==null?"java/lang/Object":x.getName().replace('.','/');}catch(Throwable t){return"java/lang/Object";}}};
 cr.accept(new ClassVisitor(ASM9,cw){String o;public void visit(int v,int a,String n,String s,String u,String[]i){o=n;super.visit(v,a,n,s,u,i);}public MethodVisitor visitMethod(int a,String n,String d,String s,String[]e){MethodVisitor mv=super.visitMethod(a,n,d,s,e);
  if(o.equals(tc)&&n.equals(tm)&&d.equals("()V")){chg.add(n+d);return test(mv);}
  if(o.equals("org/tron/core/actuator/AbstractActuator")&&n.equals("<init>")&&d.startsWith("(Lorg/tron/protos/Protocol$Transaction$Contract$ContractType;Ljava/lang/Class;)")){chg.add(n+d);return ctor(mv);}
  if(o.startsWith("org/tron/core/actuator/")&&!o.endsWith("AbstractActuator")&&!o.endsWith("VMActuator")&&((n.equals("validate")&&d.equals("()Z"))||(n.equals("execute")&&d.equals("(Ljava/lang/Object;)Z")))&&(a&ACC_ABSTRACT)==0){chg.add(n+d);return invocation(mv,n);}
  if(o.equals("org/tron/core/db2/core/Chainbase")){if(n.equals("put")&&d.equals("([B[B)V")){chg.add(n+d);return write(mv,false);}if(n.equals("delete")&&d.equals("([B)V")){chg.add(n+d);return write(mv,true);}if((n.equals("getUnchecked")||n.equals("getFromRoot"))&&d.equals("([B)[B")){chg.add(n+d);return read(mv);}}
  if(o.endsWith("/LevelDbDataSourceImpl")||o.endsWith("/RocksDbDataSourceImpl")){if(n.equals("putData")&&d.equals("([B[B)V")){chg.add(n+d);return write(mv,false);}if(n.equals("deleteData")&&d.equals("([B)V")){chg.add(n+d);return write(mv,true);}if(n.equals("getData")&&d.equals("([B)[B")){chg.add(n+d);return read(mv);}}
  if(o.equals("org/tron/core/db/Manager")&&n.equals("init")&&d.equals("()V")){chg.add(n+d);return manager(mv);}return mv;}},ClassReader.EXPAND_FRAMES);if(chg.isEmpty())return null;byte[]out=cw.toByteArray();C012Capture.audit(name,sha(in),join(chg),loader!=null);return out;}catch(Throwable t){C012Capture.captureFailure(t);return null;}}
 private boolean target(String n){return n.equals(tc)||n.equals("org/tron/core/actuator/AbstractActuator")||n.startsWith("org/tron/core/actuator/")||n.equals("org/tron/core/db2/core/Chainbase")||n.endsWith("/LevelDbDataSourceImpl")||n.endsWith("/RocksDbDataSourceImpl")||n.equals("org/tron/core/db/Manager");}
 private static MethodVisitor test(MethodVisitor mv){return new MethodVisitor(ASM9,mv){Label start=new Label(),end=new Label();public void visitCode(){super.visitCode();super.visitMethodInsn(INVOKESTATIC,CAP,"enterTestBody","()V",false);super.visitLabel(start);}public void visitInsn(int op){if(op>=IRETURN&&op<=RETURN){super.visitInsn(ACONST_NULL);super.visitMethodInsn(INVOKESTATIC,CAP,"exitTestBody","(Ljava/lang/Throwable;)V",false);}super.visitInsn(op);}public void visitMaxs(int a,int b){super.visitLabel(end);Label h=new Label();super.visitTryCatchBlock(start,end,h,"java/lang/Throwable");super.visitLabel(h);super.visitVarInsn(ASTORE,100);super.visitVarInsn(ALOAD,100);super.visitMethodInsn(INVOKESTATIC,CAP,"exitTestBody","(Ljava/lang/Throwable;)V",false);super.visitVarInsn(ALOAD,100);super.visitInsn(ATHROW);super.visitMaxs(a,b);}};}
 private static MethodVisitor ctor(MethodVisitor mv){return new MethodVisitor(ASM9,mv){boolean hooked;public void visitMethodInsn(int op,String owner,String n,String d,boolean itf){super.visitMethodInsn(op,owner,n,d,itf);if(!hooked&&op==INVOKESPECIAL&&n.equals("<init>")){hooked=true;super.visitVarInsn(ALOAD,0);super.visitVarInsn(ALOAD,1);super.visitVarInsn(ALOAD,2);super.visitMethodInsn(INVOKESTATIC,CAP,"actuatorConstructed","(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Class;)V",false);}}};}
 private static MethodVisitor manager(MethodVisitor mv){return new MethodVisitor(ASM9,mv){public void visitInsn(int op){if(op==RETURN){super.visitVarInsn(ALOAD,0);super.visitMethodInsn(INVOKESTATIC,CAP,"managerInitialized","(Ljava/lang/Object;)V",false);}super.visitInsn(op);}};}
 private static MethodVisitor invocation(MethodVisitor mv,final String phase){return new MethodVisitor(ASM9,mv){Label start=new Label(),end=new Label();public void visitCode(){super.visitCode();super.visitVarInsn(ALOAD,0);super.visitLdcInsn(phase);if(phase.equals("execute"))super.visitVarInsn(ALOAD,1);else super.visitInsn(ACONST_NULL);super.visitMethodInsn(INVOKESTATIC,CAP,"enterInvocation","(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)J",false);super.visitVarInsn(LSTORE,90);super.visitLabel(start);}public void visitInsn(int op){if(op==IRETURN){super.visitVarInsn(ISTORE,89);super.visitVarInsn(LLOAD,90);super.visitVarInsn(ILOAD,89);super.visitMethodInsn(INVOKESTATIC,CAP,"exitInvocationSuccess","(JZ)V",false);super.visitVarInsn(ILOAD,89);}super.visitInsn(op);}public void visitMaxs(int a,int b){super.visitLabel(end);Label h=new Label();super.visitTryCatchBlock(start,end,h,"java/lang/Throwable");super.visitLabel(h);super.visitVarInsn(ASTORE,100);super.visitVarInsn(LLOAD,90);super.visitVarInsn(ALOAD,100);super.visitMethodInsn(INVOKESTATIC,CAP,"exitInvocationFailure","(JLjava/lang/Throwable;)V",false);super.visitVarInsn(ALOAD,100);super.visitInsn(ATHROW);super.visitMaxs(a,b);}};}
 private static MethodVisitor write(MethodVisitor mv,final boolean del){return new MethodVisitor(ASM9,mv){public void visitCode(){super.visitCode();super.visitVarInsn(ALOAD,0);super.visitVarInsn(ALOAD,1);if(del)super.visitInsn(ACONST_NULL);else super.visitVarInsn(ALOAD,2);super.visitInsn(del?ICONST_1:ICONST_0);super.visitMethodInsn(INVOKESTATIC,CAP,"storeWriteEnter","(Ljava/lang/Object;[B[BZ)Ljava/lang/Object;",false);super.visitVarInsn(ASTORE,90);}public void visitInsn(int op){if(op==RETURN){super.visitVarInsn(ALOAD,90);super.visitMethodInsn(INVOKESTATIC,CAP,"storeWriteExit","(Ljava/lang/Object;)V",false);}super.visitInsn(op);}};}
 private static MethodVisitor read(MethodVisitor mv){return new MethodVisitor(ASM9,mv){public void visitInsn(int op){if(op==ARETURN){super.visitInsn(DUP);super.visitVarInsn(ASTORE,90);super.visitVarInsn(ALOAD,0);super.visitVarInsn(ALOAD,1);super.visitVarInsn(ALOAD,90);super.visitMethodInsn(INVOKESTATIC,CAP,"storeRead","(Ljava/lang/Object;[B[B)V",false);}super.visitInsn(op);}};}
 private static String sha(byte[]b)throws Exception{byte[]h=MessageDigest.getInstance("SHA-256").digest(b);StringBuilder s=new StringBuilder();for(byte x:h)s.append(String.format("%02x",x&255));return s.toString();}private static String join(List<String>x){StringBuilder b=new StringBuilder();for(String s:x){if(b.length()>0)b.append(',');b.append(s);}return b.toString();}
}
