//! C014.03A arithmetic, comparison, environment, and block opcode rows.
use crate::{EnergyMeter,Memory,OperationContext,OperationControl,OperationSpec,OperationVariant,TvmRules,VmFault,Word,MEMORY_LIMIT};
use core::cmp::Ordering;
use prost::Message;
use tron_protocol::protocol::Block;
use tron_state::StoreKind;

const fn yes(_: &TvmRules)->bool{true} const fn constantinople(r:&TvmRules)->bool{r.constantinople} const fn istanbul(r:&TvmRules)->bool{r.istanbul} const fn london(r:&TvmRules)->bool{r.london} const fn blob(r:&TvmRules)->bool{r.blob} const fn osaka(r:&TvmRules)->bool{r.osaka}
fn e2(_: &OperationContext<'_,'_>)->Result<i64,VmFault>{Ok(2)} fn e3(_: &OperationContext<'_,'_>)->Result<i64,VmFault>{Ok(3)} fn e5(_: &OperationContext<'_,'_>)->Result<i64,VmFault>{Ok(5)} fn e8(_: &OperationContext<'_,'_>)->Result<i64,VmFault>{Ok(8)} fn e20(_: &OperationContext<'_,'_>)->Result<i64,VmFault>{Ok(20)} fn e400(_: &OperationContext<'_,'_>)->Result<i64,VmFault>{Ok(400)}
fn exp_energy(c:&OperationContext<'_,'_>)->Result<i64,VmFault>{Ok(10+10*i64::try_from(c.stack.peek(1)?.bytes_occupied()).map_err(|_|VmFault::Arithmetic)?)}
fn mem_energy(c:&OperationContext<'_,'_>,off:Word,size:Word,base:i64,per_word:i64)->Result<i64,VmFault>{let o=usize::try_from(off.to_i32_safe()).map_err(|_|VmFault::OutOfMemory)?;let n=usize::try_from(size.to_i32_safe()).map_err(|_|VmFault::OutOfMemory)?;let end=if n==0{c.memory.soft_len()}else{o.checked_add(n).filter(|end|*end<=MEMORY_LIMIT).ok_or(VmFault::OutOfMemory)?};let delta=EnergyMeter::memory_delta(c.memory.soft_len(),end)?;let words=i64::try_from(n.checked_add(31).ok_or(VmFault::OutOfMemory)?/32).map_err(|_|VmFault::OutOfEnergy)?;base.checked_add(delta).and_then(|v|v.checked_add(words.checked_mul(per_word)?)).ok_or(VmFault::OutOfEnergy)}
fn sha3_energy(c:&OperationContext<'_,'_>)->Result<i64,VmFault>{mem_energy(c,c.stack.peek(0)?,c.stack.peek(1)?,30,6)}
fn copy_energy(c:&OperationContext<'_,'_>)->Result<i64,VmFault>{mem_energy(c,c.stack.peek(0)?,c.stack.peek(2)?,0,3)}
fn extcopy_energy(c:&OperationContext<'_,'_>)->Result<i64,VmFault>{mem_energy(c,c.stack.peek(1)?,c.stack.peek(3)?,20,3)}
fn retcopy_energy(c:&OperationContext<'_,'_>)->Result<i64,VmFault>{copy_energy(c)}
fn cont()->Result<OperationControl,VmFault>{Ok(OperationControl::Continue)}
fn boolw(v:bool)->Word{if v{Word::ONE}else{Word::ZERO}}
fn binary(c:&mut OperationContext<'_,'_>,f:fn(Word,Word)->Word)->Result<OperationControl,VmFault>{let a=c.stack.pop()?;let b=c.stack.pop()?;c.stack.push(f(a,b))?;cont()}
fn add(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|a+b)} fn mul(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|a*b)} fn sub(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|a-b)} fn div(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,Word::unsigned_div)} fn sdiv(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,Word::signed_div)} fn modu(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,Word::unsigned_rem)} fn smod(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,Word::signed_rem)}
fn modular(mut a:Word,mut b:Word,m:Word,multiply:bool)->Word{if m.is_zero(){return Word::ZERO}a=a%m;b=b%m;let mut out=Word::ZERO;if !multiply{return add_mod(a,b,m)}while !b.is_zero(){if b.bit(0){out=add_mod(out,a,m);}a=add_mod(a,a,m);b=b.shr(Word::ONE);}out}
fn add_mod(a:Word,b:Word,m:Word)->Word{let gap=m-b;if a>=gap{a-gap}else{a+b}}
fn addmod(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=c.stack.pop()?;let b=c.stack.pop()?;let m=c.stack.pop()?;c.stack.push(modular(a,b,m,false))?;cont()} fn mulmod(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=c.stack.pop()?;let b=c.stack.pop()?;let m=c.stack.pop()?;c.stack.push(modular(a,b,m,true))?;cont()}
fn exp(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let mut a=c.stack.pop()?;let mut p=c.stack.pop()?;let mut out=Word::ONE;while !p.is_zero(){if p.bit(0){out=out*a;}a=a*a;p=p.shr(Word::ONE);}c.stack.push(out)?;cont()} fn signextend(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let k=c.stack.pop()?;let v=c.stack.pop()?;c.stack.push(v.sign_extend(k))?;cont()}
fn lt(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|boolw(a<b))} fn gt(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|boolw(a>b))} fn slt(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|boolw(a.signed_cmp(b)==Ordering::Less))} fn sgt(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|boolw(a.signed_cmp(b)==Ordering::Greater))} fn eq(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|boolw(a==b))} fn iszero(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=c.stack.pop()?;c.stack.push(boolw(a.is_zero()))?;cont()} fn and(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|a&b)} fn or(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|a|b)} fn xor(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{binary(c,|a,b|a^b)} fn not(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=c.stack.pop()?;c.stack.push(!a)?;cont()}
fn byte(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let i=c.stack.pop()?;let v=c.stack.pop()?;let out=if i<Word::from(32u8){Word::from(v.to_be_bytes()[i.low_u32() as usize])}else{Word::ZERO};c.stack.push(out)?;cont()} fn shl(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let s=c.stack.pop()?;let v=c.stack.pop()?;c.stack.push(v.shl(s))?;cont()} fn shr(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let s=c.stack.pop()?;let v=c.stack.pop()?;c.stack.push(v.shr(s))?;cont()} fn sar(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let s=c.stack.pop()?;let v=c.stack.pop()?;c.stack.push(v.sar(s))?;cont()} fn clz(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let v=c.stack.pop()?;c.stack.push(Word::from_u64(u64::from(v.leading_zeros())))?;cont()}
fn sha3(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let o=c.stack.pop()?.to_i32_safe() as usize;let n=c.stack.pop()?.to_i32_safe() as usize;let data=c.memory.read(o,n)?;c.stack.push(Word::from_be_bytes(tron_crypto::keccak256(&data)))?;cont()}
fn addr_word(bytes:&[u8],last20:bool)->Word{let bytes=if last20&&bytes.len()>20{&bytes[bytes.len()-20..]}else{bytes};let mut out=[0u8;32];let n=bytes.len().min(32);out[32-n..].copy_from_slice(&bytes[bytes.len()-n..]);Word::from_be_bytes(out)}
fn address(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(addr_word(c.frame.context_address.as_bytes(),c.rules.multi_sign))?;cont()} fn origin(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(addr_word(c.frame.origin.as_bytes(),c.rules.multi_sign))?;cont()} fn caller(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(addr_word(c.frame.caller.as_bytes(),true))?;cont()} fn callvalue(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(c.frame.call_value)?;cont()}
fn balance(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=c.stack.pop()?.to_tron_address();let v=c.repository.balance(&a).map_err(|_|VmFault::Other)?;c.stack.push(Word::from_u64(v.max(0) as u64))?;cont()}
fn calldataload(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let o=c.stack.pop()?.to_i32_safe() as usize;let mut b=[0u8;32];if o<c.frame.input.len(){let n=32.min(c.frame.input.len()-o);b[..n].copy_from_slice(&c.frame.input[o..o+n]);}c.stack.push(Word::from_be_bytes(b))?;cont()} fn calldatasize(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(Word::from_u64(c.frame.input.len() as u64))?;cont()}
fn copy_to_memory(memory:&mut Memory,destination:Word,source_offset:Word,size:Word,source:&[u8])->Result<(),VmFault>{let destination=usize::try_from(destination.to_i32_safe()).map_err(|_|VmFault::OutOfMemory)?;let source_offset=usize::try_from(source_offset.to_i32_safe()).map_err(|_|VmFault::OutOfMemory)?;let size=usize::try_from(size.to_i32_safe()).map_err(|_|VmFault::OutOfMemory)?;memory.write_padded(destination,size,source,source_offset)}
fn calldatacopy(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let m=c.stack.pop()?;let o=c.stack.pop()?;let n=c.stack.pop()?;copy_to_memory(c.memory,m,o,n,&c.frame.input)?;cont()} fn codesize(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(Word::from_u64(c.program.code().len() as u64))?;cont()} fn codecopy(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let m=c.stack.pop()?;let o=c.stack.pop()?;let n=c.stack.pop()?;copy_to_memory(c.memory,m,o,n,c.program.code())?;cont()} fn returndatasize(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(Word::from_u64(c.effects.return_data.len() as u64))?;cont()} fn returndatacopy(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let m=c.stack.pop()?.to_i32_safe() as usize;let o=c.stack.pop()?.to_i32_safe() as usize;let n=c.stack.pop()?.to_i32_safe() as usize;let end=o.checked_add(n).ok_or(VmFault::ReturnDataBounds)?;if end>c.effects.return_data.len(){return Err(VmFault::ReturnDataBounds)}c.memory.write(m,&c.effects.return_data[o..end])?;cont()}
fn dynamic(c:&OperationContext<'_,'_>,key:&str)->Word{Word::from_u64(c.repository.dynamic_i64(key).ok().flatten().unwrap_or(0).max(0) as u64)} fn gasprice(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let v=if c.rules.compatible_evm&&c.frame.contract_version==1{dynamic(c,"ENERGY_FEE")}else{Word::ZERO};c.stack.push(v)?;cont()}
fn extcodesize(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=c.stack.pop()?.to_tron_address();c.stack.push(Word::from_u64(c.repository.code(&a).map_or(0,|v|v.len()) as u64))?;cont()} fn extcodecopy(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=c.stack.pop()?.to_tron_address();let m=c.stack.pop()?;let o=c.stack.pop()?;let n=c.stack.pop()?;let code=c.repository.code(&a).unwrap_or_default();copy_to_memory(c.memory,m,o,n,&code)?;cont()} fn extcodehash(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=c.stack.pop()?.to_tron_address();let v=match c.repository.account(&a).map_err(|_|VmFault::Other)?{None=>Word::ZERO,Some(_)=>Word::from_be_bytes(tron_crypto::keccak256(&c.repository.code(&a).unwrap_or_default()))};c.stack.push(v)?;cont()}
fn block_id(c:&OperationContext<'_,'_>,n:i64)->Option<Vec<u8>>{c.repository.get_raw(StoreKind::BlockIndex,&n.to_be_bytes())} fn block(c:&OperationContext<'_,'_>,n:i64)->Option<Block>{let id=block_id(c,n)?;Block::decode(c.repository.get_raw(StoreKind::Block,&id)?.as_slice()).ok()} fn blockhash(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let n=i64::from(c.stack.pop()?.to_i32_safe());let cur=c.rules.latest_block_number;let lower=if c.rules.disable_java_math{cur.max(256)-256}else{cur.saturating_sub(256)};let v=if n<cur&&n>=lower{block_id(c,n).and_then(|v|<[u8;32]>::try_from(v).ok()).map(Word::from_be_bytes).unwrap_or(Word::ZERO)}else{Word::ZERO};c.stack.push(v)?;cont()} fn coinbase(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let bytes=block(c,c.rules.latest_block_number).and_then(|b|b.block_header?.raw_data).map(|r|r.witness_address).unwrap_or_default();c.stack.push(addr_word(&bytes,false))?;cont()} fn timestamp(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let ms=c.repository.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP").ok().flatten().unwrap_or(0);c.stack.push(Word::from_u64((ms/1000).max(0) as u64))?;cont()} fn number(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(Word::from_u64(c.rules.latest_block_number.max(0) as u64))?;cont()} fn zero(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.push(Word::ZERO)?;cont()} fn chainid(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let id=block_id(c,0).unwrap_or_default();let bytes=if c.rules.compatible_evm||c.rules.optimized_chain_id{&id[id.len().saturating_sub(4)..]}else{&id};c.stack.push(addr_word(bytes,false))?;cont()} fn selfbalance(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let v=c.repository.balance(&c.frame.context_address).map_err(|_|VmFault::Other)?;c.stack.push(Word::from_u64(v.max(0) as u64))?;cont()} fn basefee(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let v=dynamic(c,"ENERGY_FEE");c.stack.push(v)?;cont()}
fn blobhash(c:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{c.stack.pop()?;c.stack.push(Word::ZERO)?;cont()}

macro_rules! v{($e:ident,$x:ident)=>{&[OperationVariant{when:yes,energy:$e,execute:$x}]};} macro_rules! s{($o:expr,$r:expr,$w:expr,$a:ident,$e:ident,$x:ident)=>{OperationSpec{opcode:$o,required_before:$r,resulting_window:$w,activation:$a,variants:v!($e,$x)}};}
static SPECS:[OperationSpec;54]=[
s!(0x01,2,1,yes,e3,add),s!(0x02,2,1,yes,e5,mul),s!(0x03,2,1,yes,e3,sub),s!(0x04,2,1,yes,e5,div),s!(0x05,2,1,yes,e5,sdiv),s!(0x06,2,1,yes,e5,modu),s!(0x07,2,1,yes,e5,smod),s!(0x08,3,1,yes,e8,addmod),s!(0x09,3,1,yes,e8,mulmod),s!(0x0a,2,1,yes,exp_energy,exp),s!(0x0b,2,1,yes,e5,signextend),
s!(0x10,2,1,yes,e3,lt),s!(0x11,2,1,yes,e3,gt),s!(0x12,2,1,yes,e3,slt),s!(0x13,2,1,yes,e3,sgt),s!(0x14,2,1,yes,e3,eq),s!(0x15,1,1,yes,e3,iszero),s!(0x16,2,1,yes,e3,and),s!(0x17,2,1,yes,e3,or),s!(0x18,2,1,yes,e3,xor),s!(0x19,1,1,yes,e3,not),s!(0x1a,2,1,yes,e3,byte),s!(0x1b,2,1,constantinople,e3,shl),s!(0x1c,2,1,constantinople,e3,shr),s!(0x1d,2,1,constantinople,e3,sar),s!(0x1e,1,1,osaka,e5,clz),s!(0x20,2,1,yes,sha3_energy,sha3),
s!(0x30,0,1,yes,e2,address),s!(0x31,1,1,yes,e20,balance),s!(0x32,0,1,yes,e2,origin),s!(0x33,0,1,yes,e2,caller),s!(0x34,0,1,yes,e2,callvalue),s!(0x35,1,1,yes,e3,calldataload),s!(0x36,0,1,yes,e2,calldatasize),s!(0x37,3,0,yes,copy_energy,calldatacopy),s!(0x38,0,1,yes,e2,codesize),s!(0x39,3,0,yes,copy_energy,codecopy),s!(0x3a,0,1,yes,e2,gasprice),s!(0x3b,1,1,yes,e20,extcodesize),s!(0x3c,4,0,yes,extcopy_energy,extcodecopy),s!(0x3d,0,1,yes,e2,returndatasize),s!(0x3e,3,0,yes,retcopy_energy,returndatacopy),s!(0x3f,1,1,constantinople,e400,extcodehash),
s!(0x40,1,1,yes,e20,blockhash),s!(0x41,0,1,yes,e2,coinbase),s!(0x42,0,1,yes,e2,timestamp),s!(0x43,0,1,yes,e2,number),s!(0x44,0,1,yes,e2,zero),s!(0x45,0,1,yes,e2,zero),s!(0x46,0,1,istanbul,e2,chainid),s!(0x47,0,1,istanbul,e5,selfbalance),s!(0x48,0,1,london,e2,basefee),s!(0x49,1,1,blob,e3,blobhash),s!(0x4a,0,1,blob,e2,zero)];
/// Returns this family's immutable registry rows in numeric opcode order.
#[must_use] pub const fn operation_specs()->&'static[OperationSpec]{&SPECS}
