//! C014.03C call, create, system, and TRON-specific opcode rows.
use crate::{CallRequest,CreateKind,CreateRequest,ChildId,ChildStorageMode,ContractResult,EnergyMeter,ExecutionOutcome,FrameContext,InternalTransactionRecord,OperationContext,OperationControl,OperationSpec,OperationVariant,TvmRules,VmFault,Word,MEMORY_LIMIT};
use tron_crypto::{create2_address,internal_create_address};
use tron_protocol::protocol::Vote;
use tron_primitives::{Hash32,TronAddress21};

const CALL_BASE:i64=40; const VALUE_TRANSFER:i64=9_000; const NEW_ACCOUNT:i64=25_000; const STIPEND:i64=2_300;
fn always(_: &TvmRules)->bool{true} fn transfer(r:&TvmRules)->bool{r.transfer_trc10} fn constantinople(r:&TvmRules)->bool{r.constantinople} fn solidity059(r:&TvmRules)->bool{r.solidity_059} fn freeze(r:&TvmRules)->bool{r.freeze} fn vote(r:&TvmRules)->bool{r.vote} fn freeze_v2(r:&TvmRules)->bool{r.freeze_v2}
fn ordinary(_: &TvmRules)->bool{true} fn fair_energy(r:&TvmRules)->bool{r.energy_adjustment&&!r.selfdestruct_restriction} fn restricted(r:&TvmRules)->bool{r.selfdestruct_restriction}
fn fixed<const N:i64>(_:&OperationContext<'_,'_>)->Result<i64,VmFault>{Ok(N)}
fn range_end(offset:Word,size:Word)->Result<usize,VmFault>{
 let size=word_usize(size)?;if size==0{return Ok(0)}
 let offset=word_usize(offset)?;offset.checked_add(size).filter(|end|*end<=MEMORY_LIMIT).ok_or(VmFault::OutOfMemory)
}
fn word_usize(value:Word)->Result<usize,VmFault>{if value>Word::from(i64::MAX as u64){return Err(VmFault::OutOfMemory)}usize::try_from(value.to_i64_safe()).map_err(|_|VmFault::OutOfMemory)}
fn memory_delta(ctx:&OperationContext<'_,'_>,end:usize)->Result<i64,VmFault>{if end==0||end<=ctx.memory.soft_len(){Ok(0)}else{EnergyMeter::memory_delta(ctx.memory.soft_len(),end)}}
fn checked_sum(values:&[i64])->Result<i64,VmFault>{values.iter().try_fold(0i64,|sum,value|sum.checked_add(*value).ok_or(VmFault::OutOfEnergy))}
fn word32(bytes:Vec<u8>)->Result<Word,VmFault>{let array:[u8;32]=bytes.try_into().map_err(|_|VmFault::Other)?;Ok(Word::from_be_bytes(array))}
fn call_energy(ctx:&OperationContext<'_,'_>,with_value:bool,new_account:bool,token:bool)->Result<i64,VmFault>{let address=ctx.stack.peek(1)?;let value=if with_value{ctx.stack.peek(2)?}else{Word::ZERO};let in_off_i=if token{4}else if with_value{3}else{2};let in_size_i=in_off_i+1;let out_off_i=in_off_i+2;let out_size_i=in_off_i+3;let end=range_end(ctx.stack.peek(in_off_i)?,ctx.stack.peek(in_size_i)?)?.max(range_end(ctx.stack.peek(out_off_i)?,ctx.stack.peek(out_size_i)?)?);let mut base=checked_sum(&[CALL_BASE,memory_delta(ctx,end)?])?;if !value.is_zero(){base=base.checked_add(VALUE_TRANSFER).ok_or(VmFault::OutOfEnergy)?;if new_account&&ctx.repository.account(&address.to_tron_address()).map_err(|_|VmFault::Other)?.is_none(){base=base.checked_add(NEW_ACCOUNT).ok_or(VmFault::OutOfEnergy)?;}}Ok(base)}
fn call_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{call_energy(ctx,true,true,false)} fn callcode_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{call_energy(ctx,true,false,false)} fn delegate_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{call_energy(ctx,false,false,false)} fn calltoken_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{call_energy(ctx,true,true,true)}
fn create_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{let end=range_end(ctx.stack.peek(1)?,ctx.stack.peek(2)?)?;checked_sum(&[32_000,memory_delta(ctx,end)?])} fn create2_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{let size=word_usize(ctx.stack.peek(2)?)?;let words=i64::try_from(size.checked_add(31).ok_or(VmFault::OutOfMemory)?/32).map_err(|_|VmFault::OutOfEnergy)?;checked_sum(&[create_e(ctx)?,words.checked_mul(6).ok_or(VmFault::OutOfEnergy)?])}
fn freeze_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{let receiver=ctx.stack.peek(2)?.to_tron_address();Ok(20_000+if ctx.repository.account(&receiver).map_err(|_|VmFault::Other)?.is_none(){NEW_ACCOUNT}else{0})}
fn vote_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{let extra=if ctx.rules.energy_adjustment{32}else{0};let a=range_end(ctx.stack.peek(1)?,ctx.stack.peek(0)?.wrapping_add(Word::from(extra as u64)).wrapping_mul(Word::from(32u64)))?;let w=range_end(ctx.stack.peek(3)?,ctx.stack.peek(2)?.wrapping_add(Word::from(extra as u64)).wrapping_mul(Word::from(32u64)))?;checked_sum(&[30_000,memory_delta(ctx,a.max(w))?])}
fn suicide_e(ctx:&OperationContext<'_,'_>)->Result<i64,VmFault>{let base=if ctx.rules.selfdestruct_restriction{5_000}else{0};let target=ctx.stack.peek(0)?.to_tron_address();Ok(base+if ctx.repository.account(&target).map_err(|_|VmFault::Other)?.is_none(){NEW_ACCOUNT}else{0})}
fn push(ctx:&mut OperationContext<'_,'_>,v:Word)->Result<OperationControl,VmFault>{ctx.stack.push(v)?;Ok(OperationControl::Continue)} fn push_zero(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{push(ctx,Word::ZERO)} fn token_value(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{push(ctx,ctx.frame.token_value)} fn token_id(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{push(ctx,ctx.frame.token_id)}
fn token_balance(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let token=ctx.stack.pop()?.no_leading_zero_bytes();let address=ctx.stack.pop()?.to_tron_address();let token=String::from_utf8(token).map_err(|_|VmFault::Other)?;let value=ctx.repository.token_balance(&address,&token).map_err(|_|VmFault::Other)?;push(ctx,Word::from(value.max(0) as u64))}
fn is_contract(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let a=ctx.stack.pop()?.to_tron_address();push(ctx,if ctx.repository.contract(&a).map_err(|_|VmFault::Other)?.is_some(){Word::ONE}else{Word::ZERO})}
fn static_guard(ctx:&OperationContext<'_,'_>)->Result<(),VmFault>{if ctx.frame.is_static{Err(VmFault::StaticViolation)}else{Ok(())}}
fn transactional(ctx:&mut OperationContext<'_,'_>,f:impl FnOnce(&mut crate::Repository<'_>)->Result<Word,crate::RepositoryError>)->Result<OperationControl,VmFault>{let child=ctx.repository.begin_child(ChildStorageMode::Copied);match f(ctx.repository){Ok(value)=>{ctx.repository.commit_child(child).map_err(|_|VmFault::Other)?;push(ctx,value)},Err(_)=>{ctx.repository.revoke_child(child).map_err(|_|VmFault::Other)?;push_zero(ctx)}}}
fn freeze_legacy(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{if ctx.rules.vote{static_guard(ctx)?}let kind=ctx.stack.pop()?;let amount=ctx.stack.pop()?;let receiver=ctx.stack.pop()?.to_tron_address();if ctx.rules.freeze_v2{return push_zero(ctx)}let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(if r.freeze_legacy(&owner,&receiver,amount,kind)?{Word::ONE}else{Word::ZERO}))}
fn unfreeze_legacy(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{if ctx.rules.vote{static_guard(ctx)?}let kind=ctx.stack.pop()?;let receiver=ctx.stack.pop()?.to_tron_address();let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(if r.unfreeze_legacy(&owner,&receiver,kind)?.is_some(){Word::ONE}else{Word::ZERO}))}
fn expire(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{let kind=ctx.stack.pop()?;let target=ctx.stack.pop()?.to_tron_address();let value=ctx.repository.freeze_expire_time(&ctx.frame.context_address,&target,kind).map_err(|_|VmFault::Other)?;push(ctx,Word::from((value/1000).max(0) as u64))}
fn freeze_balance_v2(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let kind=ctx.stack.pop()?;let amount=ctx.stack.pop()?;let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(if r.freeze_v2(&owner,amount,kind)?{Word::ONE}else{Word::ZERO}))}
fn unfreeze_balance_v2(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let kind=ctx.stack.pop()?;let amount=ctx.stack.pop()?;let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(if r.unfreeze_v2(&owner,amount,kind)?{Word::ONE}else{Word::ZERO}))}
fn cancel_all(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(if r.cancel_all_unfreeze_v2(&owner)?{Word::ONE}else{Word::ZERO}))}
fn withdraw_expired(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(Word::from(r.withdraw_expired_v2(&owner)?.max(0) as u64)))}
fn delegate_resource(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let kind=ctx.stack.pop()?;let amount=ctx.stack.pop()?;let receiver=ctx.stack.pop()?.to_tron_address();let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(if r.delegate_v2(&owner,&receiver,amount,kind)?{Word::ONE}else{Word::ZERO}))}
fn undelegate_resource(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let kind=ctx.stack.pop()?;let amount=ctx.stack.pop()?;let receiver=ctx.stack.pop()?.to_tron_address();let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(if r.undelegate_v2(&owner,&receiver,amount,kind)?{Word::ONE}else{Word::ZERO}))}
fn vote_witness(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let amount_len=ctx.stack.pop()?.to_i32_safe();let amount_off=ctx.stack.pop()?.to_i32_safe();let witness_len=ctx.stack.pop()?.to_i32_safe();let witness_off=ctx.stack.pop()?.to_i32_safe();if amount_len<0||witness_len<0||amount_len!=witness_len{return push_zero(ctx)}let wl=word32(ctx.memory.read(witness_off.max(0) as usize,32)?)?;let al=word32(ctx.memory.read(amount_off.max(0) as usize,32)?)?;if wl.to_i32_safe()!=witness_len||al.to_i32_safe()!=amount_len{return Err(VmFault::Other)}let mut votes=Vec::with_capacity(witness_len as usize);for i in 0..witness_len as usize{let w=word32(ctx.memory.read(witness_off as usize+32+i*32,32)?)?;let a=word32(ctx.memory.read(amount_off as usize+32+i*32,32)?)?;votes.push(Vote{vote_address:w.to_tron_address().as_bytes().to_vec(),vote_count:a.to_i64_safe()})}let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(if r.vote_witness(&owner,votes)?{Word::ONE}else{Word::ZERO}))}
fn withdraw_reward(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let owner=ctx.frame.context_address;transactional(ctx,move|r|Ok(Word::from(r.withdraw_reward(&owner)?.max(0) as u64)))}
fn call_exec(ctx:&mut OperationContext<'_,'_>,kind:CallKind,with_value:bool,token:bool)->Result<OperationControl,VmFault>{let requested=ctx.stack.pop()?;let destination=ctx.stack.pop()?.to_tron_address();let supplied_value=if with_value{ctx.stack.pop()?}else{Word::ZERO};if ctx.frame.is_static&&!supplied_value.is_zero(){return Err(VmFault::StaticViolation)}let token_id=if token{ctx.stack.pop()?}else{Word::ZERO};let input_offset_word=ctx.stack.pop()?;let input_size_word=ctx.stack.pop()?;let output_offset_word=ctx.stack.pop()?;let output_size_word=ctx.stack.pop()?;let input_end=range_end(input_offset_word,input_size_word)?;let output_end=range_end(output_offset_word,output_size_word)?;let input_size=word_usize(input_size_word)?;let input_offset=if input_size==0{0}else{input_end-input_size};let output_size=word_usize(output_size_word)?;let output_offset=if output_size==0{0}else{output_end-output_size};let data=ctx.memory.read(input_offset,input_size)?;ctx.memory.expand(output_offset,output_size)?;ctx.effects.return_data.clear();let cap=ctx.energy.remaining()-ctx.energy.remaining()/64;let requested=requested.to_i64_safe().max(0);let reserved_energy=requested.min(cap);ctx.energy.spend(reserved_energy)?;let stipend=if with_value&&!supplied_value.is_zero(){STIPEND}else{0};let energy_limit=reserved_energy.checked_add(stipend).ok_or(VmFault::OutOfEnergy)?;let(value,token_value)=if token{(Word::ZERO,supplied_value)}else{(supplied_value,Word::ZERO)};Ok(OperationControl::Call(CallRequest{kind,destination,data,output_offset,output_size,energy_limit,reserved_energy,value,token_value,token_id}))}
fn call(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{call_exec(ctx,CallKind::Call,true,false)}fn callcode(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{call_exec(ctx,CallKind::CallCode,true,false)}fn delegate(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{call_exec(ctx,CallKind::DelegateCall,false,false)}fn staticcall(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{call_exec(ctx,CallKind::StaticCall,false,false)}fn calltoken(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{call_exec(ctx,CallKind::CallToken,true,true)}
fn create(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let value=ctx.stack.pop()?;let offset_word=ctx.stack.pop()?;let size_word=ctx.stack.pop()?;let end=range_end(offset_word,size_word)?;let size=word_usize(size_word)?;let offset=if size==0{0}else{end-size};let init_code=ctx.memory.read(offset,size)?;ctx.effects.return_data.clear();Ok(OperationControl::Create(CreateRequest{kind:CreateKind::Create,init_code,energy_limit:ctx.energy.remaining()-ctx.energy.remaining()/64,value,salt:None}))}fn create2(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;let value=ctx.stack.pop()?;let offset_word=ctx.stack.pop()?;let size_word=ctx.stack.pop()?;let salt=ctx.stack.pop()?;let end=range_end(offset_word,size_word)?;let size=word_usize(size_word)?;let offset=if size==0{0}else{end-size};let init_code=ctx.memory.read(offset,size)?;if ctx.rules.osaka{ctx.effects.return_data.clear();}Ok(OperationControl::Create(CreateRequest{kind:CreateKind::Create2,init_code,energy_limit:ctx.energy.remaining()-ctx.energy.remaining()/64,value,salt:Some(salt)}))}
fn suicide(ctx:&mut OperationContext<'_,'_>)->Result<OperationControl,VmFault>{static_guard(ctx)?;if !ctx.repository.can_selfdestruct(&ctx.frame.context_address,ctx.rules.freeze,ctx.rules.freeze_v2,ctx.rules.selfdestruct_restriction).map_err(|_|VmFault::Other)?{return Ok(OperationControl::Revert(Vec::new()))}let target=ctx.stack.pop()?.to_tron_address();Ok(OperationControl::SelfDestruct(target))}

#[derive(Clone,Copy,Debug,Eq,PartialEq)]pub enum CallKind{Call,CallCode,DelegateCall,StaticCall,CallToken}
#[derive(Clone,Debug,Eq,PartialEq)]pub struct ChildFrame{pub code_address:TronAddress21,pub context_address:TronAddress21,pub caller:TronAddress21,pub call_value:Word,pub token_value:Word,pub token_id:Word,pub depth:u16,pub is_static:bool}
#[must_use]pub fn child_frame(parent:&FrameContext,destination:TronAddress21,value:Word,token_value:Word,token_id:Word,kind:CallKind)->Option<ChildFrame>{if parent.depth>=64{return None}Some(match kind{CallKind::Call|CallKind::CallToken=>ChildFrame{code_address:destination,context_address:destination,caller:parent.context_address,call_value:value,token_value,token_id,depth:parent.depth+1,is_static:parent.is_static},CallKind::CallCode=>ChildFrame{code_address:destination,context_address:parent.context_address,caller:parent.context_address,call_value:value,token_value:Word::ZERO,token_id:Word::ZERO,depth:parent.depth+1,is_static:parent.is_static},CallKind::DelegateCall=>ChildFrame{code_address:destination,context_address:parent.context_address,caller:parent.caller,call_value:parent.call_value,token_value:parent.token_value,token_id:parent.token_id,depth:parent.depth+1,is_static:parent.is_static},CallKind::StaticCall=>ChildFrame{code_address:destination,context_address:destination,caller:parent.context_address,call_value:Word::ZERO,token_value:Word::ZERO,token_id:Word::ZERO,depth:parent.depth+1,is_static:true}})}
pub fn begin_call_child(ctx:&mut OperationContext<'_,'_>)->ChildId{ctx.repository.begin_child(ChildStorageMode::Copied)}
pub fn finish_call_child(ctx:&mut OperationContext<'_,'_>,id:ChildId,outcome:&ExecutionOutcome,record:&mut InternalTransactionRecord)->Result<Word,VmFault>{ctx.effects.return_data=outcome.return_data.clone();if outcome.contract_result==ContractResult::Success{ctx.repository.commit_child(id).map_err(|_|VmFault::Other)?;Ok(Word::ONE)}else{ctx.repository.revoke_child(id).map_err(|_|VmFault::Other)?;record.reject();Ok(Word::ZERO)}}
#[must_use]pub fn create_address(frame:&FrameContext,nonce:i64)->TronAddress21{internal_create_address(&frame.root_txid,nonce)}#[must_use]pub fn create2_address_no_ff(frame:&FrameContext,salt:Word,init_code:&[u8],istanbul:bool)->TronAddress21{let source=if istanbul{frame.context_address}else{frame.caller};create2_address(&source,&Hash32::from_array(salt.to_be_bytes()),init_code)}pub fn validate_deployed_code(code:&[u8],london:bool)->Result<i64,VmFault>{if london&&code.first()==Some(&0xef){return Err(VmFault::InvalidCode)}i64::try_from(code.len()).map_err(|_|VmFault::OutOfEnergy)?.checked_mul(200).ok_or(VmFault::OutOfEnergy)}
macro_rules! v{($energy:expr,$exec:expr)=>{&[OperationVariant{when:ordinary,energy:$energy,execute:$exec}]};}macro_rules! row{($op:expr,$req:expr,$res:expr,$act:expr,$vars:expr)=>{OperationSpec{opcode:$op,required_before:$req,resulting_window:$res,activation:$act,variants:$vars}};}
const SUICIDE_V:[OperationVariant;3]=[OperationVariant{when:ordinary,energy:suicide_e,execute:suicide},OperationVariant{when:fair_energy,energy:suicide_e,execute:suicide},OperationVariant{when:restricted,energy:suicide_e,execute:suicide}];
static ROWS:[OperationSpec;23]=[
row!(0xd0,8,1,transfer,v!(calltoken_e,calltoken)),row!(0xd1,2,1,transfer,v!(fixed::<20>,token_balance)),row!(0xd2,0,1,transfer,v!(fixed::<2>,token_value)),row!(0xd3,0,1,transfer,v!(fixed::<2>,token_id)),row!(0xd4,1,1,solidity059,v!(fixed::<20>,is_contract)),row!(0xd5,3,1,freeze,v!(freeze_e,freeze_legacy)),row!(0xd6,2,1,freeze,v!(fixed::<20_000>,unfreeze_legacy)),row!(0xd7,2,1,freeze,v!(fixed::<50>,expire)),row!(0xd8,4,1,vote,v!(vote_e,vote_witness)),row!(0xd9,0,1,vote,v!(fixed::<20_000>,withdraw_reward)),row!(0xda,2,1,freeze_v2,v!(fixed::<10_000>,freeze_balance_v2)),row!(0xdb,2,1,freeze_v2,v!(fixed::<10_000>,unfreeze_balance_v2)),row!(0xdc,0,1,freeze_v2,v!(fixed::<10_000>,cancel_all)),row!(0xdd,0,1,freeze_v2,v!(fixed::<10_000>,withdraw_expired)),row!(0xde,3,1,freeze_v2,v!(fixed::<10_000>,delegate_resource)),row!(0xdf,3,1,freeze_v2,v!(fixed::<10_000>,undelegate_resource)),row!(0xf0,3,1,always,v!(create_e,create)),row!(0xf1,7,1,always,v!(call_e,call)),row!(0xf2,7,1,always,v!(callcode_e,callcode)),row!(0xf4,6,1,always,v!(delegate_e,delegate)),row!(0xf5,4,1,constantinople,v!(create2_e,create2)),row!(0xfa,6,1,always,v!(delegate_e,staticcall)),row!(0xff,1,0,always,&SUICIDE_V),
];
/// Returns this family's immutable registry rows in numeric opcode order.
#[must_use]pub const fn operation_specs()->&'static[OperationSpec]{&ROWS}
