use crate::Word;
use prost::Message;
use std::collections::{BTreeMap,BTreeSet};
use tron_primitives::TronAddress21;
use tron_protocol::protocol::{account::{AccountResource,FreezeV2,Frozen,UnFreezeV2}, Account, AccountType, ContractState, DelegatedResource, ResourceCode, SmartContract, Vote, Votes, smart_contract::Abi};
use tron_state::{delegation,evaluate_fork_pass,ForkPassInput,ForkVersion,JavaForkMath,ReadView,Session,SessionError,StoreKind};

#[derive(Clone,Debug,Eq,Ord,PartialEq,PartialOrd)] struct StateKey{store:StoreKind,key:Vec<u8>}
#[derive(Clone,Debug,Eq,PartialEq)] enum JournalValue{Put(Vec<u8>),Delete}
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum ChildStorageMode{Shared,Copied}
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub struct ChildId(usize);
#[derive(Clone,Debug,Eq,PartialEq)] pub struct RepositoryDelta{pub store:StoreKind,pub key:Vec<u8>,pub before:Option<Vec<u8>>,pub after:Option<Vec<u8>>}
#[derive(Clone,Debug,Eq,PartialEq)] pub enum RepositoryError{Session(SessionError),ReadOnly,InvalidChild,Decode(&'static str),InvalidDynamicValue{key:String,length:usize},InvalidForkStatsValue{version:i32,index:usize,value:u8},InvalidForkInterval, ForkTimestampOverflow}
impl core::fmt::Display for RepositoryError{fn fmt(&self,f:&mut core::fmt::Formatter<'_>)->core::fmt::Result{write!(f,"repository error: {self:?}")}} impl std::error::Error for RepositoryError{} impl From<SessionError> for RepositoryError{fn from(v:SessionError)->Self{Self::Session(v)}}

enum BaseState<'a>{Session(&'a Session),View(&'a ReadView)}
impl BaseState<'_>{fn get(&self,store:StoreKind,key:&[u8])->Option<Vec<u8>>{match self{Self::Session(v)=>v.store(store).get(key),Self::View(v)=>v.store(store).get(key)}}}
#[derive(Default)] struct RepositoryLayer{persistent:BTreeMap<StateKey,JournalValue>,transient:BTreeMap<(Vec<u8>,Word),Word>,new_contracts:BTreeSet<Vec<u8>>,storage_mode:Option<ChildStorageMode>}

pub struct Repository<'a>{base:BaseState<'a>,layers:Vec<RepositoryLayer>,before:BTreeMap<StateKey,Option<Vec<u8>>>,blackhole_address:TronAddress21}
impl<'a> Repository<'a>{
    #[must_use] pub fn from_session(session:&'a Session)->Self{Self{base:BaseState::Session(session),layers:vec![RepositoryLayer::default()],before:BTreeMap::new(),blackhole_address:TronAddress21::new(0x41,tron_primitives::Address20::from_array([0x41;20]))}}
    #[must_use] pub fn from_view(view:&'a ReadView)->Self{Self{base:BaseState::View(view),layers:vec![RepositoryLayer::default()],before:BTreeMap::new(),blackhole_address:TronAddress21::new(0x41,tron_primitives::Address20::from_array([0x41;20]))}}
    pub fn set_blackhole_address(&mut self,address:TronAddress21){self.blackhole_address=address;}
    #[must_use] pub fn blackhole_address(&self)->TronAddress21{self.blackhole_address}
    fn raw(&self,store:StoreKind,key:&[u8])->Option<Vec<u8>>{let state=StateKey{store,key:key.to_vec()};for layer in self.layers.iter().rev(){if let Some(v)=layer.persistent.get(&state){return match v{JournalValue::Put(v)=>Some(v.clone()),JournalValue::Delete=>None};}}self.base.get(store,key)}
    fn write(&mut self,store:StoreKind,key:Vec<u8>,value:JournalValue){let state=StateKey{store,key};if !self.before.contains_key(&state){self.before.insert(state.clone(),self.raw(state.store,&state.key));}self.layers.last_mut().expect("root").persistent.insert(state,value);}
    pub fn get_raw(&self,store:StoreKind,key:&[u8])->Option<Vec<u8>>{self.raw(store,key)}
    pub fn put_raw(&mut self,store:StoreKind,key:impl Into<Vec<u8>>,value:impl Into<Vec<u8>>){self.write(store,key.into(),JournalValue::Put(value.into()));}
    pub fn delete_raw(&mut self,store:StoreKind,key:impl Into<Vec<u8>>){self.write(store,key.into(),JournalValue::Delete);}
    pub fn begin_child(&mut self,storage_mode:ChildStorageMode)->ChildId{self.layers.push(RepositoryLayer{storage_mode:Some(storage_mode),..RepositoryLayer::default()});ChildId(self.layers.len()-1)}
    pub fn commit_child(&mut self,id:ChildId)->Result<(),RepositoryError>{if id.0+1!=self.layers.len()||id.0==0{return Err(RepositoryError::InvalidChild);}let child=self.layers.pop().expect("checked");let parent=self.layers.last_mut().expect("root");parent.persistent.extend(child.persistent);parent.transient.extend(child.transient);parent.new_contracts.extend(child.new_contracts);Ok(())}
    pub fn revoke_child(&mut self,id:ChildId)->Result<(),RepositoryError>{if id.0+1!=self.layers.len()||id.0==0{return Err(RepositoryError::InvalidChild);}self.layers.pop();Ok(())}
    pub fn child_storage_mode(&self)->Option<ChildStorageMode>{self.layers.last().and_then(|v|v.storage_mode)}
    pub fn transient(&self,address:&TronAddress21,slot:Word)->Word{let key=(address.as_bytes().to_vec(),slot);self.layers.iter().rev().find_map(|l|l.transient.get(&key).copied()).unwrap_or(Word::ZERO)}
    pub fn set_transient(&mut self,address:TronAddress21,slot:Word,value:Word){self.layers.last_mut().expect("root").transient.insert((address.as_bytes().to_vec(),slot),value);}
    pub fn mark_new_contract(&mut self,address:TronAddress21){self.layers.last_mut().expect("root").new_contracts.insert(address.as_bytes().to_vec());}
    pub fn is_new_contract(&self,address:&TronAddress21)->bool{self.layers.iter().rev().any(|l|l.new_contracts.contains(address.as_bytes()))}
    pub fn account(&self,address:&TronAddress21)->Result<Option<Account>,RepositoryError>{decode(self.raw(StoreKind::Account,address.as_bytes()),"account")}
    pub fn put_account(&mut self,account:&Account){self.put_raw(StoreKind::Account,account.address.clone(),account.encode_to_vec());}
    pub fn balance(&self,address:&TronAddress21)->Result<i64,RepositoryError>{Ok(self.account(address)?.map_or(0,|a|a.balance))}
    pub fn set_balance(&mut self,address:&TronAddress21,balance:i64)->Result<(),RepositoryError>{let mut account=self.account(address)?.unwrap_or_else(||Account{address:address.as_bytes().to_vec(),..Account::default()});account.balance=balance;self.put_account(&account);Ok(())}
    pub fn token_balance(&self,address:&TronAddress21,token:&str)->Result<i64,RepositoryError>{Ok(self.account(address)?.and_then(|a|a.asset_v2.get(token).copied()).unwrap_or(0))}
    pub fn set_token_balance(&mut self,address:&TronAddress21,token:String,balance:i64)->Result<(),RepositoryError>{let mut account=self.account(address)?.unwrap_or_else(||Account{address:address.as_bytes().to_vec(),..Account::default()});if balance==0{account.asset_v2.remove(&token);}else{account.asset_v2.insert(token,balance);}self.put_account(&account);Ok(())}
    pub fn contract(&self,address:&TronAddress21)->Result<Option<SmartContract>,RepositoryError>{decode(self.raw(StoreKind::Contract,address.as_bytes()),"contract")}
    pub fn put_contract(&mut self,contract:SmartContract){let split=tron_state::contract::split_contract(contract);let key=split.contract.instance().contract_address.clone();self.put_raw(StoreKind::Contract,key.clone(),split.contract.data());if self.raw(StoreKind::Abi,&key).is_none(){if let Some(abi)=split.abi{self.put_raw(StoreKind::Abi,key,abi.data());}}}
    pub fn abi(&self,address:&TronAddress21)->Result<Option<Abi>,RepositoryError>{decode(self.raw(StoreKind::Abi,address.as_bytes()),"abi")}
    pub fn code(&self,address:&TronAddress21)->Option<Vec<u8>>{self.raw(StoreKind::Code,address.as_bytes())}
    pub fn put_code(&mut self,address:TronAddress21,code:Vec<u8>){self.put_raw(StoreKind::Code,address.as_bytes().to_vec(),code);}
    pub fn create_destination_exists(&self,address:&TronAddress21,constantinople:bool)->Result<bool,RepositoryError>{
        let Some(_account)=self.account(address)? else{return Ok(false)};
        Ok(!constantinople||self.contract(address)?.is_some())
    }
    pub fn prepare_created_contract(&mut self,address:TronAddress21,origin:TronAddress21,root_txid:&tron_primitives::TransactionId,is_create2:bool,constantinople:bool,compatible_evm:bool,version:i32)->Result<(),RepositoryError>{
        let mut account=match self.account(&address)?{
            Some(mut account) if constantinople=>{
                account.r#type=AccountType::Contract as i32;
                account.acquired_delegated_frozen_balance_for_bandwidth=0;
                account.acquired_delegated_frozen_v2_balance_for_bandwidth=0;
                let resource=account.account_resource.get_or_insert_with(AccountResource::default);
                resource.acquired_delegated_frozen_balance_for_energy=0;
                resource.acquired_delegated_frozen_v2_balance_for_energy=0;
                account
            }
            _=>Account{account_name:b"CreatedByContract".to_vec(),r#type:AccountType::Contract as i32,address:address.as_bytes().to_vec(),..Account::default()},
        };
        account.address=address.as_bytes().to_vec();
        self.put_account(&account);
        self.put_contract(SmartContract{
            origin_address:origin.as_bytes().to_vec(),
            contract_address:address.as_bytes().to_vec(),
            consume_user_resource_percent:100,
            trx_hash:if is_create2{root_txid.as_bytes().to_vec()}else{Vec::new()},
            version:if compatible_evm{version}else{0},
            ..SmartContract::default()
        });
        self.mark_new_contract(address);
        Ok(())
    }
    pub fn save_created_code(&mut self,address:TronAddress21,code:Vec<u8>,constantinople:bool)->Result<(),RepositoryError>{
        if constantinople{
            let mut contract=self.contract(&address)?.ok_or(RepositoryError::Decode("created contract"))?;
            contract.code_hash=tron_crypto::keccak256(&code).to_vec();
            self.put_contract(contract);
        }
        self.put_code(address,code);
        Ok(())
    }
    pub fn delete_contract(&mut self,address:&TronAddress21){let key=address.as_bytes().to_vec();self.delete_raw(StoreKind::Code,key.clone());self.delete_raw(StoreKind::Account,key.clone());self.delete_raw(StoreKind::Contract,key);}
    pub fn contract_state(&self,address:&TronAddress21)->Result<Option<ContractState>,RepositoryError>{decode(self.raw(StoreKind::ContractState,address.as_bytes()),"contract state")}
    pub fn put_contract_state(&mut self,address:TronAddress21,state:&ContractState){self.put_raw(StoreKind::ContractState,address.as_bytes().to_vec(),state.encode_to_vec());}
    fn storage_key(address:&TronAddress21,slot:Word,contract_version:i32,tx_hash:Option<&[u8;32]>)->[u8;32]{tron_state::contract::storage_row_key(address.as_bytes(),&slot.to_be_bytes(),contract_version,tx_hash)}
    pub fn storage(&self,address:&TronAddress21,slot:Word,contract_version:i32,tx_hash:Option<&[u8;32]>)->Option<Word>{self.raw(StoreKind::StorageRow,&Self::storage_key(address,slot,contract_version,tx_hash)).and_then(|v|<[u8;32]>::try_from(v).ok()).map(Word::from_be_bytes)}
    pub fn set_storage(&mut self,address:&TronAddress21,slot:Word,value:Word,contract_version:i32,tx_hash:Option<&[u8;32]>){let key=Self::storage_key(address,slot,contract_version,tx_hash);if value.is_zero(){self.delete_raw(StoreKind::StorageRow,key);}else{self.put_raw(StoreKind::StorageRow,key,value.to_be_bytes());}}
    pub fn dynamic_i64(&self,name:&str)->Result<Option<i64>,RepositoryError>{let Some(key)=tron_state::dynamic::key(name)else{return Ok(None)};let Some(v)=self.raw(StoreKind::DynamicProperties,key)else{return Ok(None)};let n=v.len();Ok(Some(match n{8=>i64::from_be_bytes(v.try_into().expect("length")),4=>i64::from(i32::from_be_bytes(v.try_into().expect("length"))),_=>return Err(RepositoryError::InvalidDynamicValue{key:name.into(),length:n})}))}
    pub fn set_dynamic_i64(&mut self,name:&str,value:i64)->Result<(),RepositoryError>{let Some(key)=tron_state::dynamic::key(name)else{return Err(RepositoryError::InvalidDynamicValue{key:name.into(),length:0})};self.put_raw(StoreKind::DynamicProperties,key.to_vec(),value.to_be_bytes());Ok(())}
    pub(crate) fn canonical_fork_pass(&self,fork:ForkVersion)->Result<bool,RepositoryError>{
        let interval_bytes=self.raw(StoreKind::DynamicProperties,tron_state::dynamic::key("MAINTENANCE_TIME_INTERVAL").expect("known dynamic key")).ok_or_else(||RepositoryError::InvalidDynamicValue{key:"MAINTENANCE_TIME_INTERVAL".into(),length:0})?;
        let interval_length=interval_bytes.len();
        let interval=i64::from_be_bytes(interval_bytes.try_into().map_err(|_|RepositoryError::InvalidDynamicValue{key:"MAINTENANCE_TIME_INTERVAL".into(),length:interval_length})?);
        let timestamp_bytes=self.raw(StoreKind::DynamicProperties,tron_state::dynamic::key("LATEST_BLOCK_HEADER_TIMESTAMP").expect("known dynamic key")).ok_or_else(||RepositoryError::InvalidDynamicValue{key:"LATEST_BLOCK_HEADER_TIMESTAMP".into(),length:0})?;
        let timestamp_length=timestamp_bytes.len();
        let timestamp=i64::from_be_bytes(timestamp_bytes.try_into().map_err(|_|RepositoryError::InvalidDynamicValue{key:"LATEST_BLOCK_HEADER_TIMESTAMP".into(),length:timestamp_length})?);
        let stats=self.raw(StoreKind::DynamicProperties,format!("FORK_VERSION_{}",fork.version).as_bytes());
        evaluate_fork_pass(ForkPassInput{target:fork,old_cutoff:16,latest_block_number:0,energy_limit_height:i64::MAX,latest_block_timestamp:timestamp,maintenance_interval:interval,stats:stats.as_deref()},&JavaForkMath).map_err(|error|match error{tron_state::ForkError::InvalidInterval=>RepositoryError::InvalidForkInterval,tron_state::ForkError::TimestampOverflow{..}=>RepositoryError::ForkTimestampOverflow,_=>RepositoryError::Decode("fork activation")})
    }
    fn checked_add(a:i64,b:i64)->Result<i64,RepositoryError>{a.checked_add(b).ok_or(RepositoryError::Decode("long overflow"))}
    fn resource(word:Word,tron_power:bool)->Option<ResourceCode>{match word.to_i64_safe(){0=>Some(ResourceCode::Bandwidth),1=>Some(ResourceCode::Energy),2 if tron_power=>Some(ResourceCode::TronPower),_=>None}}
    fn frozen_v2(a:&Account,k:ResourceCode)->i64{a.frozen_v2.iter().find(|v|v.r#type==k as i32).map_or(0,|v|v.amount)}
    fn add_frozen_v2(a:&mut Account,k:ResourceCode,n:i64)->Result<(),RepositoryError>{if let Some(v)=a.frozen_v2.iter_mut().find(|v|v.r#type==k as i32){v.amount=Self::checked_add(v.amount,n)?}else{a.frozen_v2.push(FreezeV2{r#type:k as i32,amount:n})}Ok(())}
    fn weight_key(k:ResourceCode)->&'static str{match k{ResourceCode::Bandwidth=>"TOTAL_NET_WEIGHT",ResourceCode::Energy=>"TOTAL_ENERGY_WEIGHT",ResourceCode::TronPower=>"TOTAL_TRON_POWER_WEIGHT"}}
    fn change_weight(&mut self,k:ResourceCode,old:i64,new:i64)->Result<(),RepositoryError>{let key=Self::weight_key(k);let total=self.dynamic_i64(key)?.unwrap_or(0);self.set_dynamic_i64(key,Self::checked_add(total,new/1_000_000-old/1_000_000)?) }
    fn legacy_frozen(a:&Account,k:ResourceCode)->i64{match k{ResourceCode::Bandwidth=>a.frozen.iter().map(|v|v.frozen_balance).sum(),ResourceCode::Energy=>a.account_resource.as_ref().and_then(|r|r.frozen_balance_for_energy.as_ref()).map_or(0,|v|v.frozen_balance),ResourceCode::TronPower=>0}}
    fn legacy_expire(a:&Account,k:ResourceCode)->i64{match k{ResourceCode::Bandwidth=>a.frozen.first().map_or(0,|v|v.expire_time),ResourceCode::Energy=>a.account_resource.as_ref().and_then(|r|r.frozen_balance_for_energy.as_ref()).map_or(0,|v|v.expire_time),ResourceCode::TronPower=>0}}
    pub fn can_selfdestruct(&self,owner:&TronAddress21,freeze_enabled:bool,freeze_v2_enabled:bool,restricted:bool)->Result<bool,RepositoryError>{
        let Some(account)=self.account(owner)?else{return Ok(false)};
        if freeze_enabled {
            if account.delegated_frozen_balance_for_bandwidth!=0||account.account_resource.as_ref().is_some_and(|r|r.delegated_frozen_balance_for_energy!=0){return Ok(false)}
            if restricted {let now=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);if account.frozen.iter().any(|v|v.frozen_balance>0&&v.expire_time>now)||account.account_resource.as_ref().and_then(|r|r.frozen_balance_for_energy.as_ref()).is_some_and(|v|v.frozen_balance>0&&v.expire_time>now){return Ok(false)}}
        }
        if freeze_v2_enabled {let now=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);if account.delegated_frozen_v2_balance_for_bandwidth!=0||account.account_resource.as_ref().is_some_and(|r|r.delegated_frozen_v2_balance_for_energy!=0)||account.unfrozen_v2.iter().any(|v|v.unfreeze_expire_time>now){return Ok(false)}}
        Ok(true)
    }
    pub fn transfer_selfdestruct_resources(&mut self,owner:&TronAddress21,inheritor:&TronAddress21,freeze_enabled:bool,freeze_v2_enabled:bool,restricted:bool)->Result<i64,RepositoryError>{
        let Some(mut from)=self.account(owner)?else{return Ok(0)};let mut to=self.account(inheritor)?.unwrap_or_else(||Account{address:inheritor.as_bytes().to_vec(),..Default::default()});
        if freeze_enabled {let bandwidth: i64=from.frozen.iter().map(|v|v.frozen_balance).sum();let energy=from.account_resource.as_ref().and_then(|r|r.frozen_balance_for_energy.as_ref()).map_or(0,|v|v.frozen_balance);to.balance=Self::checked_add(to.balance,Self::checked_add(bandwidth,energy)?)?;self.change_weight(ResourceCode::Bandwidth,bandwidth,0)?;self.change_weight(ResourceCode::Energy,energy,0)?;if restricted{from.frozen.clear();if let Some(r)=from.account_resource.as_mut(){r.frozen_balance_for_energy=None}}}
        let mut expired=0;
        if freeze_v2_enabled {for frozen in &from.frozen_v2{if frozen.amount>0{if let Ok(kind)=ResourceCode::try_from(frozen.r#type){Self::add_frozen_v2(&mut to,kind,frozen.amount)?}}}let now=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);for pending in &from.unfrozen_v2{if pending.unfreeze_amount>0&&pending.unfreeze_expire_time<=now{expired=Self::checked_add(expired,pending.unfreeze_amount)?}}to.balance=Self::checked_add(to.balance,expired)?;from.frozen_v2.clear();from.unfrozen_v2.clear();from.net_usage=0;from.latest_consume_time=0;if let Some(r)=from.account_resource.as_mut(){r.energy_usage=0;r.latest_consume_time_for_energy=0}}
        self.put_account(&from);self.put_account(&to);Ok(expired)
    }
    pub fn freeze_legacy(&mut self,owner:&TronAddress21,receiver:&TronAddress21,amount:Word,kind:Word)->Result<bool,RepositoryError>{
        let n=amount.to_i64_safe();let Some(k)=Self::resource(kind,false)else{return Ok(false)};let Some(mut from)=self.account(owner)?else{return Ok(false)};
        if n<1_000_000||n>from.balance||from.frozen.len()>1{return Ok(false)}
        let mut to=if owner==receiver{None}else{Some(self.account(receiver)?.unwrap_or_else(||Account{address:receiver.as_bytes().to_vec(),..Account::default()}))};
        if to.as_ref().is_some_and(|a|a.r#type==AccountType::Contract as i32){return Ok(false)}
        let now=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);let days=self.dynamic_i64("MIN_FROZEN_TIME")?.unwrap_or(0);let expire=Self::checked_add(now,days.checked_mul(86_400_000).ok_or(RepositoryError::Decode("long overflow"))?)?;
        if let Some(ref mut receiver_account)=to{let key=delegation::legacy_resource_key(owner.as_bytes(),receiver.as_bytes());let mut d=decode::<DelegatedResource>(self.raw(StoreKind::DelegatedResource,&key),"delegated resource")?.unwrap_or(DelegatedResource{from:owner.as_bytes().to_vec(),to:receiver.as_bytes().to_vec(),..Default::default()});match k{ResourceCode::Bandwidth=>{d.frozen_balance_for_bandwidth=Self::checked_add(d.frozen_balance_for_bandwidth,n)?;d.expire_time_for_bandwidth=expire;from.delegated_frozen_balance_for_bandwidth=Self::checked_add(from.delegated_frozen_balance_for_bandwidth,n)?;receiver_account.acquired_delegated_frozen_balance_for_bandwidth=Self::checked_add(receiver_account.acquired_delegated_frozen_balance_for_bandwidth,n)?},ResourceCode::Energy=>{d.frozen_balance_for_energy=Self::checked_add(d.frozen_balance_for_energy,n)?;d.expire_time_for_energy=expire;let resource=from.account_resource.get_or_insert_with(AccountResource::default);resource.delegated_frozen_balance_for_energy=Self::checked_add(resource.delegated_frozen_balance_for_energy,n)?;let resource=receiver_account.account_resource.get_or_insert_with(AccountResource::default);resource.acquired_delegated_frozen_balance_for_energy=Self::checked_add(resource.acquired_delegated_frozen_balance_for_energy,n)?},ResourceCode::TronPower=>unreachable!()}self.put_raw(StoreKind::DelegatedResource,key,d.encode_to_vec());self.put_account(receiver_account)}else{match k{ResourceCode::Bandwidth=>{let old=Self::legacy_frozen(&from,k);if let Some(v)=from.frozen.first_mut(){v.frozen_balance=Self::checked_add(v.frozen_balance,n)?;v.expire_time=expire}else{from.frozen.push(Frozen{frozen_balance:n,expire_time:expire})}debug_assert_eq!(Self::legacy_frozen(&from,k),old+n)},ResourceCode::Energy=>{let resource=from.account_resource.get_or_insert_with(AccountResource::default);let frozen=resource.frozen_balance_for_energy.get_or_insert_with(Frozen::default);frozen.frozen_balance=Self::checked_add(frozen.frozen_balance,n)?;frozen.expire_time=expire},ResourceCode::TronPower=>unreachable!()}}
        from.balance-=n;let total=self.dynamic_i64(Self::weight_key(k))?.unwrap_or(0);self.set_dynamic_i64(Self::weight_key(k),Self::checked_add(total,n/1_000_000)?)?;self.put_account(&from);Ok(true)
    }
    pub fn unfreeze_legacy(&mut self,owner:&TronAddress21,receiver:&TronAddress21,kind:Word)->Result<Option<i64>,RepositoryError>{
        let Some(k)=Self::resource(kind,false)else{return Ok(None)};let Some(mut from)=self.account(owner)?else{return Ok(None)};let now=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);let n;
        if owner!=receiver{let key=delegation::legacy_resource_key(owner.as_bytes(),receiver.as_bytes());let Some(bytes)=self.raw(StoreKind::DelegatedResource,&key)else{return Ok(None)};let mut d=DelegatedResource::decode(bytes.as_slice()).map_err(|_|RepositoryError::Decode("delegated resource"))?;match k{ResourceCode::Bandwidth=>{n=d.frozen_balance_for_bandwidth;if n<=0||d.expire_time_for_bandwidth>now{return Ok(None)}d.frozen_balance_for_bandwidth=0;d.expire_time_for_bandwidth=0;from.delegated_frozen_balance_for_bandwidth-=n;if let Some(mut to)=self.account(receiver)?{to.acquired_delegated_frozen_balance_for_bandwidth-=n;self.put_account(&to)}},ResourceCode::Energy=>{n=d.frozen_balance_for_energy;if n<=0||d.expire_time_for_energy>now{return Ok(None)}d.frozen_balance_for_energy=0;d.expire_time_for_energy=0;let resource=from.account_resource.get_or_insert_with(AccountResource::default);resource.delegated_frozen_balance_for_energy-=n;if let Some(mut to)=self.account(receiver)?{let resource=to.account_resource.get_or_insert_with(AccountResource::default);resource.acquired_delegated_frozen_balance_for_energy-=n;self.put_account(&to)}},ResourceCode::TronPower=>unreachable!()}self.put_raw(StoreKind::DelegatedResource,key,d.encode_to_vec())
        }else{match k{ResourceCode::Bandwidth=>{if from.frozen.is_empty()||!from.frozen.iter().any(|v|v.expire_time<=now){return Ok(None)}let mut released=0;from.frozen.retain(|v|{if v.expire_time<=now{released+=v.frozen_balance;false}else{true}});n=released},ResourceCode::Energy=>{n=Self::legacy_frozen(&from,k);if n<=0||Self::legacy_expire(&from,k)>now{return Ok(None)}if let Some(resource)=from.account_resource.as_mut(){resource.frozen_balance_for_energy=None}},ResourceCode::TronPower=>unreachable!()}}
        from.balance=Self::checked_add(from.balance,n)?;let total=self.dynamic_i64(Self::weight_key(k))?.unwrap_or(0);self.set_dynamic_i64(Self::weight_key(k),Self::checked_add(total,-(n/1_000_000))?)?;self.put_account(&from);Ok(Some(n))
    }
    pub fn freeze_v2(&mut self,owner:&TronAddress21,amount:Word,kind:Word)->Result<bool,RepositoryError>{let n=amount.to_i64_safe();let Some(k)=Self::resource(kind,true)else{return Ok(false)};let Some(mut a)=self.account(owner)?else{return Ok(false)};if n<1_000_000||n>a.balance{return Ok(false)}let old=Self::frozen_v2(&a,k);a.balance-=n;Self::add_frozen_v2(&mut a,k,n)?;self.change_weight(k,old,Self::frozen_v2(&a,k))?;self.put_account(&a);Ok(true)}
    pub fn unfreeze_v2(&mut self,owner:&TronAddress21,amount:Word,kind:Word)->Result<bool,RepositoryError>{let n=amount.to_i64_safe();let Some(k)=Self::resource(kind,true)else{return Ok(false)};let Some(mut a)=self.account(owner)?else{return Ok(false)};let now=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);if n<=0||n>Self::frozen_v2(&a,k)||a.unfrozen_v2.iter().filter(|v|v.unfreeze_expire_time>now).count()>=32{return Ok(false)}let mut expired=0;a.unfrozen_v2.retain(|v|{if v.unfreeze_expire_time<=now{expired+=v.unfreeze_amount;false}else{true}});a.balance=Self::checked_add(a.balance,expired)?;let old=Self::frozen_v2(&a,k);Self::add_frozen_v2(&mut a,k,-n)?;self.change_weight(k,old,Self::frozen_v2(&a,k))?;let days=self.dynamic_i64("UNFREEZE_DELAY_DAYS")?.unwrap_or(0);let expire=Self::checked_add(now,days.checked_mul(86_400_000).ok_or(RepositoryError::Decode("long overflow"))?)?;a.unfrozen_v2.push(UnFreezeV2{r#type:k as i32,unfreeze_amount:n,unfreeze_expire_time:expire});self.put_account(&a);Ok(true)}
    pub fn withdraw_expired_v2(&mut self,owner:&TronAddress21)->Result<i64,RepositoryError>{let Some(mut a)=self.account(owner)?else{return Ok(0)};let now=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);let mut n=0;a.unfrozen_v2.retain(|v|{if v.unfreeze_expire_time<=now{n+=v.unfreeze_amount;false}else{true}});if n>0{a.balance=Self::checked_add(a.balance,n)?;self.put_account(&a)}Ok(n)}
    pub fn cancel_all_unfreeze_v2(&mut self,owner:&TronAddress21)->Result<bool,RepositoryError>{if self.dynamic_i64("ALLOW_CANCEL_ALL_UNFREEZE_V2")?.unwrap_or(0)!=1{return Ok(false)}let Some(mut a)=self.account(owner)?else{return Ok(false)};if a.unfrozen_v2.is_empty(){return Ok(false)}let now=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);for v in core::mem::take(&mut a.unfrozen_v2){if v.unfreeze_expire_time<=now{a.balance=Self::checked_add(a.balance,v.unfreeze_amount)?}else{let Some(k)=ResourceCode::try_from(v.r#type).ok()else{return Ok(false)};let old=Self::frozen_v2(&a,k);Self::add_frozen_v2(&mut a,k,v.unfreeze_amount)?;self.change_weight(k,old,Self::frozen_v2(&a,k))?}}self.put_account(&a);Ok(true)}
    pub fn freeze_expire_time(&self,owner:&TronAddress21,target:&TronAddress21,kind:Word)->Result<i64,RepositoryError>{let k=kind.to_i64_safe();if owner==target{let Some(a)=self.account(owner)?else{return Ok(0)};return Ok(if k==0{a.frozen.first().filter(|v|v.frozen_balance!=0).map_or(0,|v|v.expire_time)}else if k==1{a.account_resource.and_then(|r|r.frozen_balance_for_energy).filter(|v|v.frozen_balance!=0).map_or(0,|v|v.expire_time)}else{0})}let key=delegation::legacy_resource_key(owner.as_bytes(),target.as_bytes());let Some(bytes)=self.raw(StoreKind::DelegatedResource,&key)else{return Ok(0)};let d=DelegatedResource::decode(bytes.as_slice()).map_err(|_|RepositoryError::Decode("delegated resource"))?;Ok(if k==0&&d.frozen_balance_for_bandwidth!=0{d.expire_time_for_bandwidth}else if k==1&&d.frozen_balance_for_energy!=0{d.expire_time_for_energy}else{0})}
    pub fn withdraw_reward(&mut self,owner:&TronAddress21)->Result<i64,RepositoryError>{let Some(mut a)=self.account(owner)?else{return Ok(0)};let n=a.allowance;if n<=0{return Ok(0)}a.allowance=0;a.balance=Self::checked_add(a.balance,n)?;a.latest_withdraw_time=self.dynamic_i64("LATEST_BLOCK_HEADER_TIMESTAMP")?.unwrap_or(0);self.put_account(&a);Ok(n)}
    pub fn vote_witness(&mut self,owner:&TronAddress21,votes:Vec<Vote>)->Result<bool,RepositoryError>{let Some(mut a)=self.account(owner)?else{return Ok(false)};if votes.len()>30||votes.iter().any(|v|v.vote_count<=0||self.raw(StoreKind::Witness,&v.vote_address).is_none()){return Ok(false)}let total=votes.iter().try_fold(0i64,|n,v|Self::checked_add(n,v.vote_count))?;let power=a.frozen.iter().map(|v|v.frozen_balance).sum::<i64>()+a.frozen_v2.iter().map(|v|v.amount).sum::<i64>();if total>power/1_000_000{return Ok(false)}let record=Votes{address:a.address.clone(),old_votes:a.votes.clone(),new_votes:votes.clone()};a.votes=votes;self.put_raw(StoreKind::Votes,owner.as_bytes().to_vec(),record.encode_to_vec());self.put_account(&a);Ok(true)}
    pub fn delegate_v2(&mut self,owner:&TronAddress21,receiver:&TronAddress21,amount:Word,kind:Word)->Result<bool,RepositoryError>{let n=amount.to_i64_safe();let Some(k)=Self::resource(kind,false)else{return Ok(false)};if n<1_000_000||owner==receiver||self.dynamic_i64("ALLOW_DELEGATE_RESOURCE")?.unwrap_or(0)!=1{return Ok(false)}let(Some(mut from),Some(mut to))=(self.account(owner)?,self.account(receiver)?)else{return Ok(false)};if self.contract(receiver)?.is_some()||n>Self::frozen_v2(&from,k){return Ok(false)}Self::add_frozen_v2(&mut from,k,-n)?;match k{ResourceCode::Bandwidth=>{from.delegated_frozen_v2_balance_for_bandwidth=Self::checked_add(from.delegated_frozen_v2_balance_for_bandwidth,n)?;to.acquired_delegated_frozen_v2_balance_for_bandwidth=Self::checked_add(to.acquired_delegated_frozen_v2_balance_for_bandwidth,n)?},ResourceCode::Energy=>{let fr=from.account_resource.get_or_insert_default();fr.delegated_frozen_v2_balance_for_energy=Self::checked_add(fr.delegated_frozen_v2_balance_for_energy,n)?;let tr=to.account_resource.get_or_insert_default();tr.acquired_delegated_frozen_v2_balance_for_energy=Self::checked_add(tr.acquired_delegated_frozen_v2_balance_for_energy,n)?},ResourceCode::TronPower=>return Ok(false)}let key=delegation::resource_v2_key(owner.as_bytes(),receiver.as_bytes(),false);let mut d=self.raw(StoreKind::DelegatedResource,&key).map(|v|DelegatedResource::decode(v.as_slice()).map_err(|_|RepositoryError::Decode("delegated resource"))).transpose()?.unwrap_or_else(||DelegatedResource{from:owner.as_bytes().to_vec(),to:receiver.as_bytes().to_vec(),..Default::default()});if k==ResourceCode::Bandwidth{d.frozen_balance_for_bandwidth=Self::checked_add(d.frozen_balance_for_bandwidth,n)?}else{d.frozen_balance_for_energy=Self::checked_add(d.frozen_balance_for_energy,n)?}self.put_raw(StoreKind::DelegatedResource,key,d.encode_to_vec());self.put_account(&from);self.put_account(&to);Ok(true)}
    pub fn undelegate_v2(&mut self,owner:&TronAddress21,receiver:&TronAddress21,amount:Word,kind:Word)->Result<bool,RepositoryError>{let n=amount.to_i64_safe();let Some(k)=Self::resource(kind,false)else{return Ok(false)};if n<=0{return Ok(false)}let(Some(mut from),Some(mut to))=(self.account(owner)?,self.account(receiver)?)else{return Ok(false)};let key=delegation::resource_v2_key(owner.as_bytes(),receiver.as_bytes(),false);let Some(bytes)=self.raw(StoreKind::DelegatedResource,&key)else{return Ok(false)};let mut d=DelegatedResource::decode(bytes.as_slice()).map_err(|_|RepositoryError::Decode("delegated resource"))?;let held=if k==ResourceCode::Bandwidth{d.frozen_balance_for_bandwidth}else{d.frozen_balance_for_energy};if n>held{return Ok(false)}Self::add_frozen_v2(&mut from,k,n)?;if k==ResourceCode::Bandwidth{d.frozen_balance_for_bandwidth-=n;from.delegated_frozen_v2_balance_for_bandwidth-=n;to.acquired_delegated_frozen_v2_balance_for_bandwidth=to.acquired_delegated_frozen_v2_balance_for_bandwidth.saturating_sub(n)}else{d.frozen_balance_for_energy-=n;let fr=from.account_resource.get_or_insert_default();fr.delegated_frozen_v2_balance_for_energy-=n;let tr=to.account_resource.get_or_insert_default();tr.acquired_delegated_frozen_v2_balance_for_energy=tr.acquired_delegated_frozen_v2_balance_for_energy.saturating_sub(n)}if d.frozen_balance_for_bandwidth==0&&d.frozen_balance_for_energy==0{self.delete_raw(StoreKind::DelegatedResource,key)}else{self.put_raw(StoreKind::DelegatedResource,key,d.encode_to_vec())}self.put_account(&from);self.put_account(&to);Ok(true)}
    #[must_use] pub fn deltas(&self)->Vec<RepositoryDelta>{self.before.iter().map(|(k,b)|RepositoryDelta{store:k.store,key:k.key.clone(),before:b.clone(),after:self.raw(k.store,&k.key)}).filter(|d|d.before!=d.after).collect()}
    pub fn flush_into_session(self)->Result<Vec<RepositoryDelta>,RepositoryError>{let BaseState::Session(session)=self.base else{return Err(RepositoryError::ReadOnly)};if self.layers.len()!=1{return Err(RepositoryError::InvalidChild);}let deltas=self.deltas();for (key,value) in self.layers.into_iter().next().expect("root").persistent{match value{JournalValue::Put(v)=>session.store(key.store).put(&key.key,&v)?,JournalValue::Delete=>session.store(key.store).delete(&key.key)?,}}Ok(deltas)}
}
fn decode<M:Message+Default>(bytes:Option<Vec<u8>>,name:&'static str)->Result<Option<M>,RepositoryError>{bytes.map(|v|M::decode(v.as_slice()).map_err(|_|RepositoryError::Decode(name))).transpose()}
