use tron_crypto::{recover_permission_weight,CryptoEngine,DuplicateSignerPolicy,PermissionError,PermissionKey,RecoverableSignature};
use tron_primitives::{Hash32,TronAddress21};
use tron_protocol::protocol::{Permission,permission::PermissionType,transaction::Contract};
use crate::RawWireTransaction;

pub const TRANSACTION_MAX_BYTE_SIZE:usize=500*1024;
pub const MAX_RESULT_SIZE_IN_TX:usize=64;
pub const MAXIMUM_TIME_UNTIL_EXPIRATION:i64=24*60*60*1000;

#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum AdmissionOrigin{Network,Block}
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub struct AdmissionPolicy{pub engine:CryptoEngine,pub consensus_logic_optimization:bool,pub duplicate_signer_policy:DuplicateSignerPolicy,pub total_signature_limit:usize,pub max_transaction_bytes:usize,pub expiration_horizon_millis:i64}
impl Default for AdmissionPolicy{fn default()->Self{Self{engine:CryptoEngine::Secp256k1,consensus_logic_optimization:false,duplicate_signer_policy:DuplicateSignerPolicy::RecoveredAddress,total_signature_limit:5,max_transaction_bytes:TRANSACTION_MAX_BYTE_SIZE,expiration_horizon_millis:MAXIMUM_TIME_UNTIL_EXPIRATION}}}
#[derive(Clone,Copy,Debug)]pub struct AdmissionClock{pub head_block_time:i64,pub next_block_slot_time:i64,pub now:i64,pub block_number:i64,pub head_slot:i64}
pub struct SignatureAdmission<'a>{pub permission:Option<&'a Permission>,pub default_owner:Option<&'a [u8]>,pub default_active_operations:Option<&'a [u8]>,pub ownerless_shielded:bool}

#[derive(Clone,Debug,Eq,PartialEq)]pub enum AdmissionError{MalformedTransaction(String),MissingContract,MultipleContracts{count:usize},BadBlockResultCount{result_count:usize,transaction_id:Hash32,contract_count:usize},TooBigWithResult{size:usize,max:usize},TooBigTransaction{size:usize,max:usize},Expired{expiration:i64,head:i64},ExpirationBeyondHorizon{expiration:i64,head:i64,horizon:i64},ExpiredForNextSlot{expiration:i64,next_slot:i64},TaposBlockNotFound{key:[u8;2]},TaposHashMismatch{expected:Vec<u8>,actual:Vec<u8>},DuplicateTransaction(Hash32),MissingSignature,TooManySignatures{count:usize,max:usize},UnexpectedTransparentSignature,SignatureIngressFormat{index:usize,length:usize},PermissionMissing{permission_id:i32},PermissionType,PermissionDenied,InvalidPermissionAddress,Signature(PermissionError),InsufficientWeight{weight:i64,threshold:i64}}
impl core::fmt::Display for AdmissionError{fn fmt(&self,f:&mut core::fmt::Formatter<'_>)->core::fmt::Result{match self{Self::MalformedTransaction(s)=>f.write_str(s),Self::MissingContract=>f.write_str("miss sig or contract"),Self::MultipleContracts{count}=>write!(f,"transaction must contain exactly one contract, found {count}"),Self::BadBlockResultCount{result_count,transaction_id,contract_count}=>write!(f,"The result count {result_count} of this transaction {transaction_id} is greater than its contract count {contract_count}"),Self::TooBigWithResult{size,max}=>write!(f,"Too big transaction with result, the size is {size} bytes, maxTxSize {max}"),Self::TooBigTransaction{size,max}=>write!(f,"Too big transaction, the size is {size} bytes, maxTxSize {max}"),Self::Expired{expiration,head}|Self::ExpirationBeyondHorizon{expiration,head,..}=>write!(f,"Transaction expiration, transaction expiration time is {expiration}, but headBlockTime is {head}"),Self::ExpiredForNextSlot{expiration,next_slot}=>write!(f,"Transaction expiration time is {expiration}, but next slot time is {next_slot}"),Self::TaposBlockNotFound{key}=>write!(f,"Tapos failed, block not found, ref block {:02x}{:02x}",key[0],key[1]),Self::TaposHashMismatch{expected,actual}=>write!(f,"Tapos failed, different block hash, expected {expected:02x?}, actual {actual:02x?}"),Self::DuplicateTransaction(id)=>write!(f,"dup transaction {id}"),Self::MissingSignature=>f.write_str("miss sig or contract"),Self::TooManySignatures{count,max}=>write!(f,"too many signatures: {count}, max {max}"),Self::UnexpectedTransparentSignature=>f.write_str("shielded transaction must not carry transparent signatures"),Self::SignatureIngressFormat{index,length}=>write!(f,"signature[{index}] has invalid ingress length {length}"),Self::PermissionMissing{permission_id}=>write!(f,"permission {permission_id} not found"),Self::PermissionType=>f.write_str("permission type is wrong"),Self::PermissionDenied=>f.write_str("permission denied"),Self::InvalidPermissionAddress=>f.write_str("permission key address is invalid"),Self::Signature(e)=>e.fmt(f),Self::InsufficientWeight{weight,threshold}=>write!(f,"weight {weight} is less than threshold {threshold}")}}}
impl std::error::Error for AdmissionError{}


pub struct AdmissionValidator{pub policy:AdmissionPolicy}
impl AdmissionValidator{
 pub fn validate<F>(&self,tx:&mut RawWireTransaction,origin:AdmissionOrigin,clock:AdmissionClock,signature:SignatureAdmission<'_>,mut recent_block:F)->Result<Hash32,AdmissionError>where F:FnMut(&[u8;2])->Option<Vec<u8>>{
  let contract_count=tx.message().raw_data.as_ref().ok_or_else(||AdmissionError::MalformedTransaction("transaction raw_data is missing".into()))?.contract.len();
  match contract_count{0=>return Err(AdmissionError::MissingContract),1=>{},n=>return Err(AdmissionError::MultipleContracts{count:n})}
  let result_count=tx.message().ret.len();
  if origin==AdmissionOrigin::Block&&self.policy.consensus_logic_optimization&&result_count>contract_count{return Err(AdmissionError::BadBlockResultCount{result_count,transaction_id:tx.transaction_id(self.policy.engine),contract_count})}
  let optimize=origin==AdmissionOrigin::Network||self.policy.consensus_logic_optimization;
  if origin==AdmissionOrigin::Network{tx.strip_redundant_results();}
  if optimize{let projected=tx.bytes_without_results().len().checked_add(2*MAX_RESULT_SIZE_IN_TX).ok_or(AdmissionError::TooBigWithResult{size:usize::MAX,max:self.policy.max_transaction_bytes})?;if projected>self.policy.max_transaction_bytes{return Err(AdmissionError::TooBigWithResult{size:projected,max:self.policy.max_transaction_bytes})}}
  if tx.full_bytes().len()>self.policy.max_transaction_bytes{return Err(AdmissionError::TooBigTransaction{size:tx.full_bytes().len(),max:self.policy.max_transaction_bytes})}
  let raw=tx.message().raw_data.as_ref().expect("raw_data checked above");let expiration=raw.expiration;if origin==AdmissionOrigin::Block&&self.policy.consensus_logic_optimization&&expiration<clock.next_block_slot_time{return Err(AdmissionError::ExpiredForNextSlot{expiration,next_slot:clock.next_block_slot_time})}if expiration<=clock.head_block_time{return Err(AdmissionError::Expired{expiration,head:clock.head_block_time})}if expiration>clock.head_block_time.saturating_add(self.policy.expiration_horizon_millis){return Err(AdmissionError::ExpirationBeyondHorizon{expiration,head:clock.head_block_time,horizon:self.policy.expiration_horizon_millis})}
  if raw.ref_block_bytes.len()!=2{return Err(AdmissionError::TaposBlockNotFound{key:[0,0]})}let key=[raw.ref_block_bytes[0],raw.ref_block_bytes[1]];let actual=recent_block(&key).ok_or(AdmissionError::TaposBlockNotFound{key})?;if actual!=raw.ref_block_hash{return Err(AdmissionError::TaposHashMismatch{expected:raw.ref_block_hash.clone(),actual})}
  let id=tx.transaction_id(self.policy.engine);
  self.validate_signatures(tx,signature)?;
  if origin==AdmissionOrigin::Network{tx.sanitize_top_level_unknown_fields().map_err(|e|AdmissionError::MalformedTransaction(e.to_string()))?;}
  Ok(id)
 }
 pub fn validate_signatures(&self,tx:&RawWireTransaction,input:SignatureAdmission<'_>)->Result<(),AdmissionError>{let raw=tx.message().raw_data.as_ref().ok_or(AdmissionError::MissingContract)?;let contract=&raw.contract[0];let signatures=&tx.message().signature;if input.ownerless_shielded{if signatures.is_empty(){return Ok(())}return Err(AdmissionError::UnexpectedTransparentSignature)}if signatures.is_empty(){return Err(AdmissionError::MissingSignature)}if signatures.len()>self.policy.total_signature_limit{return Err(AdmissionError::TooManySignatures{count:signatures.len(),max:self.policy.total_signature_limit})}for(i,s)in signatures.iter().enumerate(){RecoverableSignature::from_ingress_wire(s).map_err(|_|AdmissionError::SignatureIngressFormat{index:i,length:s.len()})?;}
  let owned;let permission=if let Some(p)=input.permission{p}else{let owner=input.default_owner.ok_or(AdmissionError::PermissionMissing{permission_id:contract.permission_id})?;owned=default_permission(contract.permission_id,owner,input.default_active_operations)?;&owned};check_permission(contract,permission)?;
  let mut keys=Vec::with_capacity(permission.keys.len());for key in &permission.keys{keys.push(PermissionKey{address:TronAddress21::validate_mainnet(&key.address).map_err(|_|AdmissionError::InvalidPermissionAddress)?,weight:key.weight})}let weight=recover_permission_weight(self.policy.engine,tx.transaction_id(self.policy.engine).as_bytes(),signatures,&keys,self.policy.duplicate_signer_policy).map_err(AdmissionError::Signature)?;if weight.current_weight<permission.threshold{return Err(AdmissionError::InsufficientWeight{weight:weight.current_weight,threshold:permission.threshold})}Ok(())}
}
fn default_permission(id:i32,owner:&[u8],ops:Option<&[u8]>)->Result<Permission,AdmissionError>{let key=tron_protocol::protocol::Key{address:owner.to_vec(),weight:1};match id{0=>Ok(Permission{r#type:PermissionType::Owner as i32,id:0,permission_name:"owner".into(),threshold:1,parent_id:0,operations:vec![],keys:vec![key]}),2=>Ok(Permission{r#type:PermissionType::Active as i32,id:2,permission_name:"active".into(),threshold:1,parent_id:0,operations:ops.unwrap_or(&[]).to_vec(),keys:vec![key]}),_=>Err(AdmissionError::PermissionMissing{permission_id:id})}}
fn check_permission(contract:&Contract,permission:&Permission)->Result<(),AdmissionError>{if contract.permission_id==0{return Ok(())}if permission.r#type!=PermissionType::Active as i32{return Err(AdmissionError::PermissionType)}let t=usize::try_from(contract.r#type).map_err(|_|AdmissionError::PermissionDenied)?;let byte=t/8;let bit=t%8;if permission.operations.get(byte).is_none_or(|v|v&(1<<bit)==0){return Err(AdmissionError::PermissionDenied)}Ok(())}
#[must_use]pub fn tapos_ref_block_bytes(height:i64)->[u8;2]{let b=height.to_be_bytes();[b[6],b[7]]}
pub fn tapos_ref_block_hash(block_id:&[u8])->Result<[u8;8],AdmissionError>{block_id.get(8..16).and_then(|s|s.try_into().ok()).ok_or_else(||AdmissionError::MalformedTransaction("block id must contain at least 16 bytes".into()))}
