use tron_protocol::{google::protobuf::Any, protocol::{transaction::result::Code, Account, AssetIssueContract, Exchange, ExchangeCreateContract, ExchangeInjectContract, ExchangeTransactionContract, ExchangeWithdrawContract}};
use tron_state::StoreKind;
use crate::{account::charge_fee, context::{checked_add, checked_sub, decode_typed_any, valid_address}, Actuator, ActuatorError, ActuatorResult, ExecutionContext, ValidationContext};
const TRX:&[u8]=b"_";
fn key(id:i64)->[u8;8]{id.to_be_bytes()}
fn numeric(v:&[u8])->bool{!v.is_empty()&&v.iter().all(u8::is_ascii_digit)}
fn hex_bytes(value:&[u8])->String{value.iter().map(|byte|format!("{byte:02x}")).collect()}
fn same(c:&ExecutionContext<'_>)->Result<bool,ActuatorError>{Ok(c.dynamic_long("ALLOW_SAME_TOKEN_NAME")?==1)}
fn hard(c:&ExecutionContext<'_>)->bool{c.dynamic_long("ALLOW_HARDEN_EXCHANGE_CALCULATION").unwrap_or(0)==1}
fn account(c:&ExecutionContext<'_>,a:&[u8])->Result<Account,ActuatorError>{c.decode(StoreKind::Account,a,"Account does not exist").map_err(|error|if error.message=="Account does not exist"{ActuatorError::validation(format!("account[{}] not exists",hex_bytes(a)))}else{error})}
fn put_account(c:&mut ExecutionContext<'_>,a:&Account)->Result<(),ActuatorError>{c.put_message(StoreKind::Account,&a.address,a)}
fn exchange(c:&ExecutionContext<'_>,id:i64)->Result<Exchange,ActuatorError>{c.decode(if same(c)?{StoreKind::ExchangeV2}else{StoreKind::Exchange},&key(id),"Exchange does not exist").map_err(|error|if error.message=="Exchange does not exist"{ActuatorError::validation(format!("Exchange[{id}] not exists"))}else{error})}
fn balance(c:&ExecutionContext<'_>,a:&Account,t:&[u8])->Result<i64,ActuatorError>{if t==TRX{return Ok(a.balance)}if same(c)?{c.account_asset_balance(a,t)}else{Ok(*a.asset.get(core::str::from_utf8(t).unwrap_or("")).unwrap_or(&0))}}
fn set_balance(c:&mut ExecutionContext<'_>,a:&mut Account,t:&[u8],v:i64)->Result<(),ActuatorError>{if t==TRX{a.balance=v;return Ok(())}let s=core::str::from_utf8(t).map_err(|_|ActuatorError::execution("asset id is not UTF-8"))?.to_owned();if same(c)?{c.set_account_asset_balance(a,t,v)}else{a.asset.insert(s,v);let issue:AssetIssueContract=c.decode(StoreKind::AssetIssue,t,"Asset does not exist")?;c.set_account_asset_balance(a,issue.id.as_bytes(),v)}}
fn add_balance(c:&mut ExecutionContext<'_>,a:&mut Account,t:&[u8],v:i64)->Result<(),ActuatorError>{let n=checked_add(balance(c,a,t)?,v)?;set_balance(c,a,t,n)}
fn sub_balance(c:&mut ExecutionContext<'_>,a:&mut Account,t:&[u8],v:i64)->Result<(),ActuatorError>{let n=checked_sub(balance(c,a,t)?,v)?;set_balance(c,a,t,n)}
fn validate_token(c:&ExecutionContext<'_>,t:&[u8],label:&str)->Result<(),ActuatorError>{if same(c)?&&t!=TRX&&!numeric(t){let message=if label.is_empty(){"token id is not a valid number".to_owned()}else{format!("{label} token id is not a valid number")};Err(ActuatorError::validation(message))}else{Ok(())}}
fn proportional(n:i64,q:i64,d:i64)->Result<i64,ActuatorError>{let v=i128::from(n)*i128::from(q)/i128::from(d);i64::try_from(v).map_err(|_|ActuatorError::arithmetic("long overflow"))}
fn add_exchange_balance(context: &ExecutionContext<'_>, balance: i64, amount: i64) -> Result<i64, ActuatorError> {
    if hard(context) {
        checked_add(balance, amount)
    } else {
        Ok(balance.wrapping_add(amount))
    }
}

fn subtract_exchange_balance(context: &ExecutionContext<'_>, balance: i64, amount: i64) -> Result<i64, ActuatorError> {
    if hard(context) {
        checked_sub(balance, amount)
    } else {
        Ok(balance.wrapping_sub(amount))
    }
}
fn trade(e:&Exchange,sell:&[u8],quant:i64,hardened:bool)->Result<(i64,i64,i64),ActuatorError>{let (sb,bb,first)=if sell==e.first_token_id{(e.first_token_balance,e.second_token_balance,true)}else{(e.second_token_balance,e.first_token_balance,false)};let out=if hardened{safe_trade(sb,bb,quant)?}else{legacy_trade(sb,bb,quant)};let ns=if hardened{checked_add(sb,quant)?}else{sb.wrapping_add(quant)};let nb=if hardened{checked_sub(bb,out)?}else{bb.wrapping_sub(out)};if hardened&&(ns<0||nb<0){return Err(ActuatorError::validation("Exchange balance must be >=0 after transaction"));}Ok(if first{(out,ns,nb)}else{(out,nb,ns)})}
fn legacy_trade(sell:i64,buy:i64,quant:i64)->i64{let supply=1e18_f64;let new=sell.wrapping_add(quant);let relay=(-supply*(1.0-(1.0+quant as f64/new as f64).powf(0.0005))) as i64;let left=(1_000_000_000_000_000_000_i64).wrapping_add(relay);(buy as f64*((1.0+relay as f64/left as f64).powf(2000.0)-1.0)) as i64}
fn safe_trade(sell:i64,buy:i64,quant:i64)->Result<i64,ActuatorError>{let new=checked_add(sell,quant)?;let base=1.0+quant as f64/new as f64;let relay=(-1e18_f64*(1.0-base.powf(0.0005))).trunc();let result=(buy as f64*((1.0+relay/1e18_f64).powf(2000.0)-1.0)).trunc();if !result.is_finite()||result<i64::MIN as f64||result>i64::MAX as f64{Err(ActuatorError::arithmetic("long overflow"))}else{Ok(result as i64)}}
fn convert_id(c:&ExecutionContext<'_>,token:&[u8])->Result<Vec<u8>,ActuatorError>{if token==TRX{return Ok(token.to_vec())}let issue:AssetIssueContract=c.decode(StoreKind::AssetIssue,token,"Asset does not exist")?;Ok(issue.id.into_bytes())}
fn save_exchange(c:&mut ExecutionContext<'_>,e:&Exchange)->Result<(),ActuatorError>{if same(c)?{c.put_message(StoreKind::ExchangeV2,&key(e.exchange_id),e)}else{c.put_message(StoreKind::Exchange,&key(e.exchange_id),e)?;let mut v2=e.clone();v2.first_token_id=convert_id(c,&v2.first_token_id)?;v2.second_token_id=convert_id(c,&v2.second_token_id)?;c.put_message(StoreKind::ExchangeV2,&key(v2.exchange_id),&v2)}}
fn common_validate(c:&ValidationContext<'_>,owner:&[u8],id:i64)->Result<(Account,Exchange),ActuatorError>{if !valid_address(owner){return Err(ActuatorError::validation("Invalid address"));}Ok((account(c,owner)?,exchange(c,id)?))}

macro_rules! ctor{($name:ident,$contract:ty,$url:literal)=>{pub struct $name{any:Any,contract:$contract}impl $name{pub fn new(any:Any)->Result<Self,ActuatorError>{let contract=decode_typed_any(&any,$url)?;Ok(Self{any,contract})}pub fn raw_any(&self)->&Any{&self.any}}};}
ctor!(ExchangeCreateActuator,ExchangeCreateContract,"protocol.ExchangeCreateContract");
impl Actuator for ExchangeCreateActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{let x=&self.contract;if !valid_address(&x.owner_address){return Err(ActuatorError::validation("Invalid address"));}let a=account(c,&x.owner_address)?;let fee=c.dynamic_long("EXCHANGE_CREATE_FEE")?;if a.balance<fee{return Err(ActuatorError::validation("No enough balance for exchange create fee!"));}validate_token(c,&x.first_token_id,"first")?;validate_token(c,&x.second_token_id,"second")?;if x.first_token_id==x.second_token_id{return Err(ActuatorError::validation("cannot exchange same tokens"));}if x.first_token_balance<=0||x.second_token_balance<=0{return Err(ActuatorError::validation("token balance must greater than zero"));}let limit=c.dynamic_long("EXCHANGE_BALANCE_LIMIT")?;if x.first_token_balance>limit||x.second_token_balance>limit{return Err(ActuatorError::validation(format!("token balance must less than {limit}")));}for(token,amount,label)in[(&x.first_token_id,x.first_token_balance,"first"),(&x.second_token_id,x.second_token_balance,"second")]{if token.as_slice()==TRX{if a.balance<checked_add(amount,fee)?{return Err(ActuatorError::validation("balance is not enough"));}}else if balance(c,&a,token)?<amount{return Err(ActuatorError::validation(format!("{label} token balance is not enough")));}}Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,r:&mut ActuatorResult)->Result<(),ActuatorError>{let x=&self.contract;let fee=c.dynamic_long("EXCHANGE_CREATE_FEE")?;let mut a=account(c,&x.owner_address)?;charge_fee(c,&mut a,fee)?;sub_balance(c,&mut a,&x.first_token_id,x.first_token_balance)?;sub_balance(c,&mut a,&x.second_token_id,x.second_token_balance)?;let id=checked_add(c.dynamic_long("LATEST_EXCHANGE_NUM")?,1)?;let now=c.dynamic_long("LATEST_BLOCK_HEADER_TIMESTAMP")?;let legacy=Exchange{exchange_id:id,creator_address:x.owner_address.clone(),create_time:now,first_token_id:x.first_token_id.clone(),first_token_balance:x.first_token_balance,second_token_id:x.second_token_id.clone(),second_token_balance:x.second_token_balance};if !same(c)?{c.put_message(StoreKind::Exchange,&key(id),&legacy)?;}let mut v2=legacy;if !same(c)?{v2.first_token_id=convert_id(c,&v2.first_token_id)?;v2.second_token_id=convert_id(c,&v2.second_token_id)?;}c.put_message(StoreKind::ExchangeV2,&key(id),&v2)?;put_account(c,&a)?;c.put_dynamic_long("LATEST_EXCHANGE_NUM",id)?;r.exchange_id=id;r.fee=fee;r.code=Code::Sucess;Ok(())}}
ctor!(ExchangeInjectActuator,ExchangeInjectContract,"protocol.ExchangeInjectContract");
impl Actuator for ExchangeInjectActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{let (a,e)=common_validate(c,&self.contract.owner_address,self.contract.exchange_id)?;if a.address!=e.creator_address{return Err(ActuatorError::validation(format!("account[{}] is not creator",hex_bytes(&self.contract.owner_address))));}validate_token(c,&self.contract.token_id,"")?;if self.contract.token_id!=e.first_token_id&&self.contract.token_id!=e.second_token_id{return Err(ActuatorError::validation("token id is not in exchange"));}if self.contract.quant<=0{return Err(ActuatorError::validation("injected token quant must greater than zero"));}let (n,d,other)=if self.contract.token_id==e.first_token_id{(e.second_token_balance,e.first_token_balance,&e.second_token_id)}else{(e.first_token_balance,e.second_token_balance,&e.first_token_id)};if d==0||n==0{return Err(ActuatorError::validation("Token balance in exchange is equal with 0,the exchange has been closed"));}let oq=proportional(n,self.contract.quant,d)?;if oq<=0{return Err(ActuatorError::validation("the calculated token quant  must be greater than 0"));}let limit=c.dynamic_long("EXCHANGE_BALANCE_LIMIT")?;if d.saturating_add(self.contract.quant)>limit||n.saturating_add(oq)>limit{return Err(ActuatorError::validation(format!("token balance must less than {limit}")));}if balance(c,&a,&self.contract.token_id)?<self.contract.quant{return Err(ActuatorError::validation(if self.contract.token_id==TRX{"balance is not enough"}else{"token balance is not enough"}));}if balance(c,&a,other)?<oq{return Err(ActuatorError::validation(if other.as_slice()==TRX{"balance is not enough"}else{"another token balance is not enough"}));}Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,r:&mut ActuatorResult)->Result<(),ActuatorError>{let mut a=account(c,&self.contract.owner_address)?;let mut e=exchange(c,self.contract.exchange_id)?;let (n,d,other,first)=if self.contract.token_id==e.first_token_id{(e.second_token_balance,e.first_token_balance,e.second_token_id.clone(),true)}else{(e.first_token_balance,e.second_token_balance,e.first_token_id.clone(),false)};let oq=proportional(n,self.contract.quant,d)?;if first{e.first_token_balance=add_exchange_balance(c, e.first_token_balance, self.contract.quant)?;e.second_token_balance=add_exchange_balance(c, e.second_token_balance, oq)?}else{e.second_token_balance=add_exchange_balance(c, e.second_token_balance, self.contract.quant)?;e.first_token_balance=add_exchange_balance(c, e.first_token_balance, oq)?}sub_balance(c,&mut a,&self.contract.token_id,self.contract.quant)?;sub_balance(c,&mut a,&other,oq)?;put_account(c,&a)?;save_exchange(c,&e)?;r.exchange_inject_another_amount=oq;r.code=Code::Sucess;Ok(())}}
ctor!(ExchangeWithdrawActuator,ExchangeWithdrawContract,"protocol.ExchangeWithdrawContract");
impl Actuator for ExchangeWithdrawActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{let (a,e)=common_validate(c,&self.contract.owner_address,self.contract.exchange_id)?;if a.address!=e.creator_address{return Err(ActuatorError::validation(format!("account[{}] is not creator",hex_bytes(&self.contract.owner_address))));}validate_token(c,&self.contract.token_id,"")?;if self.contract.token_id!=e.first_token_id&&self.contract.token_id!=e.second_token_id{return Err(ActuatorError::validation("token is not in exchange"));}if self.contract.quant<=0{return Err(ActuatorError::validation("withdraw token quant must greater than zero"));}let(n,d)=if self.contract.token_id==e.first_token_id{(e.second_token_balance,e.first_token_balance)}else{(e.first_token_balance,e.second_token_balance)};if n==0||d==0{return Err(ActuatorError::validation("Token balance in exchange is equal with 0,the exchange has been closed"));}let oq=proportional(n,self.contract.quant,d)?;if oq<=0{return Err(ActuatorError::validation("withdraw another token quant must greater than zero"));}if d<self.contract.quant||n<oq{return Err(ActuatorError::validation("exchange balance is not enough"));}let remainder=(i128::from(n)*i128::from(self.contract.quant))%i128::from(d);if remainder*10_000>i128::from(oq)*i128::from(d){return Err(ActuatorError::validation("Not precise enough"));}Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,r:&mut ActuatorResult)->Result<(),ActuatorError>{let mut a=account(c,&self.contract.owner_address)?;let mut e=exchange(c,self.contract.exchange_id)?;let(n,d,other,first)=if self.contract.token_id==e.first_token_id{(e.second_token_balance,e.first_token_balance,e.second_token_id.clone(),true)}else{(e.first_token_balance,e.second_token_balance,e.first_token_id.clone(),false)};let oq=proportional(n,self.contract.quant,d)?;if first{e.first_token_balance=subtract_exchange_balance(c, e.first_token_balance, self.contract.quant)?;e.second_token_balance=subtract_exchange_balance(c, e.second_token_balance, oq)?}else{e.second_token_balance=subtract_exchange_balance(c, e.second_token_balance, self.contract.quant)?;e.first_token_balance=subtract_exchange_balance(c, e.first_token_balance, oq)?}add_balance(c,&mut a,&self.contract.token_id,self.contract.quant)?;add_balance(c,&mut a,&other,oq)?;put_account(c,&a)?;save_exchange(c,&e)?;r.exchange_withdraw_another_amount=oq;r.code=Code::Sucess;Ok(())}}
ctor!(ExchangeTransactionActuator,ExchangeTransactionContract,"protocol.ExchangeTransactionContract");
impl Actuator for ExchangeTransactionActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{if !valid_address(&self.contract.owner_address){return Err(ActuatorError::validation("Invalid address"));}let a=account(c,&self.contract.owner_address)?;if a.balance<0{return Err(ActuatorError::validation("No enough balance for exchange transaction fee!"));}let e=exchange(c,self.contract.exchange_id)?;validate_token(c,&self.contract.token_id,"")?;if self.contract.token_id!=e.first_token_id&&self.contract.token_id!=e.second_token_id{return Err(ActuatorError::validation("token is not in exchange"));}if self.contract.quant<=0{return Err(ActuatorError::validation("token quant must greater than zero"));}if self.contract.expected<=0{return Err(ActuatorError::validation("token expected must greater than zero"));}if e.first_token_balance==0||e.second_token_balance==0{return Err(ActuatorError::validation("Token balance in exchange is equal with 0,the exchange has been closed"));}let(out,nf,ns)=trade(&e,&self.contract.token_id,self.contract.quant,hard(c))?;let limit=c.dynamic_long("EXCHANGE_BALANCE_LIMIT")?;if nf>limit||ns>limit{return Err(ActuatorError::validation(format!("token balance must less than {limit}")));}if balance(c,&a,&self.contract.token_id)?<self.contract.quant{return Err(ActuatorError::validation(if self.contract.token_id==TRX{"balance is not enough"}else{"token balance is not enough"}));}if out<self.contract.expected{return Err(ActuatorError::validation("token required must greater than expected"));}Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,r:&mut ActuatorResult)->Result<(),ActuatorError>{let mut a=account(c,&self.contract.owner_address)?;let mut e=exchange(c,self.contract.exchange_id)?;let(out,nf,ns)=trade(&e,&self.contract.token_id,self.contract.quant,hard(c))?;let other=if self.contract.token_id==e.first_token_id{e.second_token_id.clone()}else{e.first_token_id.clone()};e.first_token_balance=nf;e.second_token_balance=ns;sub_balance(c,&mut a,&self.contract.token_id,self.contract.quant)?;add_balance(c,&mut a,&other,out)?;put_account(c,&a)?;save_exchange(c,&e)?;r.exchange_received_amount=out;r.code=Code::Sucess;Ok(())}}
