use prost::Message;
use tron_crypto::keccak256;
use tron_protocol::{google::protobuf::Any, protocol::{market_order::State, Account, MarketAccountOrder, MarketCancelOrderContract, MarketOrder, MarketOrderDetail, MarketOrderIdList, MarketSellAssetContract}};
use tron_state::{market::{pair_key, pair_price_head_key, pair_price_key}, StoreKind};

use crate::{account::charge_fee, context::{checked_add, checked_sub, decode_typed_any, valid_address}, Actuator, ActuatorError, ActuatorResult, ExecutionContext, ValidationContext};

const TRX: &[u8] = b"_";
const MAX_ACTIVE_ORDER_NUM: i64 = 100;
const MAX_MATCH_NUM: usize = 20;

fn account(c: &ExecutionContext<'_>, address: &[u8]) -> Result<Account, ActuatorError> { c.decode(StoreKind::Account, address, "Account does not exist!") }
fn put_account(c: &mut ExecutionContext<'_>, a: &Account) -> Result<(), ActuatorError> { c.put_message(StoreKind::Account, &a.address, a) }
fn valid_token(id: &[u8]) -> bool { id == TRX || !id.is_empty() && id.iter().all(u8::is_ascii_digit) }
fn asset_exists(c: &ExecutionContext<'_>, id: &[u8]) -> Result<bool, ActuatorError> { Ok(id == TRX || c.get(StoreKind::AssetIssueV2, id)?.is_some()) }
fn balance(c: &ExecutionContext<'_>, a: &Account, id: &[u8]) -> Result<i64, ActuatorError> { if id == TRX { Ok(a.balance) } else { c.account_asset_balance(a, id) } }
fn set_balance(c: &mut ExecutionContext<'_>, a: &mut Account, id: &[u8], value: i64) -> Result<(), ActuatorError> { if id == TRX { a.balance=value; Ok(()) } else { c.set_account_asset_balance(a,id,value) } }
fn add_balance(c: &mut ExecutionContext<'_>, a: &mut Account, id: &[u8], amount: i64) -> Result<(), ActuatorError> { let value=checked_add(balance(c,a,id)?,amount)?; set_balance(c,a,id,value) }
fn sub_balance(c: &mut ExecutionContext<'_>, a: &mut Account, id: &[u8], amount: i64) -> Result<(), ActuatorError> { let value=checked_sub(balance(c,a,id)?,amount)?; set_balance(c,a,id,value) }
fn decode<M: Message+Default>(c: &ExecutionContext<'_>, kind: StoreKind, key: &[u8], missing: &'static str)->Result<M,ActuatorError>{c.decode(kind,key,missing)}
fn put<M: Message>(c:&mut ExecutionContext<'_>,kind:StoreKind,key:&[u8],value:&M)->Result<(),ActuatorError>{c.put_message(kind,key,value)}
fn remove_account_order(c:&mut ExecutionContext<'_>, order:&MarketOrder)->Result<(),ActuatorError>{ let mut a:MarketAccountOrder=decode(c,StoreKind::MarketAccount,&order.owner_address,"market account does not exist")?; a.orders.retain(|id|id!=&order.order_id); a.count=checked_sub(a.count,1)?; put(c,StoreKind::MarketAccount,&a.owner_address,&a) }
fn order_id(owner:&[u8],sell:&[u8],buy:&[u8],count:i64)->Vec<u8>{ let mut bytes=vec![0;owner.len()+46]; bytes[..owner.len()].copy_from_slice(owner); bytes[owner.len()..owner.len()+sell.len()].copy_from_slice(sell); bytes[owner.len()+19..owner.len()+19+buy.len()].copy_from_slice(buy); bytes[owner.len()+38..].copy_from_slice(&count.to_be_bytes()); keccak256(&bytes).to_vec() }
fn ratio_mul(a:i64,b:i64,c:i64)->Result<i64,ActuatorError>{ if c==0{return Err(ActuatorError::arithmetic("/ by zero"));} let v=(a as i128)*(b as i128)/(c as i128); i64::try_from(v).map_err(|_|ActuatorError::arithmetic("long overflow")) }
fn price_matches(t:&MarketOrder,m:&MarketOrder)->bool{ (t.sell_token_quantity as i128)*(m.sell_token_quantity as i128) >= (t.buy_token_quantity as i128)*(m.buy_token_quantity as i128) }
fn price_count(c:&ExecutionContext<'_>,sell:&[u8],buy:&[u8])->Result<i64,ActuatorError>{ let key=pair_key(sell,buy).map_err(|e|ActuatorError::execution(e.to_string()))?; Ok(c.get(StoreKind::MarketPairToPrice,&key)?.map_or(0,|v|i64::from_be_bytes(v.try_into().unwrap_or_default()))) }
fn price_keys(c:&ExecutionContext<'_>,sell:&[u8],buy:&[u8])->Result<Vec<Vec<u8>>,ActuatorError>{ let pair=pair_key(sell,buy).map_err(|e|ActuatorError::execution(e.to_string()))?; let head=pair_price_head_key(sell,buy).map_err(|e|ActuatorError::execution(e.to_string()))?; c.market_ordered(StoreKind::MarketPairPriceToOrder,&pair,&head,MAX_MATCH_NUM+1) }

fn unlink(c:&mut ExecutionContext<'_>, order:&mut MarketOrder)->Result<(),ActuatorError>{let key=pair_price_key(&order.sell_token_id,&order.buy_token_id,order.sell_token_quantity,order.buy_token_quantity).map_err(|e|ActuatorError::execution(e.to_string()))?;let original=c.get(StoreKind::MarketPairPriceToOrder,&key)?.ok_or_else(||ActuatorError::execution("market price does not exist"))?;let mut ids=MarketOrderIdList::decode(original.as_slice()).map_err(|e|ActuatorError::execution(e.to_string()))?;if !order.prev.is_empty(){let mut p:MarketOrder=decode(c,StoreKind::MarketOrder,&order.prev,"orderId not exists")?;p.next=order.next.clone();put(c,StoreKind::MarketOrder,&p.order_id,&p)?}else{ids.head=order.next.clone()}if !order.next.is_empty(){let mut n:MarketOrder=decode(c,StoreKind::MarketOrder,&order.next,"orderId not exists")?;n.prev=order.prev.clone();put(c,StoreKind::MarketOrder,&n.order_id,&n)?}else{ids.tail=order.prev.clone()}order.prev.clear();order.next.clear();if ids.head.is_empty(){c.delete(StoreKind::MarketPairPriceToOrder,&key)?;let pair=pair_key(&order.sell_token_id,&order.buy_token_id).map_err(|e|ActuatorError::execution(e.to_string()))?;let count=price_count(c,&order.sell_token_id,&order.buy_token_id)?-1;if count==0{c.delete(StoreKind::MarketPairToPrice,&pair)?;let head=pair_price_head_key(&order.sell_token_id,&order.buy_token_id).map_err(|e|ActuatorError::execution(e.to_string()))?;if c.get(StoreKind::MarketPairPriceToOrder,&head)?.is_some(){c.delete(StoreKind::MarketPairPriceToOrder,&head)?}}else{c.put(StoreKind::MarketPairToPrice,&pair,&count.to_be_bytes())?}}else if ids.encode_to_vec()!=original{put(c,StoreKind::MarketPairPriceToOrder,&key,&ids)?}Ok(())}
fn append(c:&mut ExecutionContext<'_>,order:&mut MarketOrder)->Result<(),ActuatorError>{let key=pair_price_key(&order.sell_token_id,&order.buy_token_id,order.sell_token_quantity,order.buy_token_quantity).map_err(|e|ActuatorError::execution(e.to_string()))?;let existing=c.get(StoreKind::MarketPairPriceToOrder,&key)?;let mut ids=existing.as_deref().map(MarketOrderIdList::decode).transpose().map_err(|e|ActuatorError::execution(e.to_string()))?.unwrap_or_default();if !ids.tail.is_empty(){let mut tail:MarketOrder=decode(c,StoreKind::MarketOrder,&ids.tail,"orderId not exists")?;tail.next=order.order_id.clone();order.prev=tail.order_id.clone();put(c,StoreKind::MarketOrder,&tail.order_id,&tail)?}else{ids.head=order.order_id.clone()}ids.tail=order.order_id.clone();if existing.is_none(){let pair=pair_key(&order.sell_token_id,&order.buy_token_id).map_err(|e|ActuatorError::execution(e.to_string()))?;let count=price_count(c,&order.sell_token_id,&order.buy_token_id)?;if count==0{let head=pair_price_head_key(&order.sell_token_id,&order.buy_token_id).map_err(|e|ActuatorError::execution(e.to_string()))?;c.put(StoreKind::MarketPairPriceToOrder,&head,&[])?}c.put(StoreKind::MarketPairToPrice,&pair,&checked_add(count,1)?.to_be_bytes())?}put(c,StoreKind::MarketPairPriceToOrder,&key,&ids)}

pub struct MarketSellAssetActuator{any:Any,contract:MarketSellAssetContract}
impl MarketSellAssetActuator{pub fn new(any:Any)->Result<Self,ActuatorError>{let contract=decode_typed_any(&any,"protocol.MarketSellAssetContract")?;Ok(Self{any,contract})}pub fn raw_any(&self)->&Any{&self.any}}
impl Actuator for MarketSellAssetActuator{
 fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}
 fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{let x=&self.contract;if c.dynamic_long("ALLOW_MARKET_TRANSACTION")?!=1{return Err(ActuatorError::validation("Not support Market Transaction, need to be opened by the committee"))}if !valid_address(&x.owner_address){return Err(ActuatorError::validation("Invalid address"))}let a=account(c,&x.owner_address)?;if !valid_token(&x.sell_token_id){return Err(ActuatorError::validation("sellTokenId is not a valid number"))}if !valid_token(&x.buy_token_id){return Err(ActuatorError::validation("buyTokenId is not a valid number"))}if x.sell_token_id==x.buy_token_id{return Err(ActuatorError::validation("cannot exchange same tokens"))}if x.sell_token_quantity<=0||x.buy_token_quantity<=0{return Err(ActuatorError::validation("token quantity must greater than zero"))}let limit=c.dynamic_long("MARKET_QUANTITY_LIMIT")?;if x.sell_token_quantity>limit||x.buy_token_quantity>limit{return Err(ActuatorError::validation(format!("token quantity must less than {limit}")))}if let Some(v)=c.get(StoreKind::MarketAccount,&x.owner_address)?{let m=MarketAccountOrder::decode(v.as_slice()).map_err(|e|ActuatorError::execution(e.to_string()))?;if m.count>=MAX_ACTIVE_ORDER_NUM{return Err(ActuatorError::validation("Maximum number of orders exceeded，100"))}}let fee=c.dynamic_long("MARKET_SELL_FEE")?;let needed=if x.sell_token_id==TRX{checked_add(x.sell_token_quantity,fee)?}else{fee};if a.balance<needed{return Err(ActuatorError::validation("No enough balance !"))}if !asset_exists(c,&x.sell_token_id)?{return Err(ActuatorError::validation("No sellTokenId !"))}if balance(c,&a,&x.sell_token_id)?<x.sell_token_quantity{return Err(ActuatorError::validation("SellToken balance is not enough !"))}if !asset_exists(c,&x.buy_token_id)?{return Err(ActuatorError::validation("No buyTokenId !"))}Ok(())}
 fn execute_in(&self,c:&mut ExecutionContext<'_>,r:&mut ActuatorResult)->Result<(),ActuatorError>{let x=&self.contract;let fee=c.dynamic_long("MARKET_SELL_FEE")?;let mut taker_account=account(c,&x.owner_address)?;charge_fee(c,&mut taker_account,fee)?;sub_balance(c,&mut taker_account,&x.sell_token_id,x.sell_token_quantity)?;let mut ma=c.get(StoreKind::MarketAccount,&x.owner_address)?.map(|v|MarketAccountOrder::decode(v.as_slice())).transpose().map_err(|e|ActuatorError::execution(e.to_string()))?.unwrap_or(MarketAccountOrder{owner_address:x.owner_address.clone(),..Default::default()});let id=order_id(&x.owner_address,&x.sell_token_id,&x.buy_token_id,ma.total_count);ma.orders.push(id.clone());ma.count+=1;ma.total_count+=1;let mut taker=MarketOrder{order_id:id.clone(),owner_address:x.owner_address.clone(),create_time:c.dynamic_long("LATEST_BLOCK_HEADER_TIMESTAMP")?,sell_token_id:x.sell_token_id.clone(),sell_token_quantity:x.sell_token_quantity,buy_token_id:x.buy_token_id.clone(),buy_token_quantity:x.buy_token_quantity,sell_token_quantity_remain:x.sell_token_quantity,state:State::Active as i32,..Default::default()};put(c,StoreKind::MarketAccount,&ma.owner_address,&ma)?;put(c,StoreKind::MarketOrder,&id,&taker)?;
 let keys=price_keys(c,&x.buy_token_id,&x.sell_token_id)?;let mut price_index=0usize;let mut attempts=0usize;'outer: loop{if taker.sell_token_quantity_remain==0{break}let (_key,ids)=loop{let Some(key)=keys.get(price_index)else{break 'outer};match c.get(StoreKind::MarketPairPriceToOrder,key)?{Some(value)=>break (key,MarketOrderIdList::decode(value.as_slice()).map_err(|e|ActuatorError::execution(e.to_string()))?),None=>price_index+=1}};let mut maker:MarketOrder=decode(c,StoreKind::MarketOrder,&ids.head,"orderId not exists")?;if !price_matches(&taker,&maker){break}attempts+=1;let can_buy=ratio_mul(taker.sell_token_quantity_remain,maker.sell_token_quantity,maker.buy_token_quantity)?;if can_buy==0{taker.sell_token_quantity_return=taker.sell_token_quantity_remain;add_balance(c,&mut taker_account,&taker.sell_token_id,taker.sell_token_quantity_remain)?;taker.sell_token_quantity_remain=0;break}if attempts>=MAX_MATCH_NUM{break}
 let (taker_get,maker_get)=if can_buy<maker.sell_token_quantity_remain{(can_buy,taker.sell_token_quantity_remain)}else{(maker.sell_token_quantity_remain,ratio_mul(maker.sell_token_quantity_remain,maker.buy_token_quantity,maker.sell_token_quantity)?)};taker.sell_token_quantity_remain=checked_sub(taker.sell_token_quantity_remain,maker_get)?;maker.sell_token_quantity_remain=checked_sub(maker.sell_token_quantity_remain,taker_get)?;add_balance(c,&mut taker_account,&taker.buy_token_id,taker_get)?;let mut maker_account=account(c,&maker.owner_address)?;add_balance(c,&mut maker_account,&maker.buy_token_id,maker_get)?;put_account(c,&maker_account)?;r.order_details.push(MarketOrderDetail{maker_order_id:maker.order_id.clone(),taker_order_id:id.clone(),fill_sell_quantity:maker_get,fill_buy_quantity:taker_get});if attempts>MAX_MATCH_NUM{if maker.sell_token_quantity_remain==0{maker.state=State::Inactive as i32;remove_account_order(c,&maker)?}put(c,StoreKind::MarketOrder,&maker.order_id,&maker)?;if maker.sell_token_quantity_remain==0{let key=pair_price_key(&maker.sell_token_id,&maker.buy_token_id,maker.sell_token_quantity,maker.buy_token_quantity).map_err(|e|ActuatorError::execution(e.to_string()))?;c.put(StoreKind::MarketPairPriceToOrder,&key,&[])?}return Err(ActuatorError::validation("Too many matches. MAX_MATCH_NUM = 20"))}if maker.sell_token_quantity_remain==0{maker.state=State::Inactive as i32;remove_account_order(c,&maker)?;unlink(c,&mut maker)?}put(c,StoreKind::MarketOrder,&maker.order_id,&maker)?;if taker.sell_token_quantity_remain==0{taker.state=State::Inactive as i32;remove_account_order(c,&taker)?;break 'outer}}
 if taker.sell_token_quantity_remain!=0{append(c,&mut taker)?}put(c,StoreKind::MarketOrder,&id,&taker)?;put_account(c,&taker_account)?;r.order_id=id;r.fee=fee;Ok(())}
}

pub struct MarketCancelOrderActuator{any:Any,contract:MarketCancelOrderContract}
impl MarketCancelOrderActuator{pub fn new(any:Any)->Result<Self,ActuatorError>{let contract=decode_typed_any(&any,"protocol.MarketCancelOrderContract")?;Ok(Self{any,contract})}pub fn raw_any(&self)->&Any{&self.any}}
impl Actuator for MarketCancelOrderActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{if c.dynamic_long("ALLOW_MARKET_TRANSACTION")?!=1{return Err(ActuatorError::validation("Not support Market Transaction"))}if !valid_address(&self.contract.owner_address){return Err(ActuatorError::validation("Invalid address"))}let a=account(c,&self.contract.owner_address)?;let o:MarketOrder=decode(c,StoreKind::MarketOrder,&self.contract.order_id,"orderId not exists")?;if o.owner_address!=self.contract.owner_address{return Err(ActuatorError::validation("Order does not belong to the account!"))}if o.state!=State::Active as i32{return Err(ActuatorError::validation("Order is not active!"))}let fee=c.dynamic_long("MARKET_CANCEL_FEE")?;if a.balance<fee{return Err(ActuatorError::validation("No enough balance !"))}Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,r:&mut ActuatorResult)->Result<(),ActuatorError>{let fee=c.dynamic_long("MARKET_CANCEL_FEE")?;let mut a=account(c,&self.contract.owner_address)?;charge_fee(c,&mut a,fee)?;let mut o:MarketOrder=decode(c,StoreKind::MarketOrder,&self.contract.order_id,"orderId not exists")?;add_balance(c,&mut a,&o.sell_token_id,o.sell_token_quantity_remain)?;o.sell_token_quantity_remain=0;o.state=State::Canceled as i32;remove_account_order(c,&o)?;unlink(c,&mut o)?;put(c,StoreKind::MarketOrder,&o.order_id,&o)?;put_account(c,&a)?;r.fee=fee;Ok(())}}
