use tron_protocol::{google::protobuf::Any, protocol::{smart_contract::Abi, Account, ClearAbiContract, SmartContract, UpdateBrokerageContract, UpdateEnergyLimitContract, UpdateSettingContract}};
use tron_state::{keys::delegation_brokerage_key, StoreKind};
use crate::{context::{decode_typed_any, valid_address}, Actuator, ActuatorError, ActuatorResult, ExecutionContext, ValidationContext};

fn require_owner(c:&ExecutionContext<'_>,owner:&[u8],contract_address:&[u8],missing:&'static str)->Result<SmartContract,ActuatorError>{if !valid_address(owner){return Err(ActuatorError::validation("Invalid address"))}let owner_hex=||owner.iter().map(|byte|format!("{byte:02x}")).collect::<String>();let _:Account=c.decode(StoreKind::Account,owner,"Account does not exist").map_err(|error|if error.message=="Account does not exist"{let suffix=if missing=="Contract not exists"{"not exists"}else{"does not exist"};ActuatorError::validation(format!("Account[{}] {suffix}",owner_hex()))}else{error})?;let contract:SmartContract=c.decode(StoreKind::Contract,contract_address,missing)?;if contract.origin_address!=owner{return Err(ActuatorError::validation(format!("Account[{}] is not the owner of the contract",owner_hex())))}Ok(contract)}
macro_rules! constructor {($name:ident,$ty:ty,$full:literal)=>{impl $name{pub fn new(any:Any)->Result<Self,ActuatorError>{let contract=decode_typed_any(&any,$full)?;Ok(Self{any,contract})}pub fn raw_any(&self)->&Any{&self.any}}};}

pub struct UpdateSettingActuator{any:Any,contract:UpdateSettingContract} constructor!(UpdateSettingActuator,UpdateSettingContract,"protocol.UpdateSettingContract");
impl Actuator for UpdateSettingActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{if !(0..=100).contains(&self.contract.consume_user_resource_percent){return Err(ActuatorError::validation("percent not in [0, 100]"))}require_owner(c,&self.contract.owner_address,&self.contract.contract_address,"Contract does not exist")?;Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,_:&mut ActuatorResult)->Result<(),ActuatorError>{let mut deployed:SmartContract=c.decode(StoreKind::Contract,&self.contract.contract_address,"Contract does not exist")?;deployed.consume_user_resource_percent=self.contract.consume_user_resource_percent;c.put_message(StoreKind::Contract,&self.contract.contract_address,&deployed)}}

pub struct UpdateEnergyLimitActuator{any:Any,contract:UpdateEnergyLimitContract} constructor!(UpdateEnergyLimitActuator,UpdateEnergyLimitContract,"protocol.UpdateEnergyLimitContract");
impl Actuator for UpdateEnergyLimitActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{if c.dynamic_long("ALLOW_TVM_CONSTANTINOPLE").unwrap_or(1)!=1{return Err(ActuatorError::validation("contract type error, unexpected type [UpdateEnergyLimitContract]"))}if self.contract.origin_energy_limit<=0{return Err(ActuatorError::validation("origin energy limit must be > 0"))}require_owner(c,&self.contract.owner_address,&self.contract.contract_address,"Contract does not exist")?;Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,_:&mut ActuatorResult)->Result<(),ActuatorError>{let mut deployed:SmartContract=c.decode(StoreKind::Contract,&self.contract.contract_address,"Contract does not exist")?;deployed.origin_energy_limit=self.contract.origin_energy_limit;c.put_message(StoreKind::Contract,&self.contract.contract_address,&deployed)}}

pub struct ClearAbiActuator{any:Any,contract:ClearAbiContract} constructor!(ClearAbiActuator,ClearAbiContract,"protocol.ClearABIContract");
impl Actuator for ClearAbiActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{if c.dynamic_long("ALLOW_TVM_CONSTANTINOPLE").unwrap_or(1)!=1{return Err(ActuatorError::validation("contract type error,unexpected type [ClearABIContract]"))}require_owner(c,&self.contract.owner_address,&self.contract.contract_address,"Contract not exists")?;Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,_:&mut ActuatorResult)->Result<(),ActuatorError>{c.put_message(StoreKind::Abi,&self.contract.contract_address,&Abi::default())}}

pub struct UpdateBrokerageActuator{any:Any,contract:UpdateBrokerageContract} constructor!(UpdateBrokerageActuator,UpdateBrokerageContract,"protocol.UpdateBrokerageContract");
impl Actuator for UpdateBrokerageActuator{fn owner_address(&self)->Result<&[u8],ActuatorError>{Ok(&self.contract.owner_address)}fn validate(&self,c:&ValidationContext<'_>)->Result<(),ActuatorError>{if !valid_address(&self.contract.owner_address){return Err(ActuatorError::validation("Invalid ownerAddress"))}if !(0..=100).contains(&self.contract.brokerage){return Err(ActuatorError::validation("Invalid brokerage"))}if c.get(StoreKind::Witness,&self.contract.owner_address)?.is_none(){return Err(ActuatorError::validation(format!("Not existed witness:{}",self.contract.owner_address.iter().map(|byte|format!("{byte:02x}")).collect::<String>())))}Ok(())}fn execute_in(&self,c:&mut ExecutionContext<'_>,_:&mut ActuatorResult)->Result<(),ActuatorError>{let key=delegation_brokerage_key(-1,&self.contract.owner_address);c.put(StoreKind::Delegation,&key,&self.contract.brokerage.to_be_bytes())}}
