use tron_protocol::protocol::{self, transaction::{result::{Code,ContractResult as ProtoContractResult},Result as TransactionResult}, InternalTransaction, TransactionInfo};
use tron_state::{Session,StoreKind};
use tron_tvm::{ContractResult,InternalTransactionRecord,TvmLog};
use crate::{ActuatorResult,Receipt,ReceiptError,RuntimeResult};

#[derive(Clone,Copy,Debug,Eq,PartialEq)]pub enum TraceKind{NonVm,Create,Trigger}
#[derive(Clone,Debug,Eq,PartialEq)]pub enum TraceError{MissingRuntime,ReceiptMismatch{expected:ContractResult,actual:ContractResult},State(String),Receipt(ReceiptError)}
impl core::fmt::Display for TraceError{fn fmt(&self,f:&mut core::fmt::Formatter<'_>)->core::fmt::Result{match self{Self::MissingRuntime=>f.write_str("transaction trace is not initialized"),Self::ReceiptMismatch{expected,actual}=>write!(f,"different resultCode, expect: {expected:?}, actual: {actual:?}"),Self::State(v)=>f.write_str(v),Self::Receipt(v)=>v.fmt(f)}}}impl std::error::Error for TraceError{}impl From<ReceiptError> for TraceError{fn from(v:ReceiptError)->Self{Self::Receipt(v)}}

#[derive(Clone,Debug,PartialEq)]pub struct TransactionTrace{pub kind:TraceKind,pub receipt:Receipt,pub runtime:Option<RuntimeResult>,pub net_fee_for_bandwidth:bool}
impl TransactionTrace{
 pub fn new(kind:TraceKind)->Self{Self{kind,receipt:Receipt::default(),runtime:None,net_fee_for_bandwidth:true}}
 pub fn initialize(&mut self){self.runtime=None;}
 pub fn set_runtime(&mut self,result:RuntimeResult){if let Some(vm)=&result.vm{self.receipt.set_bill(vm.energy_used);self.receipt.set_penalty(vm.energy_penalty);self.receipt.resource.result=proto_result(vm.contract_result) as i32;}self.runtime=Some(result)}
 pub fn needs_vm(&self)->bool{self.kind!=TraceKind::NonVm}
 pub fn needs_out_of_time_retry(&self,origin:crate::AdmissionOrigin,expected:Option<ContractResult>)->bool{origin==crate::AdmissionOrigin::Block&&self.needs_vm()&&expected!=Some(ContractResult::OutOfTime)&&self.actual_contract_result()==Some(ContractResult::OutOfTime)}
 pub fn actual_contract_result(&self)->Option<ContractResult>{self.runtime.as_ref()?.vm.as_ref().map(|v|v.contract_result)}
 pub fn check_witness(&self,expected:Option<ContractResult>)->Result<(),TraceError>{if !self.needs_vm()||expected.is_none(){return Ok(())}let actual=self.actual_contract_result().ok_or(TraceError::MissingRuntime)?;let expected=expected.expect("checked above");if expected!=actual{return Err(TraceError::ReceiptMismatch{expected,actual})}Ok(())}
 pub fn delete_successful_contracts(&self,session:&Session)->Result<(),TraceError>{let Some(vm)=self.runtime.as_ref().and_then(|v|v.vm.as_ref())else{return Ok(())};if !self.runtime.as_ref().is_some_and(|v|v.runtime_error.is_empty()){return Ok(())}for address in &vm.deleted_accounts{for store in [StoreKind::Abi,StoreKind::Code,StoreKind::Account,StoreKind::Contract]{session.store(store).delete(address.as_bytes()).map_err(|e|TraceError::State(e.to_string()))?;}}Ok(())}
 pub fn transaction_result(&self)->Result<TransactionResult,TraceError>{let runtime=self.runtime.as_ref().ok_or(TraceError::MissingRuntime)?;let mut result=transaction_result(&runtime.actuator);if let Some(vm)=&runtime.vm{result.contract_ret=proto_result(vm.contract_result) as i32;if !runtime.runtime_error.is_empty(){result.ret=Code::Failed as i32;}}Ok(result)}
 pub fn transaction_info(&self,txid:[u8;32],block:Option<(i64,i64)>,save_internal:bool,save_featured_internal:bool,fee_pool_enabled:bool)->Result<TransactionInfo,TraceError>{let runtime=self.runtime.as_ref().ok_or(TraceError::MissingRuntime)?;let actuator=&runtime.actuator;let vm=runtime.vm.as_ref();let mut info=TransactionInfo{ id:txid.to_vec(), fee:self.receipt.total_fee(actuator.fee)?, receipt:Some(self.receipt.resource.clone()), result:if runtime.runtime_error.is_empty(){protocol::transaction_info::Code::Sucess as i32}else{protocol::transaction_info::Code::Failed as i32}, res_message:runtime.runtime_error.as_bytes().to_vec(), asset_issue_id:String::from_utf8_lossy(&actuator.asset_issue_id).into_owned(),withdraw_amount:actuator.withdraw_amount,unfreeze_amount:actuator.unfreeze_amount,exchange_received_amount:actuator.exchange_received_amount,exchange_inject_another_amount:actuator.exchange_inject_another_amount,exchange_withdraw_another_amount:actuator.exchange_withdraw_another_amount,exchange_id:actuator.exchange_id,order_id:actuator.order_id.clone(),order_details:actuator.order_details.clone(),packing_fee:self.receipt.packing_fee(fee_pool_enabled,self.net_fee_for_bandwidth),withdraw_expire_amount:actuator.withdraw_expire_amount,cancel_unfreeze_v2_amount:actuator.cancel_unfreeze_v2_amount.clone(),..TransactionInfo::default()};if let Some((number,time))=block{info.block_number=number;info.block_time_stamp=time;}if let Some(vm)=vm{info.contract_result.push(vm.return_data.clone());info.contract_address=vm.created_contract.map_or_else(Vec::new,|v|v.as_bytes().to_vec());info.log=vm.logs.iter().map(log_info).collect();if save_internal{info.internal_transactions=vm.internal_transactions.iter().filter(|it|save_featured_internal||matches!(it.note.as_slice(),b"call"|b"create"|b"suicide")).map(internal_info).collect();}}else{info.contract_result.push(Vec::new());}Ok(info)}
}

pub fn transaction_result(value:&ActuatorResult)->TransactionResult{TransactionResult{fee:value.fee,ret:value.code as i32,asset_issue_id:String::from_utf8_lossy(&value.asset_issue_id).into_owned(),withdraw_amount:value.withdraw_amount,unfreeze_amount:value.unfreeze_amount,exchange_received_amount:value.exchange_received_amount,exchange_inject_another_amount:value.exchange_inject_another_amount,exchange_withdraw_another_amount:value.exchange_withdraw_another_amount,exchange_id:value.exchange_id,order_id:value.order_id.clone(),order_details:value.order_details.clone(),withdraw_expire_amount:value.withdraw_expire_amount,cancel_unfreeze_v2_amount:value.cancel_unfreeze_v2_amount.clone(),..TransactionResult::default()}}
fn log_info(value:&TvmLog)->protocol::transaction_info::Log{protocol::transaction_info::Log{address:value.address.to_vec(),topics:value.topics.iter().map(|v|v.to_vec()).collect(),data:value.data.clone()}}
fn internal_info(value:&InternalTransactionRecord)->InternalTransaction{let mut call_value_info=vec![protocol::internal_transaction::CallValueInfo{call_value:value.value.to_i64_safe(),token_id:String::new()}];call_value_info.extend(value.token_info.iter().map(|(token,amount)|protocol::internal_transaction::CallValueInfo{call_value:amount.to_i64_safe(),token_id:token.to_i64_safe().to_string()}));InternalTransaction{hash:value.hash.as_bytes().to_vec(),caller_address:value.sender.as_bytes().to_vec(),transfer_to_address:value.transfer_to.map_or_else(Vec::new,|v|v.as_bytes().to_vec()),call_value_info,note:value.note.clone(),rejected:value.rejected,extra:String::from_utf8_lossy(&value.extra).into_owned()}}
pub const fn proto_result(value:ContractResult)->ProtoContractResult{match value{ContractResult::Success=>ProtoContractResult::Success,ContractResult::Revert=>ProtoContractResult::Revert,ContractResult::BadJumpDestination=>ProtoContractResult::BadJumpDestination,ContractResult::OutOfMemory=>ProtoContractResult::OutOfMemory,ContractResult::PrecompiledContract=>ProtoContractResult::PrecompiledContract,ContractResult::StackTooSmall=>ProtoContractResult::StackTooSmall,ContractResult::StackTooLarge=>ProtoContractResult::StackTooLarge,ContractResult::IllegalOperation=>ProtoContractResult::IllegalOperation,ContractResult::OutOfEnergy=>ProtoContractResult::OutOfEnergy,ContractResult::OutOfTime=>ProtoContractResult::OutOfTime,ContractResult::JvmStackOverflow=>ProtoContractResult::JvmStackOverFlow,ContractResult::Unknown=>ProtoContractResult::Unknown,ContractResult::TransferFailed=>ProtoContractResult::TransferFailed,ContractResult::InvalidCode=>ProtoContractResult::InvalidCode}}
