[package]
name = "tron-execution"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
prost.workspace = true
tron-config = { path = "../tron-config" }
tron-crypto = { path = "../tron-crypto" }
tron-primitives = { path = "../tron-primitives" }
tron-protocol = { path = "../tron-protocol" }
tron-state = { path = "../tron-state" }
tron-storage = { path = "../tron-storage" }
tron-shielded = { path = "../tron-shielded" }
tokio = { version = "=1.53.1", features = ["rt", "sync"] }
tron-tvm = { path = "../tron-tvm" }

[dev-dependencies]
serde_json = "=1.0.143"
[lints]
workspace = true
