[package]
name = "tron-execution"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tron-config = { path = "../tron-config" }
tron-crypto = { path = "../tron-crypto" }
tron-primitives = { path = "../tron-primitives" }
tron-protocol = { path = "../tron-protocol" }
tron-state = { path = "../tron-state" }
tron-tvm = { path = "../tron-tvm" }

[lints]
workspace = true
